package com.github.auties00.cobalt.wire.linked.message.media;

import com.github.auties00.cobalt.wire.linked.media.MediaPath;
import com.github.auties00.cobalt.wire.linked.message.context.ContextInfo;
import com.github.auties00.cobalt.wire.core.mixin.InstantSecondsMixin;
import it.auties.protobuf.annotation.*;
import it.auties.protobuf.model.*;

import java.time.Instant;
import java.util.Optional;
import java.util.OptionalInt;
import java.util.OptionalLong;

/**
 * A message whose payload is an encrypted sticker image.
 *
 * <p>Stickers come in several forms inside WhatsApp: static WebP images, animated
 * WebP or Lottie animations, AI-generated stickers and personal avatar stickers.
 * This message carries the standard media download/decrypt metadata shared with
 * other {@link MediaMessage} types plus sticker-specific information such as the
 * animation flag, the first-frame preview sidecar and origin markers (avatar, AI).
 */
@ProtobufMessage(name = "Message.StickerMessage")
public final class StickerMessage implements MediaMessage {
    /**
     * URL of the encrypted sticker image on WhatsApp's media servers.
     */
    @ProtobufProperty(index = 1, type = ProtobufType.STRING)
    String mediaUrl;

    /**
     * SHA-256 digest of the decrypted sticker bytes.
     */
    @ProtobufProperty(index = 2, type = ProtobufType.BYTES)
    byte[] mediaSha256;

    /**
     * SHA-256 digest of the encrypted sticker bytes.
     */
    @ProtobufProperty(index = 3, type = ProtobufType.BYTES)
    byte[] mediaEncryptedSha256;

    /**
     * Symmetric key used to decrypt the sticker payload.
     */
    @ProtobufProperty(index = 4, type = ProtobufType.BYTES)
    byte[] mediaKey;

    /**
     * MIME type of the sticker image, typically {@code image/webp} or
     * {@code application/json} for Lottie stickers.
     */
    @ProtobufProperty(index = 5, type = ProtobufType.STRING)
    String mimetype;

    /**
     * Sticker height in pixels.
     */
    @ProtobufProperty(index = 6, type = ProtobufType.UINT32)
    Integer height;

    /**
     * Sticker width in pixels.
     */
    @ProtobufProperty(index = 7, type = ProtobufType.UINT32)
    Integer width;

    /**
     * CDN direct path of the encrypted sticker.
     */
    @ProtobufProperty(index = 8, type = ProtobufType.STRING)
    String mediaDirectPath;

    /**
     * Size in bytes of the decrypted sticker payload.
     */
    @ProtobufProperty(index = 9, type = ProtobufType.UINT64)
    Long mediaSize;

    /**
     * Moment at which the {@link #mediaKey} was generated.
     */
    @ProtobufProperty(index = 10, type = ProtobufType.INT64, mixins = InstantSecondsMixin.class)
    Instant mediaKeyTimestamp;

    /**
     * Length in bytes of the first frame preview for animated stickers.
     */
    @ProtobufProperty(index = 11, type = ProtobufType.UINT32)
    Integer firstFrameLength;

    /**
     * Sidecar data enabling decryption of the first frame preview for animated
     * stickers.
     */
    @ProtobufProperty(index = 12, type = ProtobufType.BYTES)
    byte[] firstFrameSidecar;

    /**
     * Whether this sticker is animated.
     */
    @ProtobufProperty(index = 13, type = ProtobufType.BOOL)
    Boolean isAnimated;

    /**
     * Inline PNG thumbnail used for static preview.
     */
    @ProtobufProperty(index = 16, type = ProtobufType.BYTES)
    byte[] pngThumbnail;

    /**
     * Contextual information attached to the sticker.
     */
    @ProtobufProperty(index = 17, type = ProtobufType.MESSAGE)
    ContextInfo contextInfo;

    /**
     * Timestamp at which the sticker was originally sent, used for analytics and
     * ordering.
     */
    @ProtobufProperty(index = 18, type = ProtobufType.INT64, mixins = InstantSecondsMixin.class)
    Instant stickerSentTs;

    /**
     * Whether this sticker is a personal avatar sticker.
     */
    @ProtobufProperty(index = 19, type = ProtobufType.BOOL)
    Boolean isAvatar;

    /**
     * Whether this sticker was generated by an AI model.
     */
    @ProtobufProperty(index = 20, type = ProtobufType.BOOL)
    Boolean isAiSticker;

    /**
     * Whether this sticker uses the Lottie animation format.
     */
    @ProtobufProperty(index = 21, type = ProtobufType.BOOL)
    Boolean isLottie;

    /**
     * Accessibility label describing the sticker for screen readers.
     */
    @ProtobufProperty(index = 22, type = ProtobufType.STRING)
    String accessibilityLabel;

    /**
     * Domain identifier that scopes how the {@link #mediaKey} was derived.
     */
    @ProtobufProperty(index = 23, type = ProtobufType.ENUM)
    MediaMessageKeyDomain mediaKeyDomain;


    /**
     * Constructs a new sticker message with the given metadata.
     *
     * @param mediaUrl             the CDN URL of the encrypted sticker
     * @param mediaSha256          the hash of the decrypted sticker
     * @param mediaEncryptedSha256 the hash of the encrypted sticker
     * @param mediaKey             the decryption key
     * @param mimetype             the MIME type
     * @param height               the height in pixels
     * @param width                the width in pixels
     * @param mediaDirectPath      the CDN direct path
     * @param mediaSize            the size of the decrypted sticker
     * @param mediaKeyTimestamp    when the key was generated
     * @param firstFrameLength     first frame length for animated stickers
     * @param firstFrameSidecar    first frame sidecar for animated stickers
     * @param isAnimated           whether the sticker is animated
     * @param pngThumbnail         inline PNG preview bytes
     * @param contextInfo          context information
     * @param stickerSentTs        original send timestamp
     * @param isAvatar             whether the sticker is a personal avatar
     * @param isAiSticker          whether the sticker is AI-generated
     * @param isLottie             whether the sticker is a Lottie animation
     * @param accessibilityLabel   accessibility description
     * @param mediaKeyDomain       key derivation domain
     */
    StickerMessage(String mediaUrl, byte[] mediaSha256, byte[] mediaEncryptedSha256, byte[] mediaKey, String mimetype, Integer height, Integer width, String mediaDirectPath, Long mediaSize, Instant mediaKeyTimestamp, Integer firstFrameLength, byte[] firstFrameSidecar, Boolean isAnimated, byte[] pngThumbnail, ContextInfo contextInfo, Instant stickerSentTs, Boolean isAvatar, Boolean isAiSticker, Boolean isLottie, String accessibilityLabel, MediaMessageKeyDomain mediaKeyDomain) {
        this.mediaUrl = mediaUrl;
        this.mediaSha256 = mediaSha256;
        this.mediaEncryptedSha256 = mediaEncryptedSha256;
        this.mediaKey = mediaKey;
        this.mimetype = mimetype;
        this.height = height;
        this.width = width;
        this.mediaDirectPath = mediaDirectPath;
        this.mediaSize = mediaSize;
        this.mediaKeyTimestamp = mediaKeyTimestamp;
        this.firstFrameLength = firstFrameLength;
        this.firstFrameSidecar = firstFrameSidecar;
        this.isAnimated = isAnimated;
        this.pngThumbnail = pngThumbnail;
        this.contextInfo = contextInfo;
        this.stickerSentTs = stickerSentTs;
        this.isAvatar = isAvatar;
        this.isAiSticker = isAiSticker;
        this.isLottie = isLottie;
        this.accessibilityLabel = accessibilityLabel;
        this.mediaKeyDomain = mediaKeyDomain;
    }

    /**
     * Returns the CDN URL of the encrypted sticker payload.
     *
     * @return the URL, or empty if not yet uploaded
     */
    public Optional<String> url() {
        return Optional.ofNullable(mediaUrl);
    }

    /**
     * Returns the CDN URL of the encrypted sticker payload.
     *
     * @return the URL, or empty if not yet uploaded
     */
    @Override
    public Optional<String> mediaUrl() {
        return Optional.ofNullable(mediaUrl);
    }

    /**
     * Returns the SHA-256 digest of the decrypted sticker.
     *
     * @return the hash, or empty if unknown
     */
    public Optional<byte[]> fileSha256() {
        return Optional.ofNullable(mediaSha256);
    }

    /**
     * Returns the SHA-256 digest of the decrypted sticker.
     *
     * @return the hash, or empty if unknown
     */
    @Override
    public Optional<byte[]> mediaSha256() {
        return Optional.ofNullable(mediaSha256);
    }

    /**
     * Returns the SHA-256 digest of the encrypted sticker.
     *
     * @return the hash, or empty if unknown
     */
    public Optional<byte[]> fileEncSha256() {
        return Optional.ofNullable(mediaEncryptedSha256);
    }

    /**
     * Returns the SHA-256 digest of the encrypted sticker.
     *
     * @return the hash, or empty if unknown
     */
    @Override
    public Optional<byte[]> mediaEncryptedSha256() {
        return Optional.ofNullable(mediaEncryptedSha256);
    }

    /**
     * Returns the decryption key for the sticker payload.
     *
     * @return the key, or empty if unknown
     */
    public Optional<byte[]> mediaKey() {
        return Optional.ofNullable(mediaKey);
    }

    /**
     * Returns the MIME type of the sticker image.
     *
     * @return the MIME type, or empty if unknown
     */
    public Optional<String> mimetype() {
        return Optional.ofNullable(mimetype);
    }

    /**
     * Returns the sticker height in pixels.
     *
     * @return the height, or empty if unknown
     */
    public OptionalInt height() {
        return height == null ? OptionalInt.empty() : OptionalInt.of(height);
    }

    /**
     * Returns the sticker width in pixels.
     *
     * @return the width, or empty if unknown
     */
    public OptionalInt width() {
        return width == null ? OptionalInt.empty() : OptionalInt.of(width);
    }

    /**
     * Returns the CDN direct path of the encrypted sticker.
     *
     * @return the path, or empty if not yet uploaded
     */
    public Optional<String> directPath() {
        return Optional.ofNullable(mediaDirectPath);
    }

    /**
     * Returns the CDN direct path of the encrypted sticker.
     *
     * @return the path, or empty if not yet uploaded
     */
    @Override
    public Optional<String> mediaDirectPath() {
        return Optional.ofNullable(mediaDirectPath);
    }

    /**
     * Returns the size in bytes of the decrypted sticker.
     *
     * @return the size, or empty if unknown
     */
    public OptionalLong fileLength() {
        return mediaSize == null ? OptionalLong.empty() : OptionalLong.of(mediaSize);
    }

    /**
     * Returns the size in bytes of the decrypted sticker.
     *
     * @return the size, or empty if unknown
     */
    @Override
    public OptionalLong mediaSize() {
        return mediaSize == null ? OptionalLong.empty() : OptionalLong.of(mediaSize);
    }

    /**
     * Returns the moment at which the media key was generated.
     *
     * @return the timestamp, or empty if unknown
     */
    public Optional<Instant> mediaKeyTimestamp() {
        return Optional.ofNullable(mediaKeyTimestamp);
    }

    /**
     * Returns the length in bytes of the first animated frame preview.
     *
     * @return the length, or empty if the sticker is not animated
     */
    public OptionalInt firstFrameLength() {
        return firstFrameLength == null ? OptionalInt.empty() : OptionalInt.of(firstFrameLength);
    }

    /**
     * Returns the first-frame sidecar used to decrypt the preview.
     *
     * @return the sidecar, or empty if not present
     */
    public Optional<byte[]> firstFrameSidecar() {
        return Optional.ofNullable(firstFrameSidecar);
    }

    /**
     * Returns whether this sticker is animated.
     *
     * @return {@code true} if the sticker is animated
     */
    public boolean isAnimated() {
        return isAnimated != null && isAnimated;
    }

    /**
     * Returns the inline PNG thumbnail bytes.
     *
     * @return the thumbnail, or empty if not present
     */
    public Optional<byte[]> pngThumbnail() {
        return Optional.ofNullable(pngThumbnail);
    }

    /**
     * Returns the context information attached to this sticker message.
     *
     * @return the context info, or empty if none is attached
     */
    public Optional<ContextInfo> contextInfo() {
        return Optional.ofNullable(contextInfo);
    }

    /**
     * Returns the timestamp at which the sticker was originally sent.
     *
     * @return the timestamp, or empty if unset
     */
    public Optional<Instant> stickerSentTs() {
        return Optional.ofNullable(stickerSentTs);
    }

    /**
     * Returns whether this sticker is a personal avatar sticker.
     *
     * @return {@code true} if it is an avatar sticker
     */
    public boolean isAvatar() {
        return isAvatar != null && isAvatar;
    }

    /**
     * Returns whether this sticker was generated by an AI model.
     *
     * @return {@code true} if AI-generated
     */
    public boolean isAiSticker() {
        return isAiSticker != null && isAiSticker;
    }

    /**
     * Returns whether this sticker uses the Lottie animation format.
     *
     * @return {@code true} if the sticker is a Lottie animation
     */
    public boolean isLottie() {
        return isLottie != null && isLottie;
    }

    /**
     * Returns the accessibility label describing the sticker.
     *
     * @return the label, or empty if not provided
     */
    public Optional<String> accessibilityLabel() {
        return Optional.ofNullable(accessibilityLabel);
    }

    /**
     * Returns the domain identifier that scopes how the media key was derived.
     *
     * @return the key domain, or empty if unset
     */
    public Optional<MediaMessageKeyDomain> mediaKeyDomain() {
        return Optional.ofNullable(mediaKeyDomain);
    }

    /**
     * Returns the {@link MediaPath} classification for sticker media.
     *
     * @return {@link MediaPath#STICKER}
     */
    @Override
    public MediaPath mediaPath() {
        return MediaPath.STICKER;
    }

    /**
     * Updates the CDN URL of the encrypted sticker.
     *
     * @param mediaUrl the new URL, or {@code null} to clear
     */
    @Override
    public void setMediaUrl(String mediaUrl) {
        this.mediaUrl = mediaUrl;
    }

    /**
     * Updates the SHA-256 digest of the decrypted sticker.
     *
     * @param mediaSha256 the new hash, or {@code null} to clear
     */
    @Override
    public void setMediaSha256(byte[] mediaSha256) {
        this.mediaSha256 = mediaSha256;
    }

    /**
     * Updates the SHA-256 digest of the encrypted sticker.
     *
     * @param mediaEncryptedSha256 the new hash, or {@code null} to clear
     */
    @Override
    public void setMediaEncryptedSha256(byte[] mediaEncryptedSha256) {
        this.mediaEncryptedSha256 = mediaEncryptedSha256;
    }

    /**
     * Updates the sticker decryption key.
     *
     * @param mediaKey the new key, or {@code null} to clear
     */
    @Override
    public void setMediaKey(byte[] mediaKey) {
        this.mediaKey = mediaKey;
    }

    /**
     * Updates the MIME type.
     *
     * @param mimetype the new MIME type, or {@code null} to clear
     */
    public void setMimetype(String mimetype) {
        this.mimetype = mimetype;
    }

    /**
     * Updates the sticker height.
     *
     * @param height the new height in pixels, or {@code null} to clear
     */
    public void setHeight(Integer height) {
        this.height = height;
    }

    /**
     * Updates the sticker width.
     *
     * @param width the new width in pixels, or {@code null} to clear
     */
    public void setWidth(Integer width) {
        this.width = width;
    }

    /**
     * Updates the CDN direct path.
     *
     * @param mediaDirectPath the new path, or {@code null} to clear
     */
    @Override
    public void setMediaDirectPath(String mediaDirectPath) {
        this.mediaDirectPath = mediaDirectPath;
    }

    /**
     * Updates the size in bytes of the decrypted sticker.
     *
     * @param mediaSize the new size
     */
    @Override
    public void setMediaSize(long mediaSize) {
        this.mediaSize = mediaSize;
    }

    /**
     * Updates the moment at which the media key was generated.
     *
     * @param mediaKeyTimestamp the new timestamp, or {@code null} to clear
     */
    @Override
    public void setMediaKeyTimestamp(Instant mediaKeyTimestamp) {
        this.mediaKeyTimestamp = mediaKeyTimestamp;
    }

    /**
     * Updates the first frame length.
     *
     * @param firstFrameLength the new length, or {@code null} to clear
     */
    public void setFirstFrameLength(Integer firstFrameLength) {
        this.firstFrameLength = firstFrameLength;
    }

    /**
     * Updates the first frame sidecar.
     *
     * @param firstFrameSidecar the new sidecar, or {@code null} to clear
     */
    public void setFirstFrameSidecar(byte[] firstFrameSidecar) {
        this.firstFrameSidecar = firstFrameSidecar;
    }

    /**
     * Updates the animated flag.
     *
     * @param isAnimated {@code true} if animated, {@code false} or {@code null} otherwise
     */
    public void setAnimated(Boolean isAnimated) {
        this.isAnimated = isAnimated;
    }

    /**
     * Updates the inline PNG thumbnail.
     *
     * @param pngThumbnail the new thumbnail, or {@code null} to clear
     */
    public void setPngThumbnail(byte[] pngThumbnail) {
        this.pngThumbnail = pngThumbnail;
    }

    /**
     * Updates the context information attached to this sticker message.
     *
     * @param contextInfo the new context info, or {@code null} to clear
     */
    public void setContextInfo(ContextInfo contextInfo) {
        this.contextInfo = contextInfo;
    }

    /**
     * Updates the original send timestamp.
     *
     * @param stickerSentTs the new timestamp, or {@code null} to clear
     */
    public void setStickerSentTs(Instant stickerSentTs) {
        this.stickerSentTs = stickerSentTs;
    }

    /**
     * Updates the avatar sticker flag.
     *
     * @param isAvatar {@code true} if this is an avatar sticker, {@code false} or {@code null} otherwise
     */
    public void setAvatar(Boolean isAvatar) {
        this.isAvatar = isAvatar;
    }

    /**
     * Updates the AI-generated flag.
     *
     * @param isAiSticker {@code true} if AI-generated, {@code false} or {@code null} otherwise
     */
    public void setAiSticker(Boolean isAiSticker) {
        this.isAiSticker = isAiSticker;
    }

    /**
     * Updates the Lottie format flag.
     *
     * @param isLottie {@code true} if this is a Lottie sticker, {@code false} or {@code null} otherwise
     */
    public void setLottie(Boolean isLottie) {
        this.isLottie = isLottie;
    }

    /**
     * Updates the accessibility label.
     *
     * @param accessibilityLabel the new label, or {@code null} to clear
     */
    public void setAccessibilityLabel(String accessibilityLabel) {
        this.accessibilityLabel = accessibilityLabel;
    }

    /**
     * Updates the key derivation domain.
     *
     * @param mediaKeyDomain the new domain, or {@code null} to clear
     */
    public void setMediaKeyDomain(MediaMessageKeyDomain mediaKeyDomain) {
        this.mediaKeyDomain = mediaKeyDomain;
    }
}
