package com.github.auties00.cobalt.wire.stanza.iq.push;

import com.github.auties00.cobalt.meta.annotation.WhatsAppWebExport;
import com.github.auties00.cobalt.meta.annotation.WhatsAppWebModule;
import com.github.auties00.cobalt.meta.model.WhatsAppAdaptation;
import com.github.auties00.cobalt.wire.core.jid.JidServer;
import com.github.auties00.cobalt.stanza.model.StanzaBuilder;
import com.github.auties00.cobalt.wire.stanza.iq.IqStanza;
import com.github.auties00.cobalt.wire.core.util.RandomIdUtils;

/**
 * Requests the server-side push key used to validate inbound web-push payloads.
 *
 * <p>This is the outbound {@code <iq xmlns="urn:xmpp:whatsapp:push" type="get">} stanza of the
 * browser-push subscription flow. It is sent once the session confirms that a service-worker push
 * subscription is missing; the relay replies with its server public key (the {@code webserverkey}),
 * which is then handed to the browser's {@code PushManager.subscribe} so the browser accepts the
 * relay's push messages for the lifetime of the subscription. The request carries no payload; the
 * relay derives the reply entirely from the authenticated session. The matching inbound reply is
 * modelled by {@link IqGetPushServerSettingsResponse}.
 */
@WhatsAppWebModule(moduleName = "WAWebGetPushServerSettingsJob")
public final class IqGetPushServerSettingsRequest implements IqStanza.Request {
    /**
     * Constructs a new query-push-server-settings request.
     *
     * <p>The instance is stateless; every instance produces the same stanza shape apart from the
     * randomised stanza id assigned at {@link #toStanza()} time.
     */
    public IqGetPushServerSettingsRequest() {
    }

    /**
     * {@inheritDoc}
     *
     * <p>Produces a {@code <iq xmlns="urn:xmpp:whatsapp:push" type="get">} envelope addressed to
     * {@link JidServer#user()} and wrapping a single bare {@code <settings/>} child. The stanza id
     * is freshly generated by {@link RandomIdUtils#newId()} on each call.
     *
     * @return a {@link StanzaBuilder} carrying the {@code <iq>} envelope and the {@code <settings/>}
     *         payload, never {@code null}
     */
    @Override
    @WhatsAppWebExport(moduleName = "WAWebGetPushServerSettingsJob",
            exports = "getPushServerSettings", adaptation = WhatsAppAdaptation.DIRECT)
    public StanzaBuilder toStanza() {
        var settingsNode = new StanzaBuilder()
                .description("settings")
                .build();
        return new StanzaBuilder()
                .description("iq")
                .attribute("id", RandomIdUtils.newId())
                .attribute("xmlns", "urn:xmpp:whatsapp:push")
                .attribute("to", JidServer.user())
                .attribute("type", "get")
                .content(settingsNode);
    }

    /**
     * Compares this request to another object for equality.
     *
     * <p>Two requests are equal whenever they share the exact runtime class; the type carries no
     * state, so identity of class is sufficient.
     *
     * @param obj the object to compare against
     * @return {@code true} if {@code obj} is a request of the same class, otherwise {@code false}
     */
    @Override
    public boolean equals(Object obj) {
        if (obj == this) {
            return true;
        }
        return obj != null && obj.getClass() == this.getClass();
    }

    /**
     * Returns a hash code consistent with {@link #equals(Object)}.
     *
     * <p>Because the type is stateless, the constant class hash is returned so that all instances
     * hash identically.
     *
     * @return the class-derived hash code
     */
    @Override
    public int hashCode() {
        return IqGetPushServerSettingsRequest.class.hashCode();
    }

    /**
     * Returns a debugging representation of this request.
     *
     * @return a fixed string describing the empty request
     */
    @Override
    public String toString() {
        return "IqGetPushServerSettingsRequest[]";
    }
}
