package com.github.auties00.cobalt.wire.linked.bot.rendering;

import com.github.auties00.cobalt.wire.core.mixin.InstantMillisMixin;
import it.auties.protobuf.annotation.ProtobufEnum;
import it.auties.protobuf.annotation.ProtobufEnumIndex;
import it.auties.protobuf.annotation.ProtobufMessage;
import it.auties.protobuf.annotation.ProtobufProperty;
import it.auties.protobuf.model.ProtobufType;

import java.time.Instant;
import java.util.Optional;

/**
 * Metadata describing an encrypted media file generated by the AI bot, such as
 * an image produced by the "Imagine" feature or a face image from the "MeMe"
 * (personalized avatar) feature.
 *
 * <p>This type carries all the information needed to download and decrypt the
 * media from WhatsApp's CDN: the SHA-256 hashes, the media encryption key, and
 * the direct path to the file. It also includes the MIME type and an
 * {@linkplain OrientationType orientation hint} for UI layout.
 *
 * <p>Instances of this type appear in {@link BotUnifiedResponseMutation.MediaDetailsMetadata}
 * for high-resolution and preview variants of bot-generated media.
 */
@ProtobufMessage(name = "BotMediaMetadata")
public final class BotMediaMetadata {
    /**
     * The base64-encoded SHA-256 hash of the decrypted media file.
     */
    @ProtobufProperty(index = 1, type = ProtobufType.STRING)
    String fileSha256;

    /**
     * The base64-encoded encryption key used to decrypt the media file
     * downloaded from the CDN.
     */
    @ProtobufProperty(index = 2, type = ProtobufType.STRING)
    String mediaKey;

    /**
     * The base64-encoded SHA-256 hash of the encrypted media file as stored on
     * the CDN.
     */
    @ProtobufProperty(index = 3, type = ProtobufType.STRING)
    String fileEncSha256;

    /**
     * The CDN path for downloading the encrypted media file, for example
     * {@code "/v/t62.7118-24/12345_n.enc"}.
     */
    @ProtobufProperty(index = 4, type = ProtobufType.STRING)
    String directPath;

    /**
     * The timestamp at which the {@linkplain #mediaKey() media key} was
     * generated, represented in epoch milliseconds.
     */
    @ProtobufProperty(index = 5, type = ProtobufType.INT64, mixins = InstantMillisMixin.class)
    Instant mediaKeyTimestamp;

    /**
     * The MIME type of the media file, for example {@code "image/jpeg"} or
     * {@code "image/png"}.
     */
    @ProtobufProperty(index = 6, type = ProtobufType.STRING)
    String mimetype;

    /**
     * The orientation hint for how this media should be laid out in the chat
     * bubble.
     */
    @ProtobufProperty(index = 7, type = ProtobufType.ENUM)
    OrientationType orientationType;


    /**
     * Constructs a new {@code BotMediaMetadata} with the specified values.
     *
     * @param fileSha256        the SHA-256 hash of the decrypted file, or {@code null}
     * @param mediaKey          the media encryption key, or {@code null}
     * @param fileEncSha256     the SHA-256 hash of the encrypted file, or {@code null}
     * @param directPath        the CDN direct path, or {@code null}
     * @param mediaKeyTimestamp the media key generation timestamp, or {@code null}
     * @param mimetype          the MIME type, or {@code null}
     * @param orientationType   the orientation hint, or {@code null}
     */
    BotMediaMetadata(String fileSha256, String mediaKey, String fileEncSha256, String directPath, Instant mediaKeyTimestamp, String mimetype, OrientationType orientationType) {
        this.fileSha256 = fileSha256;
        this.mediaKey = mediaKey;
        this.fileEncSha256 = fileEncSha256;
        this.directPath = directPath;
        this.mediaKeyTimestamp = mediaKeyTimestamp;
        this.mimetype = mimetype;
        this.orientationType = orientationType;
    }

    /**
     * Returns the base64-encoded SHA-256 hash of the decrypted media file.
     *
     * @return an {@code Optional} describing the file hash, or an empty
     *         {@code Optional} if not set
     */
    public Optional<String> fileSha256() {
        return Optional.ofNullable(fileSha256);
    }

    /**
     * Returns the base64-encoded encryption key for the media file.
     *
     * @return an {@code Optional} describing the media key, or an empty
     *         {@code Optional} if not set
     */
    public Optional<String> mediaKey() {
        return Optional.ofNullable(mediaKey);
    }

    /**
     * Returns the base64-encoded SHA-256 hash of the encrypted media file.
     *
     * @return an {@code Optional} describing the encrypted file hash, or an
     *         empty {@code Optional} if not set
     */
    public Optional<String> fileEncSha256() {
        return Optional.ofNullable(fileEncSha256);
    }

    /**
     * Returns the CDN path for downloading the encrypted media file.
     *
     * @return an {@code Optional} describing the direct path, or an empty
     *         {@code Optional} if not set
     */
    public Optional<String> directPath() {
        return Optional.ofNullable(directPath);
    }

    /**
     * Returns the timestamp at which the media key was generated.
     *
     * @return an {@code Optional} describing the timestamp, or an empty
     *         {@code Optional} if not set
     */
    public Optional<Instant> mediaKeyTimestamp() {
        return Optional.ofNullable(mediaKeyTimestamp);
    }

    /**
     * Returns the MIME type of the media file.
     *
     * @return an {@code Optional} describing the MIME type, or an empty
     *         {@code Optional} if not set
     */
    public Optional<String> mimetype() {
        return Optional.ofNullable(mimetype);
    }

    /**
     * Returns the orientation hint for this media's layout.
     *
     * @return an {@code Optional} describing the orientation type, or an empty
     *         {@code Optional} if not set
     */
    public Optional<OrientationType> orientationType() {
        return Optional.ofNullable(orientationType);
    }

    /**
     * Sets the base64-encoded SHA-256 hash of the decrypted media file.
     *
     * @param fileSha256 the new file hash, or {@code null}
     */
    public void setFileSha256(String fileSha256) {
        this.fileSha256 = fileSha256;
    }

    /**
     * Sets the base64-encoded encryption key for the media file.
     *
     * @param mediaKey the new media key, or {@code null}
     */
    public void setMediaKey(String mediaKey) {
        this.mediaKey = mediaKey;
    }

    /**
     * Sets the base64-encoded SHA-256 hash of the encrypted media file.
     *
     * @param fileEncSha256 the new encrypted file hash, or {@code null}
     */
    public void setFileEncSha256(String fileEncSha256) {
        this.fileEncSha256 = fileEncSha256;
    }

    /**
     * Sets the CDN path for downloading the encrypted media file.
     *
     * @param directPath the new direct path, or {@code null}
     */
    public void setDirectPath(String directPath) {
        this.directPath = directPath;
    }

    /**
     * Sets the timestamp at which the media key was generated.
     *
     * @param mediaKeyTimestamp the new timestamp, or {@code null}
     */
    public void setMediaKeyTimestamp(Instant mediaKeyTimestamp) {
        this.mediaKeyTimestamp = mediaKeyTimestamp;
    }

    /**
     * Sets the MIME type of the media file.
     *
     * @param mimetype the new MIME type, or {@code null}
     */
    public void setMimetype(String mimetype) {
        this.mimetype = mimetype;
    }

    /**
     * Sets the orientation hint for this media's layout.
     *
     * @param orientationType the new orientation type, or {@code null}
     */
    public void setOrientationType(OrientationType orientationType) {
        this.orientationType = orientationType;
    }

    /**
     * The horizontal alignment used when rendering a bot-generated media
     * element inside a chat bubble.
     */
    @ProtobufEnum(name = "BotMediaMetadata.OrientationType")
    public static enum OrientationType {
        /**
         * The media is centered within the chat bubble.
         */
        CENTER(1),

        /**
         * The media is aligned to the left of the chat bubble.
         */
        LEFT(2),

        /**
         * The media is aligned to the right of the chat bubble.
         */
        RIGHT(3);

        /**
         * Constructs a new {@code OrientationType} with the given protobuf index.
         *
         * @param index the protobuf enum index
         */
        OrientationType(@ProtobufEnumIndex int index) {
            this.index = index;
        }

        /**
         * The protobuf enum index for this orientation type.
         */
        final int index;

        /**
         * Returns the protobuf index of this orientation type.
         *
         * @return the protobuf index
         */
        public int index() {
            return this.index;
        }
    }
}
