// Generated by jextract

package com.github.auties00.cobalt.calls.media.video.codec.h264.bindings;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class CobaltOpenH264 {

    CobaltOpenH264() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();
    static final boolean TRACE_DOWNCALLS = Boolean.getBoolean("jextract.trace.downcalls");

    static void traceDowncall(String name, Object... args) {
         String traceArgs = Arrays.stream(args)
                       .map(Object::toString)
                       .collect(Collectors.joining(", "));
         System.out.printf("%s(%s)\n", name, traceArgs);
    }

    static MemorySegment findOrThrow(String symbol) {
        return SYMBOL_LOOKUP.find(symbol)
            .orElseThrow(() -> new UnsatisfiedLinkError("unresolved symbol: " + symbol));
    }

    static MethodHandle upcallHandle(Class<?> fi, String name, FunctionDescriptor fdesc) {
        try {
            return MethodHandles.lookup().findVirtual(fi, name, fdesc.toMethodType());
        } catch (ReflectiveOperationException ex) {
            throw new AssertionError(ex);
        }
    }

    static MemoryLayout align(MemoryLayout layout, long align) {
        return switch (layout) {
            case PaddingLayout p -> p;
            case ValueLayout v -> v.withByteAlignment(align);
            case GroupLayout g -> {
                MemoryLayout[] alignedMembers = g.memberLayouts().stream()
                        .map(m -> align(m, align)).toArray(MemoryLayout[]::new);
                yield g instanceof StructLayout ?
                        MemoryLayout.structLayout(alignedMembers) : MemoryLayout.unionLayout(alignedMembers);
            }
            case SequenceLayout s -> MemoryLayout.sequenceLayout(s.elementCount(), align(s.elementLayout(), align));
        };
    }

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.loaderLookup()
            .or(Linker.nativeLinker().defaultLookup());

    public static final ValueLayout.OfBoolean C_BOOL = ValueLayout.JAVA_BOOLEAN;
    public static final ValueLayout.OfByte C_CHAR = ValueLayout.JAVA_BYTE;
    public static final ValueLayout.OfShort C_SHORT = ValueLayout.JAVA_SHORT;
    public static final ValueLayout.OfInt C_INT = ValueLayout.JAVA_INT;
    public static final ValueLayout.OfLong C_LONG_LONG = ValueLayout.JAVA_LONG;
    public static final ValueLayout.OfFloat C_FLOAT = ValueLayout.JAVA_FLOAT;
    public static final ValueLayout.OfDouble C_DOUBLE = ValueLayout.JAVA_DOUBLE;
    public static final AddressLayout C_POINTER = ValueLayout.ADDRESS
            .withTargetLayout(MemoryLayout.sequenceLayout(java.lang.Long.MAX_VALUE, JAVA_BYTE));
    public static final ValueLayout.OfLong C_LONG = ValueLayout.JAVA_LONG;
    private static final int COBALT_H264_USAGE_CAMERA_REALTIME = (int)0L;
    /**
     * {@snippet lang=c :
     * #define COBALT_H264_USAGE_CAMERA_REALTIME 0
     * }
     */
    public static int COBALT_H264_USAGE_CAMERA_REALTIME() {
        return COBALT_H264_USAGE_CAMERA_REALTIME;
    }
    private static final int COBALT_H264_USAGE_SCREEN_REALTIME = (int)1L;
    /**
     * {@snippet lang=c :
     * #define COBALT_H264_USAGE_SCREEN_REALTIME 1
     * }
     */
    public static int COBALT_H264_USAGE_SCREEN_REALTIME() {
        return COBALT_H264_USAGE_SCREEN_REALTIME;
    }
    private static final int COBALT_H264_RC_QUALITY = (int)0L;
    /**
     * {@snippet lang=c :
     * #define COBALT_H264_RC_QUALITY 0
     * }
     */
    public static int COBALT_H264_RC_QUALITY() {
        return COBALT_H264_RC_QUALITY;
    }
    private static final int COBALT_H264_RC_BITRATE = (int)1L;
    /**
     * {@snippet lang=c :
     * #define COBALT_H264_RC_BITRATE 1
     * }
     */
    public static int COBALT_H264_RC_BITRATE() {
        return COBALT_H264_RC_BITRATE;
    }
    private static final int COBALT_H264_RC_BUFFERBASED = (int)2L;
    /**
     * {@snippet lang=c :
     * #define COBALT_H264_RC_BUFFERBASED 2
     * }
     */
    public static int COBALT_H264_RC_BUFFERBASED() {
        return COBALT_H264_RC_BUFFERBASED;
    }
    private static final int COBALT_H264_RC_TIMESTAMP = (int)3L;
    /**
     * {@snippet lang=c :
     * #define COBALT_H264_RC_TIMESTAMP 3
     * }
     */
    public static int COBALT_H264_RC_TIMESTAMP() {
        return COBALT_H264_RC_TIMESTAMP;
    }
    private static final int COBALT_H264_COMPLEXITY_LOW = (int)0L;
    /**
     * {@snippet lang=c :
     * #define COBALT_H264_COMPLEXITY_LOW 0
     * }
     */
    public static int COBALT_H264_COMPLEXITY_LOW() {
        return COBALT_H264_COMPLEXITY_LOW;
    }
    private static final int COBALT_H264_COMPLEXITY_MEDIUM = (int)1L;
    /**
     * {@snippet lang=c :
     * #define COBALT_H264_COMPLEXITY_MEDIUM 1
     * }
     */
    public static int COBALT_H264_COMPLEXITY_MEDIUM() {
        return COBALT_H264_COMPLEXITY_MEDIUM;
    }
    private static final int COBALT_H264_COMPLEXITY_HIGH = (int)2L;
    /**
     * {@snippet lang=c :
     * #define COBALT_H264_COMPLEXITY_HIGH 2
     * }
     */
    public static int COBALT_H264_COMPLEXITY_HIGH() {
        return COBALT_H264_COMPLEXITY_HIGH;
    }
    private static final int COBALT_H264_OK = (int)0L;
    /**
     * {@snippet lang=c :
     * #define COBALT_H264_OK 0
     * }
     */
    public static int COBALT_H264_OK() {
        return COBALT_H264_OK;
    }

    private static class cobalt_h264_version {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltOpenH264.C_POINTER    );

        public static final MemorySegment ADDR = CobaltOpenH264.findOrThrow("cobalt_h264_version");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * const char *cobalt_h264_version()
     * }
     */
    public static FunctionDescriptor cobalt_h264_version$descriptor() {
        return cobalt_h264_version.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * const char *cobalt_h264_version()
     * }
     */
    public static MethodHandle cobalt_h264_version$handle() {
        return cobalt_h264_version.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * const char *cobalt_h264_version()
     * }
     */
    public static MemorySegment cobalt_h264_version$address() {
        return cobalt_h264_version.ADDR;
    }

    /**
     * {@snippet lang=c :
     * const char *cobalt_h264_version()
     * }
     */
    public static MemorySegment cobalt_h264_version() {
        var mh$ = cobalt_h264_version.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_h264_version");
            }
            return (MemorySegment)mh$.invokeExact();
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_h264_encoder_create {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltOpenH264.C_INT,
            CobaltOpenH264.C_INT,
            CobaltOpenH264.C_INT,
            CobaltOpenH264.C_INT,
            CobaltOpenH264.C_INT,
            CobaltOpenH264.C_INT,
            CobaltOpenH264.C_INT,
            CobaltOpenH264.C_INT,
            CobaltOpenH264.C_INT,
            CobaltOpenH264.C_INT,
            CobaltOpenH264.C_INT,
            CobaltOpenH264.C_INT,
            CobaltOpenH264.C_INT,
            CobaltOpenH264.C_INT,
            CobaltOpenH264.C_INT,
            CobaltOpenH264.C_INT,
            CobaltOpenH264.C_POINTER
        );

        public static final MemorySegment ADDR = CobaltOpenH264.findOrThrow("cobalt_h264_encoder_create");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_h264_encoder_create(int32_t width, int32_t height, int32_t targetBitrateBps, int32_t maxBitrateBps, int32_t frameRate, int32_t usageType, int32_t rcMode, int32_t complexity, int32_t temporalLayers, int32_t intraPeriod, int32_t minQp, int32_t maxQp, int32_t idrBitrateRatio, int32_t frameSkip, int32_t longTermReference, void **outCtx)
     * }
     */
    public static FunctionDescriptor cobalt_h264_encoder_create$descriptor() {
        return cobalt_h264_encoder_create.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_h264_encoder_create(int32_t width, int32_t height, int32_t targetBitrateBps, int32_t maxBitrateBps, int32_t frameRate, int32_t usageType, int32_t rcMode, int32_t complexity, int32_t temporalLayers, int32_t intraPeriod, int32_t minQp, int32_t maxQp, int32_t idrBitrateRatio, int32_t frameSkip, int32_t longTermReference, void **outCtx)
     * }
     */
    public static MethodHandle cobalt_h264_encoder_create$handle() {
        return cobalt_h264_encoder_create.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_h264_encoder_create(int32_t width, int32_t height, int32_t targetBitrateBps, int32_t maxBitrateBps, int32_t frameRate, int32_t usageType, int32_t rcMode, int32_t complexity, int32_t temporalLayers, int32_t intraPeriod, int32_t minQp, int32_t maxQp, int32_t idrBitrateRatio, int32_t frameSkip, int32_t longTermReference, void **outCtx)
     * }
     */
    public static MemorySegment cobalt_h264_encoder_create$address() {
        return cobalt_h264_encoder_create.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_h264_encoder_create(int32_t width, int32_t height, int32_t targetBitrateBps, int32_t maxBitrateBps, int32_t frameRate, int32_t usageType, int32_t rcMode, int32_t complexity, int32_t temporalLayers, int32_t intraPeriod, int32_t minQp, int32_t maxQp, int32_t idrBitrateRatio, int32_t frameSkip, int32_t longTermReference, void **outCtx)
     * }
     */
    public static int cobalt_h264_encoder_create(int width, int height, int targetBitrateBps, int maxBitrateBps, int frameRate, int usageType, int rcMode, int complexity, int temporalLayers, int intraPeriod, int minQp, int maxQp, int idrBitrateRatio, int frameSkip, int longTermReference, MemorySegment outCtx) {
        var mh$ = cobalt_h264_encoder_create.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_h264_encoder_create", width, height, targetBitrateBps, maxBitrateBps, frameRate, usageType, rcMode, complexity, temporalLayers, intraPeriod, minQp, maxQp, idrBitrateRatio, frameSkip, longTermReference, outCtx);
            }
            return (int)mh$.invokeExact(width, height, targetBitrateBps, maxBitrateBps, frameRate, usageType, rcMode, complexity, temporalLayers, intraPeriod, minQp, maxQp, idrBitrateRatio, frameSkip, longTermReference, outCtx);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_h264_encoder_set_rates {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltOpenH264.C_INT,
            CobaltOpenH264.C_POINTER,
            CobaltOpenH264.C_INT,
            CobaltOpenH264.C_INT
        );

        public static final MemorySegment ADDR = CobaltOpenH264.findOrThrow("cobalt_h264_encoder_set_rates");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_h264_encoder_set_rates(void *ctx, int32_t targetBitrateBps, int32_t frameRate)
     * }
     */
    public static FunctionDescriptor cobalt_h264_encoder_set_rates$descriptor() {
        return cobalt_h264_encoder_set_rates.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_h264_encoder_set_rates(void *ctx, int32_t targetBitrateBps, int32_t frameRate)
     * }
     */
    public static MethodHandle cobalt_h264_encoder_set_rates$handle() {
        return cobalt_h264_encoder_set_rates.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_h264_encoder_set_rates(void *ctx, int32_t targetBitrateBps, int32_t frameRate)
     * }
     */
    public static MemorySegment cobalt_h264_encoder_set_rates$address() {
        return cobalt_h264_encoder_set_rates.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_h264_encoder_set_rates(void *ctx, int32_t targetBitrateBps, int32_t frameRate)
     * }
     */
    public static int cobalt_h264_encoder_set_rates(MemorySegment ctx, int targetBitrateBps, int frameRate) {
        var mh$ = cobalt_h264_encoder_set_rates.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_h264_encoder_set_rates", ctx, targetBitrateBps, frameRate);
            }
            return (int)mh$.invokeExact(ctx, targetBitrateBps, frameRate);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_h264_encoder_force_idr {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltOpenH264.C_INT,
            CobaltOpenH264.C_POINTER
        );

        public static final MemorySegment ADDR = CobaltOpenH264.findOrThrow("cobalt_h264_encoder_force_idr");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_h264_encoder_force_idr(void *ctx)
     * }
     */
    public static FunctionDescriptor cobalt_h264_encoder_force_idr$descriptor() {
        return cobalt_h264_encoder_force_idr.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_h264_encoder_force_idr(void *ctx)
     * }
     */
    public static MethodHandle cobalt_h264_encoder_force_idr$handle() {
        return cobalt_h264_encoder_force_idr.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_h264_encoder_force_idr(void *ctx)
     * }
     */
    public static MemorySegment cobalt_h264_encoder_force_idr$address() {
        return cobalt_h264_encoder_force_idr.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_h264_encoder_force_idr(void *ctx)
     * }
     */
    public static int cobalt_h264_encoder_force_idr(MemorySegment ctx) {
        var mh$ = cobalt_h264_encoder_force_idr.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_h264_encoder_force_idr", ctx);
            }
            return (int)mh$.invokeExact(ctx);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_h264_encoder_encode {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltOpenH264.C_INT,
            CobaltOpenH264.C_POINTER,
            CobaltOpenH264.C_POINTER,
            CobaltOpenH264.C_LONG,
            CobaltOpenH264.C_INT,
            CobaltOpenH264.C_INT,
            CobaltOpenH264.C_LONG
        );

        public static final MemorySegment ADDR = CobaltOpenH264.findOrThrow("cobalt_h264_encoder_encode");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_h264_encoder_encode(void *ctx, const uint8_t *i420, size_t len, int32_t width, int32_t height, int64_t ptsMillis)
     * }
     */
    public static FunctionDescriptor cobalt_h264_encoder_encode$descriptor() {
        return cobalt_h264_encoder_encode.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_h264_encoder_encode(void *ctx, const uint8_t *i420, size_t len, int32_t width, int32_t height, int64_t ptsMillis)
     * }
     */
    public static MethodHandle cobalt_h264_encoder_encode$handle() {
        return cobalt_h264_encoder_encode.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_h264_encoder_encode(void *ctx, const uint8_t *i420, size_t len, int32_t width, int32_t height, int64_t ptsMillis)
     * }
     */
    public static MemorySegment cobalt_h264_encoder_encode$address() {
        return cobalt_h264_encoder_encode.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_h264_encoder_encode(void *ctx, const uint8_t *i420, size_t len, int32_t width, int32_t height, int64_t ptsMillis)
     * }
     */
    public static int cobalt_h264_encoder_encode(MemorySegment ctx, MemorySegment i420, long len, int width, int height, long ptsMillis) {
        var mh$ = cobalt_h264_encoder_encode.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_h264_encoder_encode", ctx, i420, len, width, height, ptsMillis);
            }
            return (int)mh$.invokeExact(ctx, i420, len, width, height, ptsMillis);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_h264_encoder_get_packet {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltOpenH264.C_INT,
            CobaltOpenH264.C_POINTER,
            CobaltOpenH264.C_POINTER,
            CobaltOpenH264.C_POINTER,
            CobaltOpenH264.C_POINTER
        );

        public static final MemorySegment ADDR = CobaltOpenH264.findOrThrow("cobalt_h264_encoder_get_packet");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_h264_encoder_get_packet(void *ctx, const uint8_t **outBuf, int32_t *outLen, int32_t *outIsKeyframe)
     * }
     */
    public static FunctionDescriptor cobalt_h264_encoder_get_packet$descriptor() {
        return cobalt_h264_encoder_get_packet.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_h264_encoder_get_packet(void *ctx, const uint8_t **outBuf, int32_t *outLen, int32_t *outIsKeyframe)
     * }
     */
    public static MethodHandle cobalt_h264_encoder_get_packet$handle() {
        return cobalt_h264_encoder_get_packet.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_h264_encoder_get_packet(void *ctx, const uint8_t **outBuf, int32_t *outLen, int32_t *outIsKeyframe)
     * }
     */
    public static MemorySegment cobalt_h264_encoder_get_packet$address() {
        return cobalt_h264_encoder_get_packet.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_h264_encoder_get_packet(void *ctx, const uint8_t **outBuf, int32_t *outLen, int32_t *outIsKeyframe)
     * }
     */
    public static int cobalt_h264_encoder_get_packet(MemorySegment ctx, MemorySegment outBuf, MemorySegment outLen, MemorySegment outIsKeyframe) {
        var mh$ = cobalt_h264_encoder_get_packet.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_h264_encoder_get_packet", ctx, outBuf, outLen, outIsKeyframe);
            }
            return (int)mh$.invokeExact(ctx, outBuf, outLen, outIsKeyframe);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_h264_encoder_destroy {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltOpenH264.C_INT,
            CobaltOpenH264.C_POINTER
        );

        public static final MemorySegment ADDR = CobaltOpenH264.findOrThrow("cobalt_h264_encoder_destroy");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_h264_encoder_destroy(void *ctx)
     * }
     */
    public static FunctionDescriptor cobalt_h264_encoder_destroy$descriptor() {
        return cobalt_h264_encoder_destroy.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_h264_encoder_destroy(void *ctx)
     * }
     */
    public static MethodHandle cobalt_h264_encoder_destroy$handle() {
        return cobalt_h264_encoder_destroy.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_h264_encoder_destroy(void *ctx)
     * }
     */
    public static MemorySegment cobalt_h264_encoder_destroy$address() {
        return cobalt_h264_encoder_destroy.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_h264_encoder_destroy(void *ctx)
     * }
     */
    public static int cobalt_h264_encoder_destroy(MemorySegment ctx) {
        var mh$ = cobalt_h264_encoder_destroy.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_h264_encoder_destroy", ctx);
            }
            return (int)mh$.invokeExact(ctx);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_h264_decoder_create {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltOpenH264.C_INT,
            CobaltOpenH264.C_POINTER
        );

        public static final MemorySegment ADDR = CobaltOpenH264.findOrThrow("cobalt_h264_decoder_create");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_h264_decoder_create(void **outCtx)
     * }
     */
    public static FunctionDescriptor cobalt_h264_decoder_create$descriptor() {
        return cobalt_h264_decoder_create.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_h264_decoder_create(void **outCtx)
     * }
     */
    public static MethodHandle cobalt_h264_decoder_create$handle() {
        return cobalt_h264_decoder_create.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_h264_decoder_create(void **outCtx)
     * }
     */
    public static MemorySegment cobalt_h264_decoder_create$address() {
        return cobalt_h264_decoder_create.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_h264_decoder_create(void **outCtx)
     * }
     */
    public static int cobalt_h264_decoder_create(MemorySegment outCtx) {
        var mh$ = cobalt_h264_decoder_create.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_h264_decoder_create", outCtx);
            }
            return (int)mh$.invokeExact(outCtx);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_h264_decoder_decode {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltOpenH264.C_INT,
            CobaltOpenH264.C_POINTER,
            CobaltOpenH264.C_POINTER,
            CobaltOpenH264.C_LONG
        );

        public static final MemorySegment ADDR = CobaltOpenH264.findOrThrow("cobalt_h264_decoder_decode");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_h264_decoder_decode(void *ctx, const uint8_t *data, size_t len)
     * }
     */
    public static FunctionDescriptor cobalt_h264_decoder_decode$descriptor() {
        return cobalt_h264_decoder_decode.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_h264_decoder_decode(void *ctx, const uint8_t *data, size_t len)
     * }
     */
    public static MethodHandle cobalt_h264_decoder_decode$handle() {
        return cobalt_h264_decoder_decode.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_h264_decoder_decode(void *ctx, const uint8_t *data, size_t len)
     * }
     */
    public static MemorySegment cobalt_h264_decoder_decode$address() {
        return cobalt_h264_decoder_decode.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_h264_decoder_decode(void *ctx, const uint8_t *data, size_t len)
     * }
     */
    public static int cobalt_h264_decoder_decode(MemorySegment ctx, MemorySegment data, long len) {
        var mh$ = cobalt_h264_decoder_decode.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_h264_decoder_decode", ctx, data, len);
            }
            return (int)mh$.invokeExact(ctx, data, len);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_h264_decoder_get_frame {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltOpenH264.C_INT,
            CobaltOpenH264.C_POINTER,
            CobaltOpenH264.C_POINTER
        );

        public static final MemorySegment ADDR = CobaltOpenH264.findOrThrow("cobalt_h264_decoder_get_frame");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_h264_decoder_get_frame(void *ctx, void **outImg)
     * }
     */
    public static FunctionDescriptor cobalt_h264_decoder_get_frame$descriptor() {
        return cobalt_h264_decoder_get_frame.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_h264_decoder_get_frame(void *ctx, void **outImg)
     * }
     */
    public static MethodHandle cobalt_h264_decoder_get_frame$handle() {
        return cobalt_h264_decoder_get_frame.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_h264_decoder_get_frame(void *ctx, void **outImg)
     * }
     */
    public static MemorySegment cobalt_h264_decoder_get_frame$address() {
        return cobalt_h264_decoder_get_frame.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_h264_decoder_get_frame(void *ctx, void **outImg)
     * }
     */
    public static int cobalt_h264_decoder_get_frame(MemorySegment ctx, MemorySegment outImg) {
        var mh$ = cobalt_h264_decoder_get_frame.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_h264_decoder_get_frame", ctx, outImg);
            }
            return (int)mh$.invokeExact(ctx, outImg);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_h264_img_plane {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltOpenH264.C_POINTER,
            CobaltOpenH264.C_POINTER,
            CobaltOpenH264.C_INT
        );

        public static final MemorySegment ADDR = CobaltOpenH264.findOrThrow("cobalt_h264_img_plane");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * const uint8_t *cobalt_h264_img_plane(void *img, int32_t plane)
     * }
     */
    public static FunctionDescriptor cobalt_h264_img_plane$descriptor() {
        return cobalt_h264_img_plane.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * const uint8_t *cobalt_h264_img_plane(void *img, int32_t plane)
     * }
     */
    public static MethodHandle cobalt_h264_img_plane$handle() {
        return cobalt_h264_img_plane.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * const uint8_t *cobalt_h264_img_plane(void *img, int32_t plane)
     * }
     */
    public static MemorySegment cobalt_h264_img_plane$address() {
        return cobalt_h264_img_plane.ADDR;
    }

    /**
     * {@snippet lang=c :
     * const uint8_t *cobalt_h264_img_plane(void *img, int32_t plane)
     * }
     */
    public static MemorySegment cobalt_h264_img_plane(MemorySegment img, int plane) {
        var mh$ = cobalt_h264_img_plane.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_h264_img_plane", img, plane);
            }
            return (MemorySegment)mh$.invokeExact(img, plane);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_h264_img_stride {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltOpenH264.C_INT,
            CobaltOpenH264.C_POINTER,
            CobaltOpenH264.C_INT
        );

        public static final MemorySegment ADDR = CobaltOpenH264.findOrThrow("cobalt_h264_img_stride");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_h264_img_stride(void *img, int32_t plane)
     * }
     */
    public static FunctionDescriptor cobalt_h264_img_stride$descriptor() {
        return cobalt_h264_img_stride.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_h264_img_stride(void *img, int32_t plane)
     * }
     */
    public static MethodHandle cobalt_h264_img_stride$handle() {
        return cobalt_h264_img_stride.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_h264_img_stride(void *img, int32_t plane)
     * }
     */
    public static MemorySegment cobalt_h264_img_stride$address() {
        return cobalt_h264_img_stride.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_h264_img_stride(void *img, int32_t plane)
     * }
     */
    public static int cobalt_h264_img_stride(MemorySegment img, int plane) {
        var mh$ = cobalt_h264_img_stride.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_h264_img_stride", img, plane);
            }
            return (int)mh$.invokeExact(img, plane);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_h264_img_width {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltOpenH264.C_INT,
            CobaltOpenH264.C_POINTER
        );

        public static final MemorySegment ADDR = CobaltOpenH264.findOrThrow("cobalt_h264_img_width");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_h264_img_width(void *img)
     * }
     */
    public static FunctionDescriptor cobalt_h264_img_width$descriptor() {
        return cobalt_h264_img_width.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_h264_img_width(void *img)
     * }
     */
    public static MethodHandle cobalt_h264_img_width$handle() {
        return cobalt_h264_img_width.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_h264_img_width(void *img)
     * }
     */
    public static MemorySegment cobalt_h264_img_width$address() {
        return cobalt_h264_img_width.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_h264_img_width(void *img)
     * }
     */
    public static int cobalt_h264_img_width(MemorySegment img) {
        var mh$ = cobalt_h264_img_width.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_h264_img_width", img);
            }
            return (int)mh$.invokeExact(img);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_h264_img_height {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltOpenH264.C_INT,
            CobaltOpenH264.C_POINTER
        );

        public static final MemorySegment ADDR = CobaltOpenH264.findOrThrow("cobalt_h264_img_height");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_h264_img_height(void *img)
     * }
     */
    public static FunctionDescriptor cobalt_h264_img_height$descriptor() {
        return cobalt_h264_img_height.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_h264_img_height(void *img)
     * }
     */
    public static MethodHandle cobalt_h264_img_height$handle() {
        return cobalt_h264_img_height.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_h264_img_height(void *img)
     * }
     */
    public static MemorySegment cobalt_h264_img_height$address() {
        return cobalt_h264_img_height.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_h264_img_height(void *img)
     * }
     */
    public static int cobalt_h264_img_height(MemorySegment img) {
        var mh$ = cobalt_h264_img_height.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_h264_img_height", img);
            }
            return (int)mh$.invokeExact(img);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_h264_decoder_destroy {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltOpenH264.C_INT,
            CobaltOpenH264.C_POINTER
        );

        public static final MemorySegment ADDR = CobaltOpenH264.findOrThrow("cobalt_h264_decoder_destroy");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_h264_decoder_destroy(void *ctx)
     * }
     */
    public static FunctionDescriptor cobalt_h264_decoder_destroy$descriptor() {
        return cobalt_h264_decoder_destroy.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_h264_decoder_destroy(void *ctx)
     * }
     */
    public static MethodHandle cobalt_h264_decoder_destroy$handle() {
        return cobalt_h264_decoder_destroy.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_h264_decoder_destroy(void *ctx)
     * }
     */
    public static MemorySegment cobalt_h264_decoder_destroy$address() {
        return cobalt_h264_decoder_destroy.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_h264_decoder_destroy(void *ctx)
     * }
     */
    public static int cobalt_h264_decoder_destroy(MemorySegment ctx) {
        var mh$ = cobalt_h264_decoder_destroy.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_h264_decoder_destroy", ctx);
            }
            return (int)mh$.invokeExact(ctx);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_h264_last_native_status {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltOpenH264.C_INT,
            CobaltOpenH264.C_POINTER
        );

        public static final MemorySegment ADDR = CobaltOpenH264.findOrThrow("cobalt_h264_last_native_status");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int32_t cobalt_h264_last_native_status(void *ctx)
     * }
     */
    public static FunctionDescriptor cobalt_h264_last_native_status$descriptor() {
        return cobalt_h264_last_native_status.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int32_t cobalt_h264_last_native_status(void *ctx)
     * }
     */
    public static MethodHandle cobalt_h264_last_native_status$handle() {
        return cobalt_h264_last_native_status.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int32_t cobalt_h264_last_native_status(void *ctx)
     * }
     */
    public static MemorySegment cobalt_h264_last_native_status$address() {
        return cobalt_h264_last_native_status.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int32_t cobalt_h264_last_native_status(void *ctx)
     * }
     */
    public static int cobalt_h264_last_native_status(MemorySegment ctx) {
        var mh$ = cobalt_h264_last_native_status.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_h264_last_native_status", ctx);
            }
            return (int)mh$.invokeExact(ctx);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class cobalt_h264_strerror {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            CobaltOpenH264.C_POINTER,
            CobaltOpenH264.C_INT
        );

        public static final MemorySegment ADDR = CobaltOpenH264.findOrThrow("cobalt_h264_strerror");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * const char *cobalt_h264_strerror(int32_t err)
     * }
     */
    public static FunctionDescriptor cobalt_h264_strerror$descriptor() {
        return cobalt_h264_strerror.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * const char *cobalt_h264_strerror(int32_t err)
     * }
     */
    public static MethodHandle cobalt_h264_strerror$handle() {
        return cobalt_h264_strerror.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * const char *cobalt_h264_strerror(int32_t err)
     * }
     */
    public static MemorySegment cobalt_h264_strerror$address() {
        return cobalt_h264_strerror.ADDR;
    }

    /**
     * {@snippet lang=c :
     * const char *cobalt_h264_strerror(int32_t err)
     * }
     */
    public static MemorySegment cobalt_h264_strerror(int err) {
        var mh$ = cobalt_h264_strerror.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("cobalt_h264_strerror", err);
            }
            return (MemorySegment)mh$.invokeExact(err);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
    private static final int COBALT_H264_RC_OFF = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define COBALT_H264_RC_OFF -1
     * }
     */
    public static int COBALT_H264_RC_OFF() {
        return COBALT_H264_RC_OFF;
    }
    private static final int COBALT_H264_BAD_PARAM = (int)-1L;
    /**
     * {@snippet lang=c :
     * #define COBALT_H264_BAD_PARAM -1
     * }
     */
    public static int COBALT_H264_BAD_PARAM() {
        return COBALT_H264_BAD_PARAM;
    }
    private static final int COBALT_H264_NOMEM = (int)-2L;
    /**
     * {@snippet lang=c :
     * #define COBALT_H264_NOMEM -2
     * }
     */
    public static int COBALT_H264_NOMEM() {
        return COBALT_H264_NOMEM;
    }
    private static final int COBALT_H264_CREATE_FAIL = (int)-3L;
    /**
     * {@snippet lang=c :
     * #define COBALT_H264_CREATE_FAIL -3
     * }
     */
    public static int COBALT_H264_CREATE_FAIL() {
        return COBALT_H264_CREATE_FAIL;
    }
    private static final int COBALT_H264_NATIVE_ERROR = (int)-4L;
    /**
     * {@snippet lang=c :
     * #define COBALT_H264_NATIVE_ERROR -4
     * }
     */
    public static int COBALT_H264_NATIVE_ERROR() {
        return COBALT_H264_NATIVE_ERROR;
    }
}

