package com.github.auties00.cobalt.socket.datagram;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import javax.crypto.SecretKey;
import javax.crypto.spec.SecretKeySpec;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.assertArrayEquals;
import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;

/**
 * Covers {@link WhatsAppDatagramInputStream} framing at end of stream: a complete datagram followed by a clean close,
 * and the partial-trailing-datagram case the WhatsApp server produces by starting a final datagram it never finishes
 * and then closing the transport. Post-handshake fixtures are generated by round-tripping through the paired
 * {@link WhatsAppDatagramOutputStream} under a fixed all-zero key so the AES-GCM nonces line up between the two
 * counters.
 */
@DisplayName("WhatsAppDatagramInputStream end-of-stream framing")
class WhatsAppDatagramInputStreamTest {

    private static final SecretKey KEY = new SecretKeySpec(new byte[32], "AES");

    private static byte[] encrypt(String... datagrams) throws IOException {
        var sink = new ByteArrayOutputStream();
        var out = new WhatsAppDatagramOutputStream(sink);
        out.setWriteKey(KEY);
        for (var datagram : datagrams) {
            var plaintext = datagram.getBytes(StandardCharsets.UTF_8);
            out.beginDatagram(null, plaintext.length);
            out.write(plaintext, 0, plaintext.length);
            out.flush();
        }
        return sink.toByteArray();
    }

    private static byte[] preHandshakeDatagram(byte... plaintext) {
        var wire = new byte[3 + plaintext.length];
        wire[0] = (byte) ((plaintext.length >>> 16) & 0xFF);
        wire[1] = (byte) ((plaintext.length >>> 8) & 0xFF);
        wire[2] = (byte) (plaintext.length & 0xFF);
        System.arraycopy(plaintext, 0, wire, 3, plaintext.length);
        return wire;
    }

    private static byte[] readToEnd(WhatsAppDatagramInputStream in) throws IOException {
        var collected = new ByteArrayOutputStream();
        var chunk = new byte[64];
        int read;
        while ((read = in.read(chunk, 0, chunk.length)) >= 0) {
            collected.write(chunk, 0, read);
        }
        return collected.toByteArray();
    }

    @Test
    @DisplayName("complete datagram then clean EOF yields the plaintext then -1")
    void completeThenCleanEof() throws IOException {
        var in = new WhatsAppDatagramInputStream(new ByteArrayInputStream(encrypt("hello")));
        in.setReadKey(KEY);
        assertArrayEquals("hello".getBytes(StandardCharsets.UTF_8), readToEnd(in));
    }

    @Nested
    @DisplayName("partial trailing datagram is abandoned as a clean close")
    class PartialTrailingDatagram {

        @Test
        @DisplayName("truncated ciphertext body delivers only the complete datagram and never the partial one")
        void truncatedBody() throws IOException {
            var firstOnly = encrypt("first");
            var both = encrypt("first", "second");
            // Keep the whole first datagram plus a few bytes of the second so the second can never authenticate.
            var truncated = Arrays.copyOf(both, firstOnly.length + 5);

            var in = new WhatsAppDatagramInputStream(new ByteArrayInputStream(truncated));
            in.setReadKey(KEY);
            assertArrayEquals("first".getBytes(StandardCharsets.UTF_8), readToEnd(in));
        }

        @Test
        @DisplayName("truncated length prefix after a complete datagram ends cleanly")
        void truncatedLengthPrefix() throws IOException {
            // Pre-handshake passthrough: one whole datagram, then a 2-byte fragment of the next int24, then EOF.
            var wire = new ByteArrayOutputStream();
            wire.writeBytes(preHandshakeDatagram((byte) 'x', (byte) 'y'));
            wire.writeBytes(new byte[]{0x00, 0x00});

            var in = new WhatsAppDatagramInputStream(new ByteArrayInputStream(wire.toByteArray()));
            assertArrayEquals(new byte[]{'x', 'y'}, readToEnd(in));
        }

        @Test
        @DisplayName("never throws when the stream ends mid-datagram")
        void neverThrows() throws IOException {
            var both = encrypt("alpha", "omega");
            var truncated = Arrays.copyOf(both, both.length - 3);
            var in = new WhatsAppDatagramInputStream(new ByteArrayInputStream(truncated));
            in.setReadKey(KEY);
            assertDoesNotThrow(() -> readToEnd(in));
            assertEquals(-1, in.read());
        }
    }
}
