package com.github.auties00.cobalt.device.fanout;

import com.alibaba.fastjson2.JSONObject;
import com.github.auties00.cobalt.device.DeviceFixtures;
import com.github.auties00.cobalt.wire.core.jid.Jid;
import com.github.auties00.cobalt.wire.linked.props.ABProp;
import com.github.auties00.cobalt.props.TestABPropsService;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Exercises {@link DevicePhashCalculator} against live-bundle Known Answer Test vectors and
 * structural edge cases.
 *
 * <p>The {@code WaWebOracleKat} nested class is the byte-equality parity layer: it asserts
 * Cobalt's V1 and V2 output against captured wire output from the live WA Web bundle. The
 * remaining nested classes carry structural checks (prefix shape, determinism, bot-injection
 * gating) that exercise edge cases the captured corpus does not. KAT vectors are loaded from
 * {@code fixtures/device/phash-samples.expected.json} via {@link DeviceFixtures#loadOracle(String)};
 * the corpus is regenerated by re-running its sibling {@code generate.mjs} without touching test
 * code.
 */
@DisplayName("DevicePhashCalculator")
class DevicePhashCalculatorTest {
    private static final Jid PEER = Jid.of("393495089819@s.whatsapp.net");
    private static final Jid PEER_DEV_1 = Jid.of("393495089819:1@s.whatsapp.net");
    private static final Jid SELF = Jid.of("19254863482@s.whatsapp.net");
    private static final Jid SELF_DEV_15 = Jid.of("19254863482:15@s.whatsapp.net");

    @Nested
    @DisplayName("WA Web oracle parity (Known Answer Test)")
    class WaWebOracleKat {
        // tag is the sample id from the oracle JSON; phashV1/phashV2 are the exact return values
        // captured from the live JS bundle for the given device JID strings.
        private record Vector(String tag, List<String> devices, String phashV1, String phashV2) {
        }

        private static List<Vector> loadVectors() {
            var oracle = DeviceFixtures.loadOracle("phash-samples");
            var vectors = new ArrayList<Vector>(oracle.size());
            for (var entry : oracle.entrySet()) {
                var sample = (JSONObject) entry.getValue();
                var devices = sample.getJSONArray("devices");
                var deviceStrings = new ArrayList<String>(devices.size());
                for (var i = 0; i < devices.size(); i++) {
                    deviceStrings.add(devices.getString(i));
                }
                vectors.add(new Vector(
                        entry.getKey(),
                        List.copyOf(deviceStrings),
                        sample.getString("phashV1"),
                        sample.getString("phashV2")));
            }
            return vectors;
        }

        @Test
        @DisplayName("V1 byte-equality against live bundle")
        void phashV1MatchesLiveBundle() throws NoSuchAlgorithmException {
            var calculator = new DevicePhashCalculator(TestABPropsService.builder().build());
            for (var v : loadVectors()) {
                var jids = toJidSet(v.devices());
                var actual = calculator.calculate(jids, DevicePhashVersion.V1, false);
                assertEquals(v.phashV1(), actual, "phashV1 mismatch on vector '" + v.tag() + "'");
            }
        }

        @Test
        @DisplayName("V2 byte-equality against live bundle")
        void phashV2MatchesLiveBundle() throws NoSuchAlgorithmException {
            var calculator = new DevicePhashCalculator(TestABPropsService.builder().build());
            for (var v : loadVectors()) {
                var jids = toJidSet(v.devices());
                var actual = calculator.calculate(jids, DevicePhashVersion.V2, false);
                assertEquals(v.phashV2(), actual, "phashV2 mismatch on vector '" + v.tag() + "'");
            }
        }

        // LinkedHashSet preserves capture order so a debug failure can point at the offending JID.
        private static Set<Jid> toJidSet(List<String> devices) {
            var jids = new LinkedHashSet<Jid>();
            for (var s : devices) {
                jids.add(Jid.of(s));
            }
            return jids;
        }
    }

    @Nested
    @DisplayName("V1 phash")
    class V1 {
        @Test
        @DisplayName("starts with the V1 prefix")
        void prefix() throws NoSuchAlgorithmException {
            var calculator = new DevicePhashCalculator(TestABPropsService.builder().build());
            var phash = calculator.calculate(Set.of(PEER), DevicePhashVersion.V1, false);
            assertTrue(phash.startsWith(DevicePhashVersion.V1.prefix()),
                    "phash should start with V1 prefix '" + DevicePhashVersion.V1.prefix() + "' but was: " + phash);
        }

        @Test
        @DisplayName("emits a base64 hash that decodes to 6 bytes")
        void truncationLength() throws NoSuchAlgorithmException {
            var calculator = new DevicePhashCalculator(TestABPropsService.builder().build());
            var phash = calculator.calculate(Set.of(PEER, PEER_DEV_1), DevicePhashVersion.V1, false);
            var base64Part = phash.substring(DevicePhashVersion.V1.prefix().length());
            assertEquals(8, base64Part.length());
        }

        @Test
        @DisplayName("is order-independent for the same set of JIDs")
        void orderIndependent() throws NoSuchAlgorithmException {
            var calculator = new DevicePhashCalculator(TestABPropsService.builder().build());
            var a = calculator.calculate(Set.of(PEER, SELF), DevicePhashVersion.V1, false);
            var b = calculator.calculate(Set.of(SELF, PEER), DevicePhashVersion.V1, false);
            assertEquals(a, b);
        }
    }

    @Nested
    @DisplayName("V2 phash")
    class V2 {
        @Test
        @DisplayName("starts with the V2 prefix")
        void prefix() throws NoSuchAlgorithmException {
            var calculator = new DevicePhashCalculator(TestABPropsService.builder().build());
            var phash = calculator.calculate(Set.of(PEER_DEV_1), DevicePhashVersion.V2, false);
            assertTrue(phash.startsWith(DevicePhashVersion.V2.prefix()),
                    "phash should start with V2 prefix '" + DevicePhashVersion.V2.prefix() + "' but was: " + phash);
        }

        @Test
        @DisplayName("V1 and V2 produce different phashes for the same input")
        void differsFromV1() throws NoSuchAlgorithmException {
            var calculator = new DevicePhashCalculator(TestABPropsService.builder().build());
            var devices = Set.of(PEER_DEV_1, SELF_DEV_15);
            var v1 = calculator.calculate(devices, DevicePhashVersion.V1, false);
            var v2 = calculator.calculate(devices, DevicePhashVersion.V2, false);
            assertNotEquals(v1, v2);
        }

        @Test
        @DisplayName("differs when one device id changes")
        void differsByDeviceId() throws NoSuchAlgorithmException {
            var calculator = new DevicePhashCalculator(TestABPropsService.builder().build());
            var a = calculator.calculate(Set.of(PEER_DEV_1), DevicePhashVersion.V2, false);
            var b = calculator.calculate(Set.of(Jid.of("393495089819:2@s.whatsapp.net")), DevicePhashVersion.V2, false);
            assertNotEquals(a, b);
        }
    }

    @Nested
    @DisplayName("Meta AI bot gating")
    class MetaAiBotGating {
        @Test
        @DisplayName("does not include the open bot when allowIncludeOpenBot=false")
        void openBotNotIncludedWithoutFlag() throws NoSuchAlgorithmException {
            var props = TestABPropsService.builder()
                    .with(ABProp.WEB_AI_GROUP_OPEN_SUPPORT, true)
                    .with(ABProp.AI_GROUP_PARTICIPATION_ENABLED, true)
                    .build();
            var calculator = new DevicePhashCalculator(props);

            var without = calculator.calculate(Set.of(PEER_DEV_1), DevicePhashVersion.V2, false);
            var withOpenBot = calculator.calculate(Set.of(PEER_DEV_1), DevicePhashVersion.V2, true);

            assertNotEquals(without, withOpenBot,
                    "phash should change when the open bot is injected via the flag");
        }

        @Test
        @DisplayName("does not include the open bot when the gating AB props are off")
        void openBotNotIncludedWhenAbPropsDisabled() throws NoSuchAlgorithmException {
            var props = TestABPropsService.builder()
                    .with(ABProp.WEB_AI_GROUP_OPEN_SUPPORT, false)
                    .with(ABProp.AI_GROUP_PARTICIPATION_ENABLED, false)
                    .build();
            var calculator = new DevicePhashCalculator(props);

            var without = calculator.calculate(Set.of(PEER_DEV_1), DevicePhashVersion.V2, false);
            var withOpenBot = calculator.calculate(Set.of(PEER_DEV_1), DevicePhashVersion.V2, true);

            assertEquals(without, withOpenBot,
                    "phash should NOT change when the open bot flag is set but AB props deny inclusion");
        }

        @Test
        @DisplayName("includes the TEE bot when both the flag and the gating AB props are on")
        void teeBotIncluded() throws NoSuchAlgorithmException {
            var props = TestABPropsService.builder()
                    .with(ABProp.WEB_AI_GROUP_OPEN_SUPPORT, true)
                    .with(ABProp.AI_GROUP_PARTICIPATION_ADD_TEE_ENABLED, true)
                    .build();
            var calculator = new DevicePhashCalculator(props);

            var without = calculator.calculate(Set.of(PEER_DEV_1), DevicePhashVersion.V2, false, false);
            var withTeeBot = calculator.calculate(Set.of(PEER_DEV_1), DevicePhashVersion.V2, false, true);

            assertNotEquals(without, withTeeBot);
        }

        @Test
        @DisplayName("V1 ignores bot inclusion flags regardless of AB props")
        void v1IgnoresBots() throws NoSuchAlgorithmException {
            var props = TestABPropsService.builder()
                    .with(ABProp.WEB_AI_GROUP_OPEN_SUPPORT, true)
                    .with(ABProp.AI_GROUP_PARTICIPATION_ENABLED, true)
                    .with(ABProp.AI_GROUP_PARTICIPATION_ADD_TEE_ENABLED, true)
                    .build();
            var calculator = new DevicePhashCalculator(props);

            var without = calculator.calculate(Set.of(PEER), DevicePhashVersion.V1, false, false);
            var withBots = calculator.calculate(Set.of(PEER), DevicePhashVersion.V1, true, true);

            assertEquals(without, withBots, "V1 must not inject bots");
        }
    }

    @Nested
    @DisplayName("determinism")
    class Determinism {
        @Test
        @DisplayName("repeated calls with identical inputs produce identical outputs")
        void deterministic() throws NoSuchAlgorithmException {
            var calculator = new DevicePhashCalculator(TestABPropsService.builder().build());
            var phash1 = calculator.calculate(Set.of(PEER, PEER_DEV_1, SELF_DEV_15), DevicePhashVersion.V2, false);
            var phash2 = calculator.calculate(Set.of(PEER, PEER_DEV_1, SELF_DEV_15), DevicePhashVersion.V2, false);
            assertEquals(phash1, phash2);
        }

        @Test
        @DisplayName("adding a device changes the phash")
        void differentForDifferentSets() throws NoSuchAlgorithmException {
            var calculator = new DevicePhashCalculator(TestABPropsService.builder().build());
            var a = calculator.calculate(Set.of(PEER, PEER_DEV_1), DevicePhashVersion.V2, false);
            var b = calculator.calculate(Set.of(PEER, PEER_DEV_1, SELF_DEV_15), DevicePhashVersion.V2, false);
            assertNotEquals(a, b);
        }
    }
}
