package com.github.auties00.cobalt.wire.linked.business.catalog;

import it.auties.protobuf.annotation.ProtobufMessage;
import it.auties.protobuf.annotation.ProtobufProperty;
import it.auties.protobuf.model.ProtobufType;

import java.util.Collections;
import java.util.List;
import java.util.Optional;

/**
 * Represents a product collection within a WhatsApp Business catalog.
 *
 * <p>WhatsApp Business accounts can organize their products into named
 * collections, each grouping related {@link BusinessCatalogEntry} items
 * under a shared identifier and display name. Collections allow business
 * owners to categorize their offerings (for example, "Summer Sale" or
 * "Electronics") so that customers browsing the catalog see a structured
 * storefront rather than a flat product list.
 *
 * <p>Each collection is assigned a unique server-side identifier, carries a
 * human-readable name, and contains zero or more product entries. When a
 * customer opens a business profile in WhatsApp and navigates to its
 * catalog, collections are presented as browsable groups.
 */
@ProtobufMessage
public final class BusinessCatalog {
    /**
     * The unique server-assigned identifier for this collection.
     *
     * <p>This value is generated by the WhatsApp catalog backend and is used
     * to reference the collection in queries, updates, and deletions.
     */
    @ProtobufProperty(index = 1, type = ProtobufType.STRING)
    String id;

    /**
     * The display name of this collection as shown to customers browsing
     * the catalog.
     *
     * <p>Business owners set this name when creating or editing a collection.
     * It appears as a heading in the storefront UI.
     */
    @ProtobufProperty(index = 2, type = ProtobufType.STRING)
    String name;

    /**
     * The product entries contained in this collection.
     *
     * <p>Each entry represents a single product with its own metadata such as
     * name, price, availability, and image. A collection may contain zero or
     * more products.
     */
    @ProtobufProperty(index = 3, type = ProtobufType.MESSAGE)
    List<BusinessCatalogEntry> products;

    /**
     * Constructs a new {@code BusinessCatalog} with the specified
     * collection identifier, display name, and list of product entries.
     *
     * @param id       the unique server-assigned identifier for this
     *                 collection, or {@code null} if not yet assigned
     * @param name     the display name of this collection, or {@code null}
     *                 if not set
     * @param products the product entries in this collection, or
     *                 {@code null} for an empty collection
     */
    BusinessCatalog(String id, String name, List<BusinessCatalogEntry> products) {
        this.id = id;
        this.name = name;
        this.products = products;
    }

    /**
     * Returns the unique server-assigned identifier for this collection.
     *
     * @return an {@code Optional} containing the collection identifier,
     *         or an empty {@code Optional} if the identifier has not been
     *         assigned
     */
    public Optional<String> id() {
        return Optional.ofNullable(id);
    }

    /**
     * Returns the display name of this collection as shown to customers
     * browsing the catalog.
     *
     * @return an {@code Optional} containing the collection name, or an
     *         empty {@code Optional} if the name has not been set
     */
    public Optional<String> name() {
        return Optional.ofNullable(name);
    }

    /**
     * Returns the product entries contained in this collection.
     *
     * @return an unmodifiable list of {@link BusinessCatalogEntry}
     *         instances; never {@code null}, returns an empty list if no
     *         products are present
     */
    public List<BusinessCatalogEntry> products() {
        return products == null ? List.of() : Collections.unmodifiableList(products);
    }

    /**
     * Sets the unique server-assigned identifier for this collection.
     *
     * @param id the collection identifier to set, or {@code null} to clear
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Sets the display name of this collection.
     *
     * @param name the collection name to set, or {@code null} to clear
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Sets the product entries contained in this collection.
     *
     * @param products the product entries to set, or {@code null} to clear
     *                 the list
     */
    public void setProducts(List<BusinessCatalogEntry> products) {
        this.products = products;
    }
}
