package com.github.auties00.cobalt.wam.privatestats;

import com.github.auties00.cobalt.meta.annotation.WhatsAppWebModule;

import java.util.Objects;

/**
 * Carries the outcome of one successful {@code sign_credential} IQ round-trip.
 *
 * <p>Holds the secret token nonce that the client kept and the shared secret derived for authenticating the
 * matching upload. Produced by {@link WamPrivateStatsTokenIssuer#issue()} and consumed by
 * {@link WamPrivateStatsUploader#upload(byte[])}. It mirrors the {@code {token, sharedSecret}} object produced by
 * the {@code getSharedSecret} export and stored by {@code WAWebCRUDOperationsACSTokens.storeACSTokenForProject}.
 *
 * @implNote
 * This implementation defensively clones {@code token} and {@code sharedSecret} on entry and on exit so callers
 * cannot mutate the stored byte arrays, matching the immutability that the JS {@code Uint8Array} carriers enjoy
 * by being copied through structured clones across the WA Web storage boundary.
 *
 * @param token        the 32-byte secret nonce randomly generated by the client; never released to the server
 * @param sharedSecret the 64-byte {@code SHA-512(token || unblindedSignedToken)} used as the upload
 *                     authentication key
 */
@WhatsAppWebModule(moduleName = "WAWebIssuePrivateStatsToken")
public record WamPrivateStatsToken(byte[] token, byte[] sharedSecret) {
    /**
     * The length in bytes of the secret token nonce.
     *
     * @implNote
     * This implementation matches the {@code new Uint8Array(32)} buffer that the {@code getBlindedToken} export
     * fills with {@code crypto.getRandomValues}.
     */
    public static final int TOKEN_BYTES = 32;

    /**
     * The length in bytes of the derived shared secret, equal to a full SHA-512 digest.
     *
     * @implNote
     * This implementation matches the output length of the {@code WACryptoPrimitives.hash} call invoked by the
     * {@code getSharedSecret} export on the concatenated {@code token || unblindedSignedToken}.
     */
    public static final int SHARED_SECRET_BYTES = 64;

    /**
     * Validates the component lengths and clones both arrays so the record stores an isolated copy.
     *
     * <p>The exact byte lengths are part of the wire contract, so a wrong-sized component surfaces here as a
     * length error rather than as a silent authentication failure downstream.
     *
     * @throws NullPointerException     if either component is {@code null}
     * @throws IllegalArgumentException if {@code token} is not {@value #TOKEN_BYTES} bytes or {@code sharedSecret}
     *                                  is not {@value #SHARED_SECRET_BYTES} bytes
     */
    public WamPrivateStatsToken {
        Objects.requireNonNull(token, "token must not be null");
        Objects.requireNonNull(sharedSecret, "sharedSecret must not be null");
        if (token.length != TOKEN_BYTES) {
            throw new IllegalArgumentException(
                    "token must be " + TOKEN_BYTES + " bytes, was " + token.length);
        }
        if (sharedSecret.length != SHARED_SECRET_BYTES) {
            throw new IllegalArgumentException(
                    "sharedSecret must be " + SHARED_SECRET_BYTES + " bytes, was " + sharedSecret.length);
        }
        token = token.clone();
        sharedSecret = sharedSecret.clone();
    }

    /**
     * Returns a fresh clone of the secret token nonce.
     *
     * <p>The clone makes the record safe to hand to callers that may mutate the array, such as the
     * multipart-body assembler in {@link WamPrivateStatsUploader}.
     *
     * @return a freshly allocated copy of the {@value #TOKEN_BYTES} token bytes
     */
    @Override
    public byte[] token() {
        return token.clone();
    }

    /**
     * Returns a fresh clone of the derived shared secret.
     *
     * <p>The clone protects the stored bytes from being mutated by the caller through the
     * {@link javax.crypto.spec.SecretKeySpec} constructor that consumes the array.
     *
     * @return a freshly allocated copy of the {@value #SHARED_SECRET_BYTES} shared-secret bytes
     */
    @Override
    public byte[] sharedSecret() {
        return sharedSecret.clone();
    }
}
