package com.github.auties00.cobalt.wam.binary;

import java.util.Map;

/**
 * A pure size-calculation utility for the WhatsApp Metrics (WAM) custom
 * binary protocol.
 *
 * <p>Every method here is a deterministic function of its inputs and
 * does not depend on any sink (byte array, output stream, or otherwise).
 * Callers that pre-allocate a buffer use these methods to compute the
 * exact byte count required; streaming sinks may ignore them entirely.
 *
 * <p>The class exposes two layers:
 * <ul>
 *   <li><b>Low-level primitives</b> ({@link #tagSize}, {@link #intSize},
 *       {@link #stringSize}, {@link #floatSize}, {@link #nullSize})
 *       used by {@link WamGlobalEncoder} and the per-impl
 *       {@code sizeOf} bodies generated by the annotation processor.
 *   <li><b>Event-layer convenience</b> ({@link #eventMarkerSize},
 *       {@link #intFieldSize}, {@link #boolFieldSize},
 *       {@link #stringFieldSize}, {@link #floatFieldSize}) used by the
 *       per-impl {@code sizeOf} bodies for events.
 * </ul>
 *
 * <p>This class is thread-safe as all methods are static and operate
 * on provided parameters without shared mutable state.
 *
 * @see WamEventEncoder
 * @see WamGlobalEncoder
 * @see WamTags
 */
public final class WamEventSizes {
    /**
     * Private constructor to prevent instantiation of this utility class.
     *
     * @throws AssertionError always
     */
    private WamEventSizes() {
        throw new AssertionError();
    }

    /**
     * Returns the number of bytes required to encode a tag with the given
     * field identifier.
     *
     * <p>Field identifiers below {@code 256} use a one-byte encoding (2
     * bytes total: flags + uint8 id). Identifiers {@code 256} and above
     * set the {@link WamTags#WIDE_ID} flag and use a two-byte encoding
     * (3 bytes total: flags + uint16 id).
     *
     * @param fieldId the numeric field or event identifier
     * @return {@code 2} if {@code fieldId < 256}, otherwise {@code 3}
     */
    public static int tagSize(int fieldId) {
        return fieldId < 256 ? 2 : 3;
    }

    /**
     * Returns the number of bytes required to encode a null value with
     * the given field identifier.
     *
     * <p>A null value is encoded as a tag-only entry with value-type
     * {@code 0x00} and no payload bytes.
     *
     * @param fieldId the numeric field identifier
     * @return the encoded size in bytes
     */
    public static int nullSize(int fieldId) {
        return tagSize(fieldId);
    }

    /**
     * Returns the number of bytes required to encode an integer value
     * with the given field identifier.
     *
     * <p>The encoding uses the minimum number of bytes for the value:
     * <ul>
     *   <li>Values {@code 0} and {@code 1} are encoded in the tag alone
     *       (zero payload bytes)
     *   <li>Values in {@code [-128, 127]} use 1 payload byte (int8)
     *   <li>Values in {@code [-32768, 32767]} use 2 payload bytes (int16)
     *   <li>Values in {@code [-2^31, 2^31-1]} use 4 payload bytes (int32)
     *   <li>All other values use 8 payload bytes (int64, encoded as
     *       float64 for range)
     * </ul>
     *
     * @param fieldId the numeric field identifier
     * @param value   the integer value to encode
     * @return the number of bytes required
     */
    public static int intSize(int fieldId, long value) {
        return tagSize(fieldId) + intPayloadSize(value);
    }

    /**
     * Returns the number of payload bytes for an integer value (excluding
     * the tag).
     *
     * @param value the integer value
     * @return the payload byte count (0, 1, 2, 4, or 8)
     */
    private static int intPayloadSize(long value) {
        if (value == 0 || value == 1) {
            return 0;
        } else if (value >= -128 && value < 128) {
            return 1;
        } else if (value >= -32768 && value < 32768) {
            return 2;
        } else if (value >= -2147483648L && value < 2147483648L) {
            return 4;
        } else {
            return 8;
        }
    }

    /**
     * Returns the number of bytes required to encode a float (double)
     * value with the given field identifier.
     *
     * <p>Floats are always encoded as 8-byte IEEE 754 double-precision
     * values in little-endian byte order.
     *
     * @param fieldId the numeric field identifier
     * @return the number of bytes required (tag + 8)
     */
    public static int floatSize(int fieldId) {
        return tagSize(fieldId) + 8;
    }

    /**
     * Returns the number of bytes required to encode a string value with
     * the given field identifier.
     *
     * <p>The encoding consists of a tag, a variable-width length prefix
     * (uint8, uint16, or uint32 depending on the UTF-8 byte count), and
     * the raw UTF-8 bytes.
     *
     * @param fieldId the numeric field identifier
     * @param value   the string to encode, must not be {@code null}
     * @return the number of bytes required
     */
    public static int stringSize(int fieldId, String value) {
        var utf8len = utf8Length(value);
        return tagSize(fieldId) + stringLengthPrefixSize(utf8len) + utf8len;
    }

    /**
     * Returns the number of bytes required for the string length prefix.
     *
     * @param utf8len the UTF-8 byte count of the string
     * @return {@code 1} if less than 256, {@code 2} if less than 65536,
     *         otherwise {@code 4}
     */
    private static int stringLengthPrefixSize(int utf8len) {
        if (utf8len < 256) {
            return 1;
        } else if (utf8len < 65536) {
            return 2;
        } else {
            return 4;
        }
    }

    /**
     * Calculates the number of bytes required to represent a string in
     * UTF-8 encoding.
     *
     * <p>This method iterates character-by-character, correctly handling
     * surrogate pairs (4 bytes), BMP characters above U+007F, and ASCII.
     *
     * @param input the string to measure
     * @return the UTF-8 byte count
     */
    public static int utf8Length(String input) {
        var length = 0;
        var len = input.length();
        for (var i = 0; i < len; i++) {
            var ch = input.charAt(i);
            if (ch <= 0x7F) {
                length++;
            } else if (ch <= 0x7FF) {
                length += 2;
            } else if (Character.isHighSurrogate(ch)) {
                length += 4;
                i++;
            } else {
                length += 3;
            }
        }
        return length;
    }

    /**
     * Returns the number of bytes required to encode an event marker
     * with the given event identifier and sampling weight.
     *
     * <p>The weight is negated on the wire so the server can apply
     * statistical correction.
     *
     * @param eventId the numeric event identifier
     * @param weight  the sampling weight (written as {@code -weight})
     * @return the encoded size in bytes
     */
    public static int eventMarkerSize(int eventId, int weight) {
        return intSize(eventId, -weight);
    }

    /**
     * Returns the number of bytes required to encode an integer field.
     *
     * @param fieldId the numeric field identifier
     * @param value   the integer value
     * @return the encoded size in bytes
     */
    public static int intFieldSize(int fieldId, long value) {
        return intSize(fieldId, value);
    }

    /**
     * Returns the number of bytes required to encode a boolean field.
     *
     * <p>Booleans are encoded as integer values {@code 0} or {@code 1},
     * both of which fit in the tag alone with zero payload bytes. The
     * size is computed for the worst case (value {@code 1}).
     *
     * @param fieldId the numeric field identifier
     * @return the encoded size in bytes
     */
    public static int boolFieldSize(int fieldId) {
        return intSize(fieldId, 1);
    }

    /**
     * Returns the number of bytes required to encode a string field.
     *
     * @param fieldId the numeric field identifier
     * @param value   the string value, must not be {@code null}
     * @return the encoded size in bytes
     */
    public static int stringFieldSize(int fieldId, String value) {
        return stringSize(fieldId, value);
    }

    /**
     * Returns the number of bytes required to encode a float (double)
     * field.
     *
     * @param fieldId the numeric field identifier
     * @return the encoded size in bytes (tag + 8)
     */
    public static int floatFieldSize(int fieldId) {
        return floatSize(fieldId);
    }

    /**
     * Returns the number of bytes required to encode a complete event,
     * marker and fields, from a map of decoded wire values.
     *
     * <p>Each field's size is computed from its {@link WamWireValue}
     * variant. This mirrors {@link WamEventEncoder#writeEvent} so that a
     * caller pre-allocating a buffer reserves exactly the bytes the encoder
     * will write.
     *
     * @param eventId the numeric event identifier
     * @param weight  the resolved sampling weight
     * @param fields  the fields to size; must not be {@code null}
     * @return the encoded size in bytes
     */
    public static int sizeOf(int eventId, int weight, Map<Integer, WamWireValue> fields) {
        var size = eventMarkerSize(eventId, weight);
        for (var entry : fields.entrySet()) {
            int fieldId = entry.getKey();
            size += switch (entry.getValue()) {
                case WamWireValue.WamInt value -> intFieldSize(fieldId, value.value());
                case WamWireValue.WamFloat value -> floatFieldSize(fieldId);
                case WamWireValue.WamString value -> stringFieldSize(fieldId, value.value());
            };
        }
        return size;
    }
}
