package com.github.auties00.cobalt.emoji;

import com.github.auties00.cobalt.meta.annotation.WhatsAppWebModule;

/**
 * The categories a {@link WhatsAppEmoji} can belong to, in the canonical order
 * WhatsApp presents them.
 *
 * <p>Generated by {@code tools/web/emoji-codegen}; do not edit manually.
 */
@WhatsAppWebModule(moduleName = "WAWebEmojiConst")
public enum EmojiCategory {
    /**
     * The Smileys People category.
     */
    SMILEYS_PEOPLE,

    /**
     * The Animals Nature category.
     */
    ANIMALS_NATURE,

    /**
     * The Food Drink category.
     */
    FOOD_DRINK,

    /**
     * The Activity category.
     */
    ACTIVITY,

    /**
     * The Travel Places category.
     */
    TRAVEL_PLACES,

    /**
     * The Objects category.
     */
    OBJECTS,

    /**
     * The Symbols category.
     */
    SYMBOLS,

    /**
     * The Flags category.
     */
    FLAGS;
}
