package com.github.auties00.cobalt.wire.linked.message.payment;

import com.github.auties00.cobalt.wire.linked.message.Message;

import java.time.Instant;

import com.github.auties00.cobalt.wire.core.mixin.InstantSecondsMixin;
import it.auties.protobuf.annotation.*;
import it.auties.protobuf.model.*;
import java.util.Optional;

/**
 * Represents an invitation sent to a contact to start using a
 * WhatsApp-integrated payment service.
 *
 * <p>Payment invite messages are generated by the WhatsApp servers or
 * by sender clients to prompt a recipient to enrol in a specific
 * payment service (such as UPI, Facebook Pay or Novi). The invite
 * carries the targeted service type, an expiry timestamp after which
 * the invite is no longer valid, and a flag indicating whether the
 * recipient is eligible for a signup incentive.
 */
@ProtobufMessage(name = "Message.PaymentInviteMessage")
public final class PaymentInviteMessage implements Message {
    /**
     * The type of payment service the recipient is being invited to use.
     */
    @ProtobufProperty(index = 1, type = ProtobufType.ENUM)
    ServiceType serviceType;

    /**
     * The instant at which this invite expires.
     *
     * <p>After this point the invite is no longer actionable and the
     * UI should hide any call-to-action prompting the user to join
     * the payment service.
     */
    @ProtobufProperty(index = 2, type = ProtobufType.INT64, mixins = InstantSecondsMixin.class)
    Instant expiryTimestamp;

    /**
     * Whether the recipient is eligible for a signup incentive.
     *
     * <p>When {@code true}, the recipient qualifies for a promotional
     * reward (such as cashback) for enrolling in the service through
     * this invite.
     */
    @ProtobufProperty(index = 3, type = ProtobufType.BOOL)
    Boolean incentiveEligible;


    /**
     * Constructs a new payment invite message.
     *
     * @param serviceType       the targeted payment service type,
     *                          may be {@code null}
     * @param expiryTimestamp   the instant at which the invite
     *                          expires, may be {@code null}
     * @param incentiveEligible whether the recipient is eligible for
     *                          a signup incentive, may be {@code null}
     */
    PaymentInviteMessage(ServiceType serviceType, Instant expiryTimestamp, Boolean incentiveEligible) {
        this.serviceType = serviceType;
        this.expiryTimestamp = expiryTimestamp;
        this.incentiveEligible = incentiveEligible;
    }

    /**
     * Returns the type of payment service being advertised.
     *
     * @return an {@link Optional} containing the {@link ServiceType},
     *         or {@link Optional#empty()} if not set
     */
    public Optional<ServiceType> serviceType() {
        return Optional.ofNullable(serviceType);
    }

    /**
     * Returns the expiry instant of this invite.
     *
     * @return an {@link Optional} containing the expiry
     *         {@link Instant}, or {@link Optional#empty()} if not set
     */
    public Optional<Instant> expiryTimestamp() {
        return Optional.ofNullable(expiryTimestamp);
    }

    /**
     * Returns whether the recipient is eligible for a signup incentive.
     *
     * @return {@code true} if the recipient is eligible for an
     *         incentive, {@code false} otherwise or if the flag is
     *         not set
     */
    public boolean incentiveEligible() {
        return incentiveEligible != null && incentiveEligible;
    }

    /**
     * Sets the type of payment service being advertised.
     *
     * @param serviceType the service type, may be {@code null}
     */
    public void setServiceType(ServiceType serviceType) {
        this.serviceType = serviceType;
    }

    /**
     * Sets the expiry instant of this invite.
     *
     * @param expiryTimestamp the expiry instant, may be {@code null}
     */
    public void setExpiryTimestamp(Instant expiryTimestamp) {
        this.expiryTimestamp = expiryTimestamp;
    }

    /**
     * Sets whether the recipient is eligible for a signup incentive.
     *
     * @param incentiveEligible the incentive eligibility flag, may be
     *                          {@code null}
     */
    public void setIncentiveEligible(Boolean incentiveEligible) {
        this.incentiveEligible = incentiveEligible;
    }

    /**
     * Enumerates the payment services that can be advertised through
     * a {@link PaymentInviteMessage}.
     *
     * <p>Each constant corresponds to a distinct WhatsApp-integrated
     * payment provider. Clients use this value to render the correct
     * branding and enrolment flow for the invite.
     */
    @ProtobufEnum(name = "Message.PaymentInviteMessage.ServiceType")
    public static enum ServiceType {
        /**
         * The service type is unknown or unspecified.
         */
        UNKNOWN(0),
        /**
         * Facebook Pay, the Meta-wide payment service.
         */
        FBPAY(1),
        /**
         * Novi, Meta's legacy digital wallet.
         */
        NOVI(2),
        /**
         * UPI (Unified Payments Interface), the Indian instant
         * payment system.
         */
        UPI(3);

        /**
         * Constructs a new service type with the given protobuf index.
         *
         * @param index the protobuf wire index for this service
         */
        ServiceType(@ProtobufEnumIndex int index) {
            this.index = index;
        }

        /**
         * The protobuf wire index of this service type.
         */
        final int index;

        /**
         * Returns the protobuf wire index of this service type.
         *
         * @return the numeric index used when serialising this
         *         constant over the wire
         */
        public int index() {
            return this.index;
        }
    }
}
