package com.github.auties00.cobalt.wire.wam.type;

import com.github.auties00.cobalt.meta.annotation.WhatsAppWebModule;

import com.github.auties00.cobalt.wam.annotation.WamEnum;
import com.github.auties00.cobalt.wam.annotation.WamEnumConstant;

@WhatsAppWebModule(moduleName = "WAWebWamEnumBlockEntryPoint")
@WamEnum
public enum BlockEntryPoint {
    @WamEnumConstant(0) OTHER,
    @WamEnumConstant(1) CHAT,
    @WamEnumConstant(2) PROFILE,
    @WamEnumConstant(3) BLOCK_LIST,
    @WamEnumConstant(4) TRIGGERED_BLOCK,
    @WamEnumConstant(5) ACCOUNT_INFO,
    @WamEnumConstant(6) CALL_LOG,
    @WamEnumConstant(7) OVERFLOW_MENU,
    @WamEnumConstant(8) GROUP_INFO,
    @WamEnumConstant(9) BLOCK_DIALOG,
    @WamEnumConstant(10) MESSAGE_MENU,
    @WamEnumConstant(11) MEDIA_VIEWER,
    @WamEnumConstant(12) OVERFLOW_MENU_BLOCK,
    @WamEnumConstant(13) ONE_TO_ONE_OLD_SPAM_BANNER_BLOCK,
    @WamEnumConstant(14) ONE_TO_ONE_SPAM_BANNER_BLOCK,
    @WamEnumConstant(15) BIZ_SPAM_BANNER_BLOCK,
    @WamEnumConstant(16) BLOCK_HEADER_CHAT,
    @WamEnumConstant(17) OVERFLOW_MENU_REPORT,
    @WamEnumConstant(18) ACCOUNT_INFO_REPORT,
    @WamEnumConstant(19) BIZ_OLD_SPAM_BANNER_BLOCK,
    @WamEnumConstant(20) CHAT_LIST_BLOCK,
    @WamEnumConstant(21) CHAT_LIST_NOINSUB_BLOCK,
    @WamEnumConstant(22) CHAT_LIST_CONTEXT_MENU_BLOCK,
    @WamEnumConstant(23) NOTIFICATION_BLOCK,
    @WamEnumConstant(24) ONE_TO_ONE_SPAM_BANNER_REPORT,
    @WamEnumConstant(25) BIZ_EXTENSION_MENU,
    @WamEnumConstant(26) VIEW_ONCE_VIEWER,
    @WamEnumConstant(27) STATUS_OVERFLOW_MENU_REPORT,
    @WamEnumConstant(28) ALBUM_MEDIA_MENU_REPORT,
    @WamEnumConstant(29) STATUS_POST_REPORT,
    @WamEnumConstant(30) MISSED_CALL_NOTIFICATION_BLOCK,
    @WamEnumConstant(31) CHAT_FMX_CARD_BLOCK,
    @WamEnumConstant(32) CHAT_FMX_CARD_BLOCK_SUSPICIOUS,
    @WamEnumConstant(33) CHAT_FMX_CARD_SAFETY_TOOLS_BLOCK,
    @WamEnumConstant(34) CHAT_FMX_CARD_SAFETY_TOOLS_BLOCK_SUSPICIOUS,
    @WamEnumConstant(35) CHAT_FMX_CARD_SAFETY_TOOLS_REPORT,
    @WamEnumConstant(36) CHAT_FMX_CARD_SAFETY_TOOLS_REPORT_SUSPICIOUS,
    @WamEnumConstant(37) ACCOUNT_INFO_BLOCK,
    @WamEnumConstant(38) CALL_LOG_BLOCK,
    @WamEnumConstant(39) BIZ_BLOCK_HEADER_CHAT,
    @WamEnumConstant(40) BIZ_OVERFLOW_MENU_BLOCK,
    @WamEnumConstant(41) PSA_BANNER_BLOCK,
    @WamEnumConstant(42) COMMENT_ACTIONS_BOTTOM_SHEET,
    @WamEnumConstant(43) CALL_SPAM_DIALOG_REPORT,
    @WamEnumConstant(44) CALL_SPAM_DIALOG_BLOCK,
    @WamEnumConstant(45) BIZ_ACCOUNT_INFO_BLOCK,
    @WamEnumConstant(46) BIZ_BLOCK_LIST,
    @WamEnumConstant(47) BIZ_CALL_LOG_BLOCK,
    @WamEnumConstant(48) ONGOING_CALL_LINK_BLOCK,
    @WamEnumConstant(49) ONE_TO_ONE_BLOCKED_CHAT_COMPOSER,
    @WamEnumConstant(50) CHAT_MORE_OPTIONS,
    @WamEnumConstant(51) CHAT_LONG_PRESS_OPTIONS,
    @WamEnumConstant(52) IAB_MENU_REPORT,
    @WamEnumConstant(53) DEPENDENT_CONVERSATION_BLOCKING_VIEW,
    @WamEnumConstant(54) PAYMENT_TRANSACTION_REPORT,
    @WamEnumConstant(55) CALL_DETAIL_SAFETY_TOOLS_BLOCK,
    @WamEnumConstant(56) CALL_DETAIL_SAFETY_TOOLS_REPORT,
    @WamEnumConstant(57) CALL_DETAIL_OVERFLOW_REPORT,
    @WamEnumConstant(58) CHAT_FMX_CARD_BLOCK_SERVER_FLAGGED_SUSPICIOUS,
    @WamEnumConstant(59) ONE_TO_ONE_SPAM_BANNER_BLOCK_SERVER_FLAGGED_SUSPICIOUS,
    @WamEnumConstant(60) TRUST_QUESTION_BOTTOMSHEET_BLOCK_SERVER_FLAGGED_SUSPICIOUS
}
