package com.github.auties00.cobalt.wire.wam.type;

import com.github.auties00.cobalt.meta.annotation.WhatsAppWebModule;

import com.github.auties00.cobalt.wam.annotation.WamEnum;
import com.github.auties00.cobalt.wam.annotation.WamEnumConstant;

@WhatsAppWebModule(moduleName = "WAWebWamEnumGroupMemberAddingActionType")
@WamEnum
public enum GroupMemberAddingActionType {
    @WamEnumConstant(0) CONTACTS_PICKER_OPENED,
    @WamEnumConstant(1) CONTACTS_LOADED,
    @WamEnumConstant(2) CONTACT_SUGGESTED_CLICKED,
    @WamEnumConstant(3) CONTACT_NOT_SUGGESTED_CLICKED,
    @WamEnumConstant(4) CONTACT_SUGGESTED_UNCLICKED,
    @WamEnumConstant(5) CONTACT_NOT_SUGGESTED_UNCLICKED,
    @WamEnumConstant(6) GROUP_MEMBER_ADD_BUTTON_CLICKED,
    @WamEnumConstant(7) GROUP_CREATION_SUBMIT_BUTTON_CLICKED,
    @WamEnumConstant(8) GROUP_ALREADY_EXISTS_DIALOG_SHOWN,
    @WamEnumConstant(9) GROUP_ALREADY_EXISTS_VIEW_GROUP_CLICKED,
    @WamEnumConstant(10) GROUP_ALREADY_EXISTS_CREATE_NEW_CLICKED,
    @WamEnumConstant(11) GROUP_ALREADY_EXISTS_CANCELED_CLICKED,
    @WamEnumConstant(12) GROUP_NAME_ENTERED,
    @WamEnumConstant(13) DISAPPEARING_MESSAGES_CLICKED,
    @WamEnumConstant(14) GROUP_PERMISSIONS_CLICKED,
    @WamEnumConstant(15) SET_PROFILE_PHOTO_CLICKED,
    @WamEnumConstant(16) NEW_CHAT_CLICKED,
    @WamEnumConstant(17) OVERFLOW_MENU_CLICKED,
    @WamEnumConstant(18) NEW_GROUP_CLICKED,
    @WamEnumConstant(19) GROUP_CREATION_SUCCEEDED,
    @WamEnumConstant(20) GROUP_CREATION_FAILED,
    @WamEnumConstant(21) CONTACT_ADDED_IN_SEARCH_BAR,
    @WamEnumConstant(22) CONTACT_REMOVED_FROM_SEARCH_BAR,
    @WamEnumConstant(23) MESSAGE_BUTTON_CLICKED,
    @WamEnumConstant(24) MEMBER_SELECTOR_BACK_BUTTON_CLICKED,
    @WamEnumConstant(25) GROUP_CREATE_FINAL_STEP_BACK_BUTTON_CLICKED,
    @WamEnumConstant(26) MEMBER_SELECTOR_BACK_DISCARD_CONFIRM_DIALOG_SHOWN,
    @WamEnumConstant(27) MEMBER_SELECTOR_BACK_DISCARD_CONFIRM_DIALOG_CANCEL_CLICKED,
    @WamEnumConstant(28) MEMBER_SELECTOR_BACK_DISCARD_CONFIRM_DIALOG_DISCARD_CLICKED,
    @WamEnumConstant(29) GROUP_HISTORY_SELECTABLE_MESSAGES_LOADED,
    @WamEnumConstant(30) GROUP_HISTORY_FOOTER_DISPLAYED,
    @WamEnumConstant(31) GROUP_HISTORY_TOGGLE_ON,
    @WamEnumConstant(32) GROUP_HISTORY_TOGGLE_OFF,
    @WamEnumConstant(33) GROUP_HISTORY_COUNT_CHANGE_ENTRY_POINT_CLICKED,
    @WamEnumConstant(34) GROUP_HISTORY_COUNT_CHANGED,
    @WamEnumConstant(35) GROUP_HISTORY_SPEED_BUMP_DIALOG_DISPLAYED,
    @WamEnumConstant(36) GROUP_HISTORY_SPEED_BUMP_DIALOG_CONTINUED,
    @WamEnumConstant(37) GROUP_HISTORY_SPEED_BUMP_DIALOG_CANCELED,
    @WamEnumConstant(38) GROUP_HISTORY_BUNDLE_MESSAGE_SENT,
    @WamEnumConstant(39) GROUP_HISTORY_NOTICE_MESSAGE_SENT,
    @WamEnumConstant(40) META_AI_NULL_STATE_GROUPS_MENU_BUTTON_CLICKED,
    @WamEnumConstant(41) META_AI_NULL_STATE_GROUPS_CAPABILITY_CLICKED,
    @WamEnumConstant(42) GROUP_AI_DEEPLINK_CLICKED,
    @WamEnumConstant(43) GROUP_MENTION_PICKER_ADD_AI_CLICKED,
    @WamEnumConstant(44) ACTIVE_CALL_TOAST_SHOWN,
    @WamEnumConstant(45) BOT_SELECTION_BOTTOM_SHEET_SHOWN,
    @WamEnumConstant(46) TEE_BOT_IN_SELECTION_BOTTOM_SHEET_CLICKED,
    @WamEnumConstant(47) OPEN_BOT_IN_SELECTION_BOTTOM_SHEET_CLICKED,
    @WamEnumConstant(48) DONE_BUTTON_IN_BOT_SELECTION_BOTTOM_SHEET_CLICKED,
    @WamEnumConstant(49) CANCEL_BUTTON_IN_BOT_SELECTION_BOTTOM_SHEET_CLICKED,
    @WamEnumConstant(50) CHAT_MENTION_PICKER_CREATE_AI_GROUP_CHAT_CLICKED,
    @WamEnumConstant(51) GROUP_MENTION_PICKER_ADD_AI_RENDERED,
    @WamEnumConstant(52) CHAT_MENTION_PICKER_CREATE_AI_GROUP_CHAT_RENDERED
}
