package com.github.auties00.cobalt.wire.wam.type;

import com.github.auties00.cobalt.meta.annotation.WhatsAppWebModule;

import com.github.auties00.cobalt.wam.annotation.WamEnum;
import com.github.auties00.cobalt.wam.annotation.WamEnumConstant;

@WhatsAppWebModule(moduleName = "WAWebWamEnumNotificationTypeEnum")
@WamEnum
public enum NotificationTypeEnum {
    @WamEnumConstant(1) TEXT_MESSAGE,
    @WamEnumConstant(2) VOICE_MESSAGE,
    @WamEnumConstant(3) FILE_MESSAGE,
    @WamEnumConstant(4) PHOTO_MESSAGE,
    @WamEnumConstant(5) VIDEO_MESSAGE,
    @WamEnumConstant(6) MISSED_VOICE_CALL,
    @WamEnumConstant(7) MISSED_VIDEO_CALL,
    @WamEnumConstant(8) STICKER_MESSAGE,
    @WamEnumConstant(9) REACTION_MESSAGE,
    @WamEnumConstant(10) GROUP_INVITE_MESSAGE,
    @WamEnumConstant(11) REQUEST_MEDIA_REUPLOAD,
    @WamEnumConstant(12) WEB_CLIENT_LOGIN,
    @WamEnumConstant(13) BACKUP,
    @WamEnumConstant(14) KEEP_IN_CHAT,
    @WamEnumConstant(15) PAYMENT,
    @WamEnumConstant(16) POLL_MESSAGE,
    @WamEnumConstant(17) LOCATION_MESSAGE,
    @WamEnumConstant(18) WEB_PAGE_MESSAGE,
    @WamEnumConstant(19) FAILED_UPLOAD,
    @WamEnumConstant(20) GDPR_REPORT,
    @WamEnumConstant(21) INCOMING_VOICE_CALL,
    @WamEnumConstant(22) INCOMING_VIDEO_CALL,
    @WamEnumConstant(23) VIDEO_CALL_UPGRADE,
    @WamEnumConstant(24) WAFFLE,
    @WamEnumConstant(25) XPLAT_MIGRATION,
    @WamEnumConstant(26) OTHER,
    @WamEnumConstant(27) INVITE_JOINED,
    @WamEnumConstant(28) SCHEDULED_CALL_LOCAL_REMINDER,
    @WamEnumConstant(29) PTV_MESSAGE,
    @WamEnumConstant(30) STATUS_MENTION,
    @WamEnumConstant(31) STATUS_REACTION,
    @WamEnumConstant(32) STICKER_PACK_MESSAGE,
    @WamEnumConstant(33) POLL_RESULT_SNAPSHOT_MESSAGE,
    @WamEnumConstant(34) CALL_LINK_CREATOR,
    @WamEnumConstant(35) STATUS_PROMPT_RESPONSE,
    @WamEnumConstant(36) LINK_CREATOR_CALL_STARTED,
    @WamEnumConstant(37) LINK_CREATOR_CALL_CONNECTED,
    @WamEnumConstant(38) LINK_CREATOR_CALL_MISSED,
    @WamEnumConstant(39) STATUS_POST_RESHARE,
    @WamEnumConstant(40) STATUS_QUESTION_ANSWER_POST_RESHARE,
    @WamEnumConstant(41) EVENT_MESSAGE,
    @WamEnumConstant(42) CONTACT_MESSAGE,
    @WamEnumConstant(43) GIF_MESSAGE,
    @WamEnumConstant(44) ALBUM_MESSAGE,
    @WamEnumConstant(45) PAA_ACTIVITY_ALERT,
    @WamEnumConstant(46) NOTIFICATION_SUMMARY,
    @WamEnumConstant(47) OTHER_INORGANIC,
    @WamEnumConstant(48) CHANNEL_NOTIFICATION_SUMMARY,
    @WamEnumConstant(49) NEWSLETTER_QUESTION_RESPONSE_REPLIED,
    @WamEnumConstant(51) NEWSLETTER_CHANNEL_INFO_UPDATE,
    @WamEnumConstant(52) WAITING_ROOM_JOINED,
    @WamEnumConstant(53) WAITING_ROOM_MULTIPLE_JOINED,
    @WamEnumConstant(54) NEWSLETTER_MILESTONE_FOLLOWERS,
    @WamEnumConstant(55) NEWSLETTER_MILESTONE_UPDATE_REACTIONS,
    @WamEnumConstant(56) NEWSLETTER_MILESTONE_UPDATE_POLL_VOTES,
    @WamEnumConstant(57) NEWSLETTER_MILESTONE_UPDATE_QUIZ_RESPONSES,
    @WamEnumConstant(58) NEWSLETTER_MILESTONE_UPDATE_QUESTION_RESPONSES,
    @WamEnumConstant(59) CALL_TRANSFER,
    @WamEnumConstant(60) AI_MESSAGE,
    @WamEnumConstant(61) PIN_MESSAGE,
    @WamEnumConstant(62) ADMIN_GROUP_JOIN_REQUEST,
    @WamEnumConstant(63) CHANNEL_STATUS_QUESTION_ANSWER_POST_RESHARE
}
