package com.github.auties00.cobalt.wire.wam.type;

import com.github.auties00.cobalt.meta.annotation.WhatsAppWebModule;

import com.github.auties00.cobalt.wam.annotation.WamEnum;
import com.github.auties00.cobalt.wam.annotation.WamEnumConstant;

@WhatsAppWebModule(moduleName = "WAWebWamEnumOrderDetailsCreationAction")
@WamEnum
public enum OrderDetailsCreationAction {
    @WamEnumConstant(1) CLICK_VIEW_RECEIVED_CART,
    @WamEnumConstant(2) SEND_DECLINE_CART,
    @WamEnumConstant(3) USER_DELETED_CART,
    @WamEnumConstant(4) CLICK_CREATE_ORDER_DETAILS_FROM_CART,
    @WamEnumConstant(5) CLICK_ORDER_FROM_ICON_MENU,
    @WamEnumConstant(6) CLICK_CREATE_ORDER_DETAILS_FROM_FAB,
    @WamEnumConstant(7) SEND_ORDER_DETAILS,
    @WamEnumConstant(8) VIEW_ORDER_DETAILS_HUB,
    @WamEnumConstant(9) VIEW_ORDER_DETAILS,
    @WamEnumConstant(10) CLICK_SORT_ORDERS,
    @WamEnumConstant(11) CLICK_UPDATE_ORDER_STATUS,
    @WamEnumConstant(12) SEND_ORDER_STATUS,
    @WamEnumConstant(13) CLICK_PAYMENT_DETAILS,
    @WamEnumConstant(14) SEND_MARK_AS_PAID,
    @WamEnumConstant(15) SEND_MARK_AS_UNPAID,
    @WamEnumConstant(16) CLICK_HELP,
    @WamEnumConstant(17) CLICK_MESSAGE_CUSTOMER,
    @WamEnumConstant(18) CLICK_ADD_PAYMENT_OPTION,
    @WamEnumConstant(19) CLICK_SAVE_ADD_PAYMENT_OPTION,
    @WamEnumConstant(20) CLICK_SAVE_EDIT_PAYMENT_OPTION,
    @WamEnumConstant(21) CLICK_EDIT_PAYMENT_OPTION,
    @WamEnumConstant(22) CLICK_DELETE_PAYMENT_OPTION,
    @WamEnumConstant(23) CLICK_GET_PAID_ON_WA,
    @WamEnumConstant(24) CLICK_SEE_ALL_OTHER_ORDERS,
    @WamEnumConstant(25) ADD_PAYMENT_OPTION_TO_OD,
    @WamEnumConstant(26) EDIT_PAYMENT_OPTION_IN_OD,
    @WamEnumConstant(27) CLICK_ADD_CUSTOM_ITEM_TO_ORDER,
    @WamEnumConstant(28) ADD_ADDITIONAL_CHARGES_TO_ORDER,
    @WamEnumConstant(29) CLICK_ADD_ITEM,
    @WamEnumConstant(30) CLICK_ADD_ADDITIONAL_CHARGES,
    @WamEnumConstant(31) VIEW_EPHEMERAL_MESSAGES_PROMPT,
    @WamEnumConstant(32) CONFIRM_SENDING_ORDER_DETAILS,
    @WamEnumConstant(33) CANCEL_SENDING_ORDER_DETAILS,
    @WamEnumConstant(34) DO_NOT_SHOW_EPHEMERAL_MESSAGES_PROMPT,
    @WamEnumConstant(35) DISMISS_EPHEMERAL_MESSAGES_PROMPT,
    @WamEnumConstant(37) VIEW_EVENT_SHARING_TOS_PROMPT,
    @WamEnumConstant(38) DISMISS_EVENT_SHARING_TOS_PROMPT,
    @WamEnumConstant(39) CLICK_EVENT_SHARING_TOS,
    @WamEnumConstant(40) ACCEPT_EVENT_SHARING_TOS,
    @WamEnumConstant(41) REJECT_EVENT_SHARING_TOS,
    @WamEnumConstant(42) VIEW_CREATE_ORDER,
    @WamEnumConstant(43) DISPLAY_ORDER_STATUS_SHARING_TOS,
    @WamEnumConstant(44) CLICK_ORDER_STATUS_SHARING_TOS,
    @WamEnumConstant(45) CLICK_EDIT_INSTALLMENTS,
    @WamEnumConstant(46) VIEW_EDIT_INSTALLMENTS_PROMPT,
    @WamEnumConstant(47) SET_DEFAULT_INSTALLMENTS,
    @WamEnumConstant(48) SAVE_DEFAULT_INSTALLMENTS,
    @WamEnumConstant(49) DISMISS_EDIT_INSTALLMENTS_PROMPT,
    @WamEnumConstant(50) VIEW_ORDERS_VALUE_PROP,
    @WamEnumConstant(51) CONTINUE_FROM_ORDERS_VALUE_PROP,
    @WamEnumConstant(52) DISMISS_ORDERS_VALUE_PROP,
    @WamEnumConstant(53) CLICK_SEE_ALL_ORDER_REQUESTS,
    @WamEnumConstant(54) BIZ_ACTION_BAR,
    @WamEnumConstant(55) CLICK_ADD_ITEMS,
    @WamEnumConstant(56) CANCEL_ORDER_REQUEST,
    @WamEnumConstant(57) CONTINUE_ORDER_REQUEST,
    @WamEnumConstant(58) VIEW_PROMPT,
    @WamEnumConstant(59) CLICK_PROCEED_WITHOUT_CATALOG,
    @WamEnumConstant(60) CLICK_CREATE_ORDER_DETAILS_FROM_PAYMENT_METHOD_ADDED_PROMPT,
    @WamEnumConstant(61) VIEW_UPDATE_STATUS
}
