package com.github.auties00.cobalt.wire.wam.type;

import com.github.auties00.cobalt.meta.annotation.WhatsAppWebModule;

import com.github.auties00.cobalt.wam.annotation.WamEnum;
import com.github.auties00.cobalt.wam.annotation.WamEnumConstant;

@WhatsAppWebModule(moduleName = "WAWebWamEnumPlatformType")
@WamEnum
public enum PlatformType {
    @WamEnumConstant(1) IPHONE,
    @WamEnumConstant(2) ANDROID,
    @WamEnumConstant(3) BB,
    @WamEnumConstant(7) BBX,
    @WamEnumConstant(4) S40,
    @WamEnumConstant(5) SYMBIAN,
    @WamEnumConstant(6) WP,
    @WamEnumConstant(8) WEBCLIENT,
    @WamEnumConstant(11) OSMETA,
    @WamEnumConstant(12) ENT,
    @WamEnumConstant(13) SMBA,
    @WamEnumConstant(14) KAIOS,
    @WamEnumConstant(15) SMBI,
    @WamEnumConstant(16) WINDOWS,
    @WamEnumConstant(17) WEB,
    @WamEnumConstant(18) PORTAL,
    @WamEnumConstant(19) BLOKS,
    @WamEnumConstant(20) BLUEA,
    @WamEnumConstant(21) BLUEI,
    @WamEnumConstant(22) FBLITEA,
    @WamEnumConstant(23) GREENA,
    @WamEnumConstant(24) GREENI,
    @WamEnumConstant(25) IGDA,
    @WamEnumConstant(26) IGDI,
    @WamEnumConstant(27) IGLITEA,
    @WamEnumConstant(28) MLITEA,
    @WamEnumConstant(29) MSGRA,
    @WamEnumConstant(30) MSGRI,
    @WamEnumConstant(31) MSGRP,
    @WamEnumConstant(32) MSGRW,
    @WamEnumConstant(33) IGDW,
    @WamEnumConstant(34) PAGE,
    @WamEnumConstant(35) MSGRDM,
    @WamEnumConstant(36) MSGRDW,
    @WamEnumConstant(37) MSGROM,
    @WamEnumConstant(38) MSGROC,
    @WamEnumConstant(43) MSGRM,
    @WamEnumConstant(44) IGDM,
    @WamEnumConstant(45) WEARM,
    @WamEnumConstant(46) CAPI,
    @WamEnumConstant(47) XR,
    @WamEnumConstant(48) MACOS,
    @WamEnumConstant(49) WAMETA_REPL,
    @WamEnumConstant(50) ARDEV,
    @WamEnumConstant(51) WEAROS,
    @WamEnumConstant(52) MSGRVR,
    @WamEnumConstant(53) BLUEW,
    @WamEnumConstant(54) IPHONEWAMETATEST,
    @WamEnumConstant(57) MSGRAR,
    @WamEnumConstant(58) IPAD,
    @WamEnumConstant(59) WAVOIP_CLI,
    @WamEnumConstant(60) MSGRT,
    @WamEnumConstant(61) IGDT,
    @WamEnumConstant(62) ANDROIDWAMETATEST,
    @WamEnumConstant(63) MSGRSG,
    @WamEnumConstant(64) IGDSG,
    @WamEnumConstant(65) INTEROP,
    @WamEnumConstant(66) INTEROP_MSGR,
    @WamEnumConstant(67) IGDVR,
    @WamEnumConstant(68) WASG,
    @WamEnumConstant(69) BLUEVR,
    @WamEnumConstant(9) TEST,
    @WamEnumConstant(10) UNKNOWN
}
