package com.github.auties00.cobalt.wire.wam.type;

import com.github.auties00.cobalt.meta.annotation.WhatsAppWebModule;

import com.github.auties00.cobalt.wam.annotation.WamEnum;
import com.github.auties00.cobalt.wam.annotation.WamEnumConstant;

@WhatsAppWebModule(moduleName = "WAWebWamEnumProductArea")
@WamEnum
public enum ProductArea {
    @WamEnumConstant(1) UNKNOWN,
    @WamEnumConstant(2) COMMUNITIES,
    @WamEnumConstant(3) CHAT_LIST,
    @WamEnumConstant(4) BROADCAST,
    @WamEnumConstant(5) GROUP_INFO,
    @WamEnumConstant(6) EVENTS,
    @WamEnumConstant(7) CALLING,
    @WamEnumConstant(8) CHANNEL,
    @WamEnumConstant(9) STATUS,
    @WamEnumConstant(10) REACTION,
    @WamEnumConstant(11) CHAT_VIEW,
    @WamEnumConstant(12) CONTACT_INFO,
    @WamEnumConstant(13) FORWARD_PICKER,
    @WamEnumConstant(14) MEDIA,
    @WamEnumConstant(15) CAMERA,
    @WamEnumConstant(16) SETTING_PAGE,
    @WamEnumConstant(17) CATALOG,
    @WamEnumConstant(18) FLOW,
    @WamEnumConstant(19) PAYMENT,
    @WamEnumConstant(20) NOTIFICATION,
    @WamEnumConstant(21) MESSAGE_ACTIONS,
    @WamEnumConstant(22) PARTICIPANT_PICKER,
    @WamEnumConstant(23) GROUP,
    @WamEnumConstant(24) SEARCH,
    @WamEnumConstant(25) BUSINESS_PROFILE,
    @WamEnumConstant(26) AI,
    @WamEnumConstant(27) PROFILE,
    @WamEnumConstant(28) CONTACTS,
    @WamEnumConstant(29) REGISTRATION,
    @WamEnumConstant(31) STICKER,
    @WamEnumConstant(32) WALLPAPER,
    @WamEnumConstant(33) LIVE_LOCATION,
    @WamEnumConstant(34) BACKUP,
    @WamEnumConstant(35) COMPANION,
    @WamEnumConstant(36) FAVORITE,
    @WamEnumConstant(37) BANNER,
    @WamEnumConstant(38) VIEW_ONCE,
    @WamEnumConstant(39) DISAPPEARING_MESSAGE,
    @WamEnumConstant(40) BLOCK_AND_REPORT,
    @WamEnumConstant(41) EDUCATION,
    @WamEnumConstant(42) DEBUG,
    @WamEnumConstant(43) POLL,
    @WamEnumConstant(44) ORDER,
    @WamEnumConstant(45) EMOJI,
    @WamEnumConstant(46) CHANGE_NUMBER,
    @WamEnumConstant(47) REG,
    @WamEnumConstant(48) OTHER_PLATFORM,
    @WamEnumConstant(49) CHAT_LOCK,
    @WamEnumConstant(50) PTV,
    @WamEnumConstant(51) SMB,
    @WamEnumConstant(52) ACCOUNT_DELETION,
    @WamEnumConstant(53) CTWA,
    @WamEnumConstant(54) PRIVACY,
    @WamEnumConstant(55) AVATARS,
    @WamEnumConstant(56) MEDIA_PREVIEW,
    @WamEnumConstant(57) MEDIA_PICKER,
    @WamEnumConstant(58) MEDIA_BROWSER,
    @WamEnumConstant(59) PTT,
    @WamEnumConstant(60) CRITICAL_LOW_STORAGE,
    @WamEnumConstant(61) WAFFLE,
    @WamEnumConstant(62) IN_APP_BROWSER,
    @WamEnumConstant(63) AI_HATCH
}
