package com.github.auties00.cobalt.wire.wam.type;

import com.github.auties00.cobalt.meta.annotation.WhatsAppWebModule;

import com.github.auties00.cobalt.wam.annotation.WamEnum;
import com.github.auties00.cobalt.wam.annotation.WamEnumConstant;

@WhatsAppWebModule(moduleName = "WAWebWamEnumSettingsItemType")
@WamEnum
public enum SettingsItemType {
    @WamEnumConstant(0) PROFILE,
    @WamEnumConstant(1) BUSINESS_TOOLS,
    @WamEnumConstant(2) ACCOUNT,
    @WamEnumConstant(3) CHATS,
    @WamEnumConstant(4) NOTIFICATIONS,
    @WamEnumConstant(5) DATA_STORAGE_USAGE,
    @WamEnumConstant(6) HELP,
    @WamEnumConstant(7) INVITE_FRIEND,
    @WamEnumConstant(8) STARRED_MESSAGES,
    @WamEnumConstant(9) WHATSAPP_WEB,
    @WamEnumConstant(10) PREMIUM_SUBSCRIPTION,
    @WamEnumConstant(11) PRIVACY,
    @WamEnumConstant(12) SECURITY,
    @WamEnumConstant(13) THEME,
    @WamEnumConstant(14) CHAT_WALLPAPER,
    @WamEnumConstant(15) MEDIA_AUTO_DOWNLOAD,
    @WamEnumConstant(16) REQUEST_ACCOUNT_INFO,
    @WamEnumConstant(17) KEYBOARD_SHORTCUTS,
    @WamEnumConstant(18) DEVELOPER,
    @WamEnumConstant(19) DATA_SHARING,
    @WamEnumConstant(20) DESKTOP_SETTINGS,
    @WamEnumConstant(21) LINKED_DEVICES,
    @WamEnumConstant(22) UNKNOWN,
    @WamEnumConstant(23) QR_CODE,
    @WamEnumConstant(24) DEVICES,
    @WamEnumConstant(25) PROFILE_CARD,
    @WamEnumConstant(26) PRIVACY_CARD,
    @WamEnumConstant(27) CONTACTS_CARD,
    @WamEnumConstant(28) AVATAR,
    @WamEnumConstant(29) PAYMENTS,
    @WamEnumConstant(30) LOGOUT,
    @WamEnumConstant(31) META_VERIFIED,
    @WamEnumConstant(32) TEXT_STATUS,
    @WamEnumConstant(33) THIRD_PARTY,
    @WamEnumConstant(34) IG_BOOKMARK,
    @WamEnumConstant(35) FB_BOOKMARK,
    @WamEnumConstant(36) FAVORITES,
    @WamEnumConstant(37) THREADS_BOOKMARK,
    @WamEnumConstant(38) LISTS,
    @WamEnumConstant(39) PROFILE_LINKS,
    @WamEnumConstant(40) WAFFLE,
    @WamEnumConstant(41) FEEDBACK,
    @WamEnumConstant(42) META_AI_BOOKMARK,
    @WamEnumConstant(43) META_HORIZON_BOOKMARK,
    @WamEnumConstant(44) VIBES_BOOKMARK,
    @WamEnumConstant(45) CONTACTS,
    @WamEnumConstant(46) APPEARANCE,
    @WamEnumConstant(47) USERNAME,
    @WamEnumConstant(48) TOAST_VIEW_LATEST_SELF_STATUS,
    @WamEnumConstant(49) PROFILE_VIEW_FIRST_UNREAD_SELF_STATUS,
    @WamEnumConstant(50) PROFILE_VIEW_OLDEST_SELF_STATUS,
    @WamEnumConstant(51) BADGE_ADD_SELF_STATUS,
    @WamEnumConstant(52) PROFILE_ADD_SELF_STATUS,
    @WamEnumConstant(53) PROFILE_OPEN_CONTEXT_MENU,
    @WamEnumConstant(55) CONTEXT_MENU_ADD_PROFILE_PICTURE,
    @WamEnumConstant(56) CONTEXT_MENU_VIEW_FIRST_UNREAD_SELF_STATUS,
    @WamEnumConstant(57) CONTEXT_MENU_VIEW_OLDEST_SELF_STATUS,
    @WamEnumConstant(58) CONTEXT_MENU_ADD_SELF_STATUS
}
