package com.github.auties00.cobalt.wire.wam.type;

import com.github.auties00.cobalt.meta.annotation.WhatsAppWebModule;

import com.github.auties00.cobalt.wam.annotation.WamEnum;
import com.github.auties00.cobalt.wam.annotation.WamEnumConstant;

@WhatsAppWebModule(moduleName = "WAWebWamEnumStatusCreationEntryPoint")
@WamEnum
public enum StatusCreationEntryPoint {
    @WamEnumConstant(1) EXTERNAL_SHARE,
    @WamEnumConstant(2) FORWARD_TO_STATUS,
    @WamEnumConstant(3) STATUS_TAB_CAMERA,
    @WamEnumConstant(4) STATUS_TAB_PEN,
    @WamEnumConstant(5) STATUS_DEEPLINK,
    @WamEnumConstant(6) CHANNEL_POST,
    @WamEnumConstant(7) CHANNEL_LINK,
    @WamEnumConstant(8) STATUS_TAB_SELF_POG,
    @WamEnumConstant(9) CHATS_TAB_CAMERA,
    @WamEnumConstant(10) CHAT_THREAD_CAMERA,
    @WamEnumConstant(11) CALLS_TAB_CAMERA,
    @WamEnumConstant(12) STATUS_TAB_FAB_CAMERA,
    @WamEnumConstant(13) COMMUNITIES_TAB_CAMERA,
    @WamEnumConstant(14) MY_STATUS_PEN,
    @WamEnumConstant(15) MY_STATUS_FAB_CAMERA,
    @WamEnumConstant(16) STATUS_RESHARE,
    @WamEnumConstant(17) SELF_POG_ON_STATUS_VIEWER,
    @WamEnumConstant(18) CATALOG_MANAGER,
    @WamEnumConstant(19) CATALOG_PRODUCT_DETAILS,
    @WamEnumConstant(20) MEDIA_PICKER_CAMERA_ACTION,
    @WamEnumConstant(21) MEDIA_PICKER_TEXT_ACTION,
    @WamEnumConstant(22) STATUS_CREATION_ENTRY_POINT,
    @WamEnumConstant(23) UNIFIED_CREATION_QUICK_ACTION_CAMERA,
    @WamEnumConstant(24) UNIFIED_CREATION_QUICK_ACTION_PEN,
    @WamEnumConstant(25) UNIFIED_CREATION_MENU_CAMERA,
    @WamEnumConstant(26) UNIFIED_CREATION_MENU_GALLERY,
    @WamEnumConstant(27) UNIFIED_CREATION_MENU_TEXT_OR_VOICE,
    @WamEnumConstant(28) UNIFIED_CREATION_MENU_NEW_STATUS,
    @WamEnumConstant(29) MEDIA_PICKER_VOICE_ACTION,
    @WamEnumConstant(30) MUSIC_ATTRIBUTION,
    @WamEnumConstant(31) STATUS_PROMPT_RESPONSE,
    @WamEnumConstant(32) AI_IMAGINE_BOTTOM_SHEET,
    @WamEnumConstant(33) STATUS_POST_RESHARE,
    @WamEnumConstant(34) WA_GROUP_INVITE,
    @WamEnumConstant(35) FORWARD_FROM_STATUS,
    @WamEnumConstant(36) GROUP_INFO_PAGE,
    @WamEnumConstant(37) STATUS_VIEWER_TOPBAR,
    @WamEnumConstant(38) QUESTION_ANSWER_RESHARE,
    @WamEnumConstant(39) GROUP_STATUS_TAB_SELF_POG,
    @WamEnumConstant(40) GROUP_STATUS_TAB_CAMERA,
    @WamEnumConstant(41) GROUP_STATUS_TAB_PEN,
    @WamEnumConstant(42) MY_GROUP_STATUS_FAB_CAMERA,
    @WamEnumConstant(43) STATUS_WIDGET,
    @WamEnumConstant(44) ENGAGEMENT_CARD,
    @WamEnumConstant(45) CHANNEL_STATUS_TAB_SELF_POG,
    @WamEnumConstant(46) MY_CHANNEL_STATUS_FAB_CAMERA,
    @WamEnumConstant(47) CHANNEL_THREAD_PAGE,
    @WamEnumConstant(48) CHANNEL_STATUS_VIEWER_TOP_BAR,
    @WamEnumConstant(50) GROUP_STATUS_CHAT_HEADER,
    @WamEnumConstant(51) CHATS_TAB_SELF_POG,
    @WamEnumConstant(52) CHATS_TAB_NEW_CHAT,
    @WamEnumConstant(53) GROUP_STATUS_CHAT_HEADER_PROFILE_RING,
    @WamEnumConstant(54) GROUP_STATUS_CHAT_HEADER_PROFILE_RING_DROPDOWN,
    @WamEnumConstant(55) CLOSE_SHARING_MIMICRY,
    @WamEnumConstant(56) CHANNEL_THREAD_SCREEN,
    @WamEnumConstant(57) MEDIA_BROWSER_STATUS_MENU,
    @WamEnumConstant(58) ARCHIVE_STATUS_VIEWER,
    @WamEnumConstant(59) ME_TAB
}
