package com.github.auties00.cobalt.wire.wam.type;

import com.github.auties00.cobalt.meta.annotation.WhatsAppWebModule;

import com.github.auties00.cobalt.wam.annotation.WamEnum;
import com.github.auties00.cobalt.wam.annotation.WamEnumConstant;

@WhatsAppWebModule(moduleName = "WAWebWamEnumStatusPostOrigin")
@WamEnum
public enum StatusPostOrigin {
    @WamEnumConstant(1) CAMERA_TAB,
    @WamEnumConstant(2) STATUS_TAB,
    @WamEnumConstant(3) FORWARD_FROM_MESSAGES,
    @WamEnumConstant(4) EXTERNAL_SHARE,
    @WamEnumConstant(5) CAMERA_CHAT,
    @WamEnumConstant(6) STATUS_TAB_PEN,
    @WamEnumConstant(7) STATUS_TAB_CAMERA,
    @WamEnumConstant(8) STATUS_TAB_SELF_POG,
    @WamEnumConstant(9) CALLS_TAB_CAMERA,
    @WamEnumConstant(10) STATUS_TAB_FAB_CAMERA,
    @WamEnumConstant(11) COMMUNITIES_TAB_CAMERA,
    @WamEnumConstant(12) MY_STATUS_PEN,
    @WamEnumConstant(13) MY_STATUS_FAB_CAMERA,
    @WamEnumConstant(14) STATUS_DEEPLINK,
    @WamEnumConstant(15) SELF_POG_ON_STATUS_VIEWER,
    @WamEnumConstant(16) STATUS_RESHARE,
    @WamEnumConstant(17) CHATS_TAB_CAMERA,
    @WamEnumConstant(18) CATALOG_MANAGER,
    @WamEnumConstant(19) CATALOG_PRODUCT_DETAILS,
    @WamEnumConstant(20) MEDIA_PICKER_CAMERA_ACTION,
    @WamEnumConstant(21) MEDIA_PICKER_TEXT_ACTION,
    @WamEnumConstant(22) STATUS_PROMPT_RESPONSE,
    @WamEnumConstant(23) UNIFIED_CREATION_QUICK_ACTION_CAMERA,
    @WamEnumConstant(24) UNIFIED_CREATION_QUICK_ACTION_PEN,
    @WamEnumConstant(25) UNIFIED_CREATION_MENU_CAMERA,
    @WamEnumConstant(26) UNIFIED_CREATION_MENU_GALLERY,
    @WamEnumConstant(27) UNIFIED_CREATION_MENU_TEXT_OR_VOICE,
    @WamEnumConstant(28) UNIFIED_CREATION_MENU_NEW_STATUS,
    @WamEnumConstant(29) MEDIA_PICKER_VOICE_ACTION,
    @WamEnumConstant(30) MUSIC_ATTRIBUTION,
    @WamEnumConstant(31) AI_IMAGINE,
    @WamEnumConstant(32) STATUS_POST_RESHARE,
    @WamEnumConstant(33) WA_GROUP_INVITE,
    @WamEnumConstant(34) FORWARD_FROM_STATUS,
    @WamEnumConstant(35) GROUP_INFO_PAGE,
    @WamEnumConstant(36) STATUS_VIEWER_TOPBAR,
    @WamEnumConstant(37) QUESTION_ANSWER_RESHARE,
    @WamEnumConstant(38) STATUS_ADD_YOURS_AI_IMAGINE,
    @WamEnumConstant(39) GROUP_STATUS_TAB_SELF_POG,
    @WamEnumConstant(40) GROUP_STATUS_TAB_CAMERA,
    @WamEnumConstant(41) GROUP_STATUS_TAB_PEN,
    @WamEnumConstant(42) MY_GROUP_STATUS_FAB_CAMERA,
    @WamEnumConstant(43) STATUS_WIDGET,
    @WamEnumConstant(44) ENGAGEMENT_CARD,
    @WamEnumConstant(45) CHANNEL_STATUS_TAB_SELF_POG,
    @WamEnumConstant(46) MY_CHANNEL_STATUS_FAB_CAMERA,
    @WamEnumConstant(47) CHANNEL_THREAD_SCREEN,
    @WamEnumConstant(48) CHANNEL_INFO_SCREEN,
    @WamEnumConstant(49) GROUP_STATUS_CHAT_HEADER,
    @WamEnumConstant(50) CHATS_TAB_SELF_POG,
    @WamEnumConstant(51) CHATS_TAB_NEW_CHAT,
    @WamEnumConstant(52) GROUP_STATUS_CHAT_HEADER_PROFILE_RING,
    @WamEnumConstant(53) GROUP_STATUS_CHAT_HEADER_PROFILE_RING_DROPDOWN,
    @WamEnumConstant(54) CLOSE_SHARING_MIMICRY,
    @WamEnumConstant(55) CHANNEL_STATUS_VIEWER_TOP_BAR,
    @WamEnumConstant(56) MEDIA_BROWSER_STATUS_MENU,
    @WamEnumConstant(57) ARCHIVE_STATUS_VIEWER,
    @WamEnumConstant(58) ME_TAB
}
