package com.github.auties00.cobalt.wire.wam.type;

import com.github.auties00.cobalt.meta.annotation.WhatsAppWebModule;

import com.github.auties00.cobalt.wam.annotation.WamEnum;
import com.github.auties00.cobalt.wam.annotation.WamEnumConstant;

@WhatsAppWebModule(moduleName = "WAWebWamEnumStatusPrivacySettingsAction")
@WamEnum
public enum StatusPrivacySettingsAction {
    @WamEnumConstant(1) AUDIENCE_SELECTION_ENTRYPOINT_CLICKED,
    @WamEnumConstant(2) INCLUDE_CONTACT_LIST_LAUNCHED,
    @WamEnumConstant(3) EXCLUDE_CONTACT_LIST_LAUNCHED,
    @WamEnumConstant(4) MY_CONTACTS_CLICKED,
    @WamEnumConstant(5) MY_CONTACTS_EXCEPT_CLICKED,
    @WamEnumConstant(6) ONLY_SHARE_WITH_CLICKED,
    @WamEnumConstant(7) UPDATED_STATUS_PRIVACY_SETTING,
    @WamEnumConstant(8) ALLOW_RESHARING_CLICKED,
    @WamEnumConstant(9) ALLOW_FORWARDING_CLICKED,
    @WamEnumConstant(10) UPDATED_STATUS_FORWARD_SETTING,
    @WamEnumConstant(11) UPDATED_STATUS_INCLUDE_CLOSE_FRIENDS_LAUNCHED,
    @WamEnumConstant(12) LIST_CONTACT_SELECTED,
    @WamEnumConstant(13) LIST_CONTACT_DESELECTED,
    @WamEnumConstant(14) MERGED_AUDIENCE_EDIT_CLICKED,
    @WamEnumConstant(15) CREATE_CUSTOM_AUDIENCE_CLICKED,
    @WamEnumConstant(16) CUSTOM_AUDIENCE_CONTACT_LIST_LAUNCHED,
    @WamEnumConstant(17) CUSTOM_AUDIENCE_EMOJI_CHANGED,
    @WamEnumConstant(18) CUSTOM_AUDIENCE_CREATED,
    @WamEnumConstant(19) CUSTOM_AUDIENCE_DELETED,
    @WamEnumConstant(20) CUSTOM_AUDIENCE_UPDATED,
    @WamEnumConstant(21) CUSTOM_AUDIENCE_CLICKED,
    @WamEnumConstant(22) CLOSE_FRIENDS_CLICKED,
    @WamEnumConstant(23) CLOSE_FRIENDS__LIST_LAUNCHED,
    @WamEnumConstant(24) CUSTOM_AUDIENCE_SELECT_ALL_CLICK,
    @WamEnumConstant(25) CUSTOM_AUDIENCE_UNSELECT_ALL_CLICK,
    @WamEnumConstant(26) CUSTOM_AUDIENCE_GROUP_BUILDER_DESELECTED_ON_SEARCH,
    @WamEnumConstant(27) CUSTOM_AUDIENCE_GROUP_BUILDER_SELECTED_ON_SEARCH,
    @WamEnumConstant(28) CUSTOM_AUDIENCE_CONTACT_SEARCH_TAP,
    @WamEnumConstant(29) SEE_ALL_BUILDERS_DONE_CLICKED,
    @WamEnumConstant(30) CUSTOM_AUDIENCE_OSW_BUILDER_DESELECTED_ON_SEE_ALL_BUILDERS,
    @WamEnumConstant(31) CUSTOM_AUDIENCE_OSW_BUILDER_SELECTED_ON_SEE_ALL_BUILDERS,
    @WamEnumConstant(32) CUSTOM_AUDIENCE_GROUP_BUILDER_DESELECTED_ON_SEE_ALL_BUILDERS,
    @WamEnumConstant(33) CUSTOM_AUDIENCE_GROUP_BUILDER_SELECTED_ON_SEE_ALL_BUILDERS,
    @WamEnumConstant(34) CUSTOM_AUDIENCE_GROUP_BUILDER_DESELECTED_ON_CONTACT_PICKER,
    @WamEnumConstant(35) CUSTOM_AUDIENCE_GROUP_BUILDER_SELECTED_ON_CONTACT_PICKER,
    @WamEnumConstant(36) CUSTOM_AUDIENCE_OSW_BUILDER_DESELECTED_ON_CONTACT_PICKER,
    @WamEnumConstant(37) CUSTOM_AUDIENCE_OSW_BUILDER_SELECTED_ON_CONTACT_PICKER,
    @WamEnumConstant(38) CUSTOM_AUDIENCE_BUILDERS_SEE_ALL_CLICK,
    @WamEnumConstant(39) CUSTOM_AUDIENCE_BUILDER_DETAILS_CLICK,
    @WamEnumConstant(40) AUDIENCE_SELECTION_ENTRYPOINT_CREATE_YOUR_OWN_CLICKED,
    @WamEnumConstant(41) AUDIENCE_SELECTION_ENTRYPOINT_ADD_TO_CF_CLICKED,
    @WamEnumConstant(42) CREATE_CLOSE_FRIENDS_CLICKED,
    @WamEnumConstant(43) CLOSE_FRIENDS_CREATED,
    @WamEnumConstant(44) CUSTOM_AUDIENCE_CONTACT_PICKER_NEXT_CLICKED
}
