package com.github.auties00.cobalt.wire.linked.business.profile;

import it.auties.protobuf.annotation.ProtobufDeserializer;
import it.auties.protobuf.annotation.ProtobufSerializer;

/**
 * Represents the bot automation type of a WhatsApp Business account, indicating the level
 * and source of automated messaging configured for the business.
 *
 * <p>Three values are currently defined by the WhatsApp protocol:
 * <ul>
 *   <li>{@link Partial1P} indicates a first-party partially automated bot where some
 *       responses are generated automatically while others are handled by a human operator.
 *   <li>{@link Full3P} indicates a third-party fully automated bot where all responses
 *       are generated by an external automation platform.
 *   <li>{@link Unknown} with a wire value of {@code "unknown"} indicates that the
 *       automation status could not be determined.
 * </ul>
 *
 * <p>An {@code Unknown} variant is also used for forward compatibility with values that
 * may be introduced by the server in the future.
 *
 * <p>The wire format is a plain {@code String} (e.g. {@code "1p_partial"}).
 *
 * @see BusinessProfile#automatedType()
 */
public sealed interface BusinessAutomatedType {
    /**
     * The singleton instance for an undetermined automation status, corresponding to the
     * wire value {@code "unknown"}.
     */
    BusinessAutomatedType UNKNOWN = new Unknown("unknown");

    /**
     * The singleton instance for a first-party partially automated bot.
     */
    BusinessAutomatedType PARTIAL_1P = new Partial1P();

    /**
     * The singleton instance for a third-party fully automated bot.
     */
    BusinessAutomatedType FULL_3P = new Full3P();

    /**
     * Returns the {@code BusinessAutomatedType} corresponding to the given wire value.
     *
     * <p>Recognized values are {@code "unknown"}, {@code "1p_partial"}, and
     * {@code "3p_full"} (case-sensitive). Any other non-{@code null} value yields an
     * {@link Unknown} instance that preserves the original string.
     *
     * @param value the wire-format string, or {@code null}
     * @return the corresponding type, or {@code null} if {@code value} is {@code null}
     */
    @ProtobufDeserializer
    static BusinessAutomatedType of(String value) {
        if (value == null) {
            return null;
        }
        return switch (value) {
            case "unknown" -> UNKNOWN;
            case "1p_partial" -> PARTIAL_1P;
            case "3p_full" -> FULL_3P;
            default -> new Unknown(value);
        };
    }

    /**
     * Returns the wire-format string representation of this automation type.
     *
     * @return the type value as sent over the wire (e.g. {@code "1p_partial"})
     */
    @ProtobufSerializer
    String value();

    /**
     * A first-party partially automated bot where some responses are generated
     * automatically while others are handled by a human operator.
     */
    record Partial1P() implements BusinessAutomatedType {
        /**
         * {@inheritDoc}
         *
         * @return {@code "1p_partial"}
         */
        @Override
        public String value() {
            return "1p_partial";
        }
    }

    /**
     * A third-party fully automated bot where all responses are generated by an external
     * automation platform.
     */
    record Full3P() implements BusinessAutomatedType {
        /**
         * {@inheritDoc}
         *
         * @return {@code "3p_full"}
         */
        @Override
        public String value() {
            return "3p_full";
        }
    }

    /**
     * An automation type that is either undetermined or unrecognized.
     *
     * <p>When the wire value is {@code "unknown"}, the automation status could not be
     * determined by the server. For any other value, this variant preserves the original
     * string for forward compatibility.
     *
     * @param value the raw wire-format string
     */
    record Unknown(String value) implements BusinessAutomatedType {
    }
}
