// Generated by jextract

package com.github.auties00.cobalt.util.ffmpeg;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct AVFilterInOut {
 *     char *name;
 *     AVFilterContext *filter_ctx;
 *     int pad_idx;
 *     struct AVFilterInOut *next;
 * }
 * }
 */
public class AVFilterInOut {

    AVFilterInOut() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Ffmpeg.C_POINTER.withName("name"),
        Ffmpeg.C_POINTER.withName("filter_ctx"),
        Ffmpeg.C_INT.withName("pad_idx"),
        MemoryLayout.paddingLayout(4),
        Ffmpeg.C_POINTER.withName("next")
    ).withName("AVFilterInOut");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout name$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char *name
     * }
     */
    public static final AddressLayout name$layout() {
        return name$LAYOUT;
    }

    private static final long name$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char *name
     * }
     */
    public static final long name$offset() {
        return name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char *name
     * }
     */
    public static MemorySegment name(MemorySegment struct) {
        return struct.get(name$LAYOUT, name$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char *name
     * }
     */
    public static void name(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(name$LAYOUT, name$OFFSET, fieldValue);
    }

    private static final AddressLayout filter_ctx$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("filter_ctx"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVFilterContext *filter_ctx
     * }
     */
    public static final AddressLayout filter_ctx$layout() {
        return filter_ctx$LAYOUT;
    }

    private static final long filter_ctx$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVFilterContext *filter_ctx
     * }
     */
    public static final long filter_ctx$offset() {
        return filter_ctx$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVFilterContext *filter_ctx
     * }
     */
    public static MemorySegment filter_ctx(MemorySegment struct) {
        return struct.get(filter_ctx$LAYOUT, filter_ctx$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVFilterContext *filter_ctx
     * }
     */
    public static void filter_ctx(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(filter_ctx$LAYOUT, filter_ctx$OFFSET, fieldValue);
    }

    private static final OfInt pad_idx$LAYOUT = (OfInt)$LAYOUT.select(groupElement("pad_idx"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int pad_idx
     * }
     */
    public static final OfInt pad_idx$layout() {
        return pad_idx$LAYOUT;
    }

    private static final long pad_idx$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int pad_idx
     * }
     */
    public static final long pad_idx$offset() {
        return pad_idx$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int pad_idx
     * }
     */
    public static int pad_idx(MemorySegment struct) {
        return struct.get(pad_idx$LAYOUT, pad_idx$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int pad_idx
     * }
     */
    public static void pad_idx(MemorySegment struct, int fieldValue) {
        struct.set(pad_idx$LAYOUT, pad_idx$OFFSET, fieldValue);
    }

    private static final AddressLayout next$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("next"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * struct AVFilterInOut *next
     * }
     */
    public static final AddressLayout next$layout() {
        return next$LAYOUT;
    }

    private static final long next$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * struct AVFilterInOut *next
     * }
     */
    public static final long next$offset() {
        return next$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * struct AVFilterInOut *next
     * }
     */
    public static MemorySegment next(MemorySegment struct) {
        return struct.get(next$LAYOUT, next$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * struct AVFilterInOut *next
     * }
     */
    public static void next(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(next$LAYOUT, next$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

