// Generated by jextract

package com.github.auties00.cobalt.util.ffmpeg;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct AVFilterFormatsConfig {
 *     AVFilterFormats *formats;
 *     AVFilterFormats *samplerates;
 *     AVFilterChannelLayouts *channel_layouts;
 *     AVFilterFormats *color_spaces;
 *     AVFilterFormats *color_ranges;
 * }
 * }
 */
public class AVFilterFormatsConfig {

    AVFilterFormatsConfig() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Ffmpeg.C_POINTER.withName("formats"),
        Ffmpeg.C_POINTER.withName("samplerates"),
        Ffmpeg.C_POINTER.withName("channel_layouts"),
        Ffmpeg.C_POINTER.withName("color_spaces"),
        Ffmpeg.C_POINTER.withName("color_ranges")
    ).withName("AVFilterFormatsConfig");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout formats$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("formats"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVFilterFormats *formats
     * }
     */
    public static final AddressLayout formats$layout() {
        return formats$LAYOUT;
    }

    private static final long formats$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVFilterFormats *formats
     * }
     */
    public static final long formats$offset() {
        return formats$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVFilterFormats *formats
     * }
     */
    public static MemorySegment formats(MemorySegment struct) {
        return struct.get(formats$LAYOUT, formats$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVFilterFormats *formats
     * }
     */
    public static void formats(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(formats$LAYOUT, formats$OFFSET, fieldValue);
    }

    private static final AddressLayout samplerates$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("samplerates"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVFilterFormats *samplerates
     * }
     */
    public static final AddressLayout samplerates$layout() {
        return samplerates$LAYOUT;
    }

    private static final long samplerates$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVFilterFormats *samplerates
     * }
     */
    public static final long samplerates$offset() {
        return samplerates$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVFilterFormats *samplerates
     * }
     */
    public static MemorySegment samplerates(MemorySegment struct) {
        return struct.get(samplerates$LAYOUT, samplerates$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVFilterFormats *samplerates
     * }
     */
    public static void samplerates(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(samplerates$LAYOUT, samplerates$OFFSET, fieldValue);
    }

    private static final AddressLayout channel_layouts$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("channel_layouts"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVFilterChannelLayouts *channel_layouts
     * }
     */
    public static final AddressLayout channel_layouts$layout() {
        return channel_layouts$LAYOUT;
    }

    private static final long channel_layouts$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVFilterChannelLayouts *channel_layouts
     * }
     */
    public static final long channel_layouts$offset() {
        return channel_layouts$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVFilterChannelLayouts *channel_layouts
     * }
     */
    public static MemorySegment channel_layouts(MemorySegment struct) {
        return struct.get(channel_layouts$LAYOUT, channel_layouts$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVFilterChannelLayouts *channel_layouts
     * }
     */
    public static void channel_layouts(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(channel_layouts$LAYOUT, channel_layouts$OFFSET, fieldValue);
    }

    private static final AddressLayout color_spaces$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("color_spaces"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVFilterFormats *color_spaces
     * }
     */
    public static final AddressLayout color_spaces$layout() {
        return color_spaces$LAYOUT;
    }

    private static final long color_spaces$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVFilterFormats *color_spaces
     * }
     */
    public static final long color_spaces$offset() {
        return color_spaces$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVFilterFormats *color_spaces
     * }
     */
    public static MemorySegment color_spaces(MemorySegment struct) {
        return struct.get(color_spaces$LAYOUT, color_spaces$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVFilterFormats *color_spaces
     * }
     */
    public static void color_spaces(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(color_spaces$LAYOUT, color_spaces$OFFSET, fieldValue);
    }

    private static final AddressLayout color_ranges$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("color_ranges"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVFilterFormats *color_ranges
     * }
     */
    public static final AddressLayout color_ranges$layout() {
        return color_ranges$LAYOUT;
    }

    private static final long color_ranges$OFFSET = 32;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVFilterFormats *color_ranges
     * }
     */
    public static final long color_ranges$offset() {
        return color_ranges$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVFilterFormats *color_ranges
     * }
     */
    public static MemorySegment color_ranges(MemorySegment struct) {
        return struct.get(color_ranges$LAYOUT, color_ranges$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVFilterFormats *color_ranges
     * }
     */
    public static void color_ranges(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(color_ranges$LAYOUT, color_ranges$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

