// Generated by jextract

package com.github.auties00.cobalt.util.ffmpeg;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct AVFilter {
 *     const char *name;
 *     const char *description;
 *     const AVFilterPad *inputs;
 *     const AVFilterPad *outputs;
 *     const AVClass *priv_class;
 *     int flags;
 *     uint8_t nb_inputs;
 *     uint8_t nb_outputs;
 *     uint8_t formats_state;
 *     int (*preinit)(AVFilterContext *);
 *     int (*init)(AVFilterContext *);
 *     void (*uninit)(AVFilterContext *);
 *     union {
 *         int (*query_func)(AVFilterContext *);
 *         int (*query_func2)(const AVFilterContext *, struct AVFilterFormatsConfig **, struct AVFilterFormatsConfig **);
 *         const enum AVPixelFormat *pixels_list;
 *         const enum AVSampleFormat *samples_list;
 *         enum AVPixelFormat pix_fmt;
 *         enum AVSampleFormat sample_fmt;
 *     } formats;
 *     int priv_size;
 *     int flags_internal;
 *     int (*process_command)(AVFilterContext *, const char *, const char *, char *, int, int);
 *     int (*activate)(AVFilterContext *);
 * }
 * }
 */
public class AVFilter {

    AVFilter() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Ffmpeg.C_POINTER.withName("name"),
        Ffmpeg.C_POINTER.withName("description"),
        Ffmpeg.C_POINTER.withName("inputs"),
        Ffmpeg.C_POINTER.withName("outputs"),
        Ffmpeg.C_POINTER.withName("priv_class"),
        Ffmpeg.C_INT.withName("flags"),
        Ffmpeg.C_CHAR.withName("nb_inputs"),
        Ffmpeg.C_CHAR.withName("nb_outputs"),
        Ffmpeg.C_CHAR.withName("formats_state"),
        MemoryLayout.paddingLayout(1),
        Ffmpeg.C_POINTER.withName("preinit"),
        Ffmpeg.C_POINTER.withName("init"),
        Ffmpeg.C_POINTER.withName("uninit"),
        AVFilter.formats.layout().withName("formats"),
        Ffmpeg.C_INT.withName("priv_size"),
        Ffmpeg.C_INT.withName("flags_internal"),
        Ffmpeg.C_POINTER.withName("process_command"),
        Ffmpeg.C_POINTER.withName("activate")
    ).withName("AVFilter");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout name$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("name"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *name
     * }
     */
    public static final AddressLayout name$layout() {
        return name$LAYOUT;
    }

    private static final long name$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *name
     * }
     */
    public static final long name$offset() {
        return name$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *name
     * }
     */
    public static MemorySegment name(MemorySegment struct) {
        return struct.get(name$LAYOUT, name$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *name
     * }
     */
    public static void name(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(name$LAYOUT, name$OFFSET, fieldValue);
    }

    private static final AddressLayout description$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("description"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const char *description
     * }
     */
    public static final AddressLayout description$layout() {
        return description$LAYOUT;
    }

    private static final long description$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const char *description
     * }
     */
    public static final long description$offset() {
        return description$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const char *description
     * }
     */
    public static MemorySegment description(MemorySegment struct) {
        return struct.get(description$LAYOUT, description$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const char *description
     * }
     */
    public static void description(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(description$LAYOUT, description$OFFSET, fieldValue);
    }

    private static final AddressLayout inputs$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("inputs"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const AVFilterPad *inputs
     * }
     */
    public static final AddressLayout inputs$layout() {
        return inputs$LAYOUT;
    }

    private static final long inputs$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const AVFilterPad *inputs
     * }
     */
    public static final long inputs$offset() {
        return inputs$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const AVFilterPad *inputs
     * }
     */
    public static MemorySegment inputs(MemorySegment struct) {
        return struct.get(inputs$LAYOUT, inputs$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const AVFilterPad *inputs
     * }
     */
    public static void inputs(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(inputs$LAYOUT, inputs$OFFSET, fieldValue);
    }

    private static final AddressLayout outputs$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("outputs"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const AVFilterPad *outputs
     * }
     */
    public static final AddressLayout outputs$layout() {
        return outputs$LAYOUT;
    }

    private static final long outputs$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const AVFilterPad *outputs
     * }
     */
    public static final long outputs$offset() {
        return outputs$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const AVFilterPad *outputs
     * }
     */
    public static MemorySegment outputs(MemorySegment struct) {
        return struct.get(outputs$LAYOUT, outputs$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const AVFilterPad *outputs
     * }
     */
    public static void outputs(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(outputs$LAYOUT, outputs$OFFSET, fieldValue);
    }

    private static final AddressLayout priv_class$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("priv_class"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * const AVClass *priv_class
     * }
     */
    public static final AddressLayout priv_class$layout() {
        return priv_class$LAYOUT;
    }

    private static final long priv_class$OFFSET = 32;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * const AVClass *priv_class
     * }
     */
    public static final long priv_class$offset() {
        return priv_class$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * const AVClass *priv_class
     * }
     */
    public static MemorySegment priv_class(MemorySegment struct) {
        return struct.get(priv_class$LAYOUT, priv_class$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * const AVClass *priv_class
     * }
     */
    public static void priv_class(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(priv_class$LAYOUT, priv_class$OFFSET, fieldValue);
    }

    private static final OfInt flags$LAYOUT = (OfInt)$LAYOUT.select(groupElement("flags"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int flags
     * }
     */
    public static final OfInt flags$layout() {
        return flags$LAYOUT;
    }

    private static final long flags$OFFSET = 40;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int flags
     * }
     */
    public static final long flags$offset() {
        return flags$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int flags
     * }
     */
    public static int flags(MemorySegment struct) {
        return struct.get(flags$LAYOUT, flags$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int flags
     * }
     */
    public static void flags(MemorySegment struct, int fieldValue) {
        struct.set(flags$LAYOUT, flags$OFFSET, fieldValue);
    }

    private static final OfByte nb_inputs$LAYOUT = (OfByte)$LAYOUT.select(groupElement("nb_inputs"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t nb_inputs
     * }
     */
    public static final OfByte nb_inputs$layout() {
        return nb_inputs$LAYOUT;
    }

    private static final long nb_inputs$OFFSET = 44;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t nb_inputs
     * }
     */
    public static final long nb_inputs$offset() {
        return nb_inputs$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t nb_inputs
     * }
     */
    public static byte nb_inputs(MemorySegment struct) {
        return struct.get(nb_inputs$LAYOUT, nb_inputs$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t nb_inputs
     * }
     */
    public static void nb_inputs(MemorySegment struct, byte fieldValue) {
        struct.set(nb_inputs$LAYOUT, nb_inputs$OFFSET, fieldValue);
    }

    private static final OfByte nb_outputs$LAYOUT = (OfByte)$LAYOUT.select(groupElement("nb_outputs"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t nb_outputs
     * }
     */
    public static final OfByte nb_outputs$layout() {
        return nb_outputs$LAYOUT;
    }

    private static final long nb_outputs$OFFSET = 45;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t nb_outputs
     * }
     */
    public static final long nb_outputs$offset() {
        return nb_outputs$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t nb_outputs
     * }
     */
    public static byte nb_outputs(MemorySegment struct) {
        return struct.get(nb_outputs$LAYOUT, nb_outputs$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t nb_outputs
     * }
     */
    public static void nb_outputs(MemorySegment struct, byte fieldValue) {
        struct.set(nb_outputs$LAYOUT, nb_outputs$OFFSET, fieldValue);
    }

    private static final OfByte formats_state$LAYOUT = (OfByte)$LAYOUT.select(groupElement("formats_state"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint8_t formats_state
     * }
     */
    public static final OfByte formats_state$layout() {
        return formats_state$LAYOUT;
    }

    private static final long formats_state$OFFSET = 46;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint8_t formats_state
     * }
     */
    public static final long formats_state$offset() {
        return formats_state$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint8_t formats_state
     * }
     */
    public static byte formats_state(MemorySegment struct) {
        return struct.get(formats_state$LAYOUT, formats_state$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint8_t formats_state
     * }
     */
    public static void formats_state(MemorySegment struct, byte fieldValue) {
        struct.set(formats_state$LAYOUT, formats_state$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * int (*preinit)(AVFilterContext *)
     * }
     */
    public static class preinit {

        preinit() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            Ffmpeg.C_INT,
            Ffmpeg.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = Ffmpeg.upcallHandle(preinit.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(preinit.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr,MemorySegment _x0) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout preinit$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("preinit"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int (*preinit)(AVFilterContext *)
     * }
     */
    public static final AddressLayout preinit$layout() {
        return preinit$LAYOUT;
    }

    private static final long preinit$OFFSET = 48;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int (*preinit)(AVFilterContext *)
     * }
     */
    public static final long preinit$offset() {
        return preinit$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int (*preinit)(AVFilterContext *)
     * }
     */
    public static MemorySegment preinit(MemorySegment struct) {
        return struct.get(preinit$LAYOUT, preinit$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int (*preinit)(AVFilterContext *)
     * }
     */
    public static void preinit(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(preinit$LAYOUT, preinit$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * int (*init)(AVFilterContext *)
     * }
     */
    public static class init {

        init() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            Ffmpeg.C_INT,
            Ffmpeg.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = Ffmpeg.upcallHandle(init.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(init.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr,MemorySegment _x0) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout init$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("init"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int (*init)(AVFilterContext *)
     * }
     */
    public static final AddressLayout init$layout() {
        return init$LAYOUT;
    }

    private static final long init$OFFSET = 56;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int (*init)(AVFilterContext *)
     * }
     */
    public static final long init$offset() {
        return init$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int (*init)(AVFilterContext *)
     * }
     */
    public static MemorySegment init(MemorySegment struct) {
        return struct.get(init$LAYOUT, init$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int (*init)(AVFilterContext *)
     * }
     */
    public static void init(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(init$LAYOUT, init$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * void (*uninit)(AVFilterContext *)
     * }
     */
    public static class uninit {

        uninit() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            void apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.ofVoid(
            Ffmpeg.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = Ffmpeg.upcallHandle(uninit.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(uninit.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static void invoke(MemorySegment funcPtr,MemorySegment _x0) {
            try {
                 DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout uninit$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("uninit"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void (*uninit)(AVFilterContext *)
     * }
     */
    public static final AddressLayout uninit$layout() {
        return uninit$LAYOUT;
    }

    private static final long uninit$OFFSET = 64;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void (*uninit)(AVFilterContext *)
     * }
     */
    public static final long uninit$offset() {
        return uninit$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void (*uninit)(AVFilterContext *)
     * }
     */
    public static MemorySegment uninit(MemorySegment struct) {
        return struct.get(uninit$LAYOUT, uninit$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void (*uninit)(AVFilterContext *)
     * }
     */
    public static void uninit(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(uninit$LAYOUT, uninit$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * union {
     *     int (*query_func)(AVFilterContext *);
     *     int (*query_func2)(const AVFilterContext *, struct AVFilterFormatsConfig **, struct AVFilterFormatsConfig **);
     *     const enum AVPixelFormat *pixels_list;
     *     const enum AVSampleFormat *samples_list;
     *     enum AVPixelFormat pix_fmt;
     *     enum AVSampleFormat sample_fmt;
     * }
     * }
     */
    public static class formats {

        formats() {
            // Should not be called directly
        }

        private static final GroupLayout $LAYOUT = MemoryLayout.unionLayout(
            Ffmpeg.C_POINTER.withName("query_func"),
            Ffmpeg.C_POINTER.withName("query_func2"),
            Ffmpeg.C_POINTER.withName("pixels_list"),
            Ffmpeg.C_POINTER.withName("samples_list"),
            Ffmpeg.C_INT.withName("pix_fmt"),
            Ffmpeg.C_INT.withName("sample_fmt")
        ).withName("$anon$325:5");

        /**
         * The layout of this union
         */
        public static final GroupLayout layout() {
            return $LAYOUT;
        }

        /**
         * {@snippet lang=c :
         * int (*query_func)(AVFilterContext *)
         * }
         */
        public static class query_func {

            query_func() {
                // Should not be called directly
            }

            /**
             * The function pointer signature, expressed as a functional interface
             */
            public interface Function {
                int apply(MemorySegment _x0);
            }

            private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
                Ffmpeg.C_INT,
                Ffmpeg.C_POINTER
            );

            /**
             * The descriptor of this function pointer
             */
            public static FunctionDescriptor descriptor() {
                return $DESC;
            }

            private static final MethodHandle UP$MH = Ffmpeg.upcallHandle(query_func.Function.class, "apply", $DESC);

            /**
             * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
             * The lifetime of the returned segment is managed by {@code arena}
             */
            public static MemorySegment allocate(query_func.Function fi, Arena arena) {
                return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
            }

            private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

            /**
             * Invoke the upcall stub {@code funcPtr}, with given parameters
             */
            public static int invoke(MemorySegment funcPtr,MemorySegment _x0) {
                try {
                    return (int) DOWN$MH.invokeExact(funcPtr, _x0);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            }
        }

        private static final AddressLayout query_func$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("query_func"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * int (*query_func)(AVFilterContext *)
         * }
         */
        public static final AddressLayout query_func$layout() {
            return query_func$LAYOUT;
        }

        private static final long query_func$OFFSET = 0;

        /**
         * Offset for field:
         * {@snippet lang=c :
         * int (*query_func)(AVFilterContext *)
         * }
         */
        public static final long query_func$offset() {
            return query_func$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * int (*query_func)(AVFilterContext *)
         * }
         */
        public static MemorySegment query_func(MemorySegment union) {
            return union.get(query_func$LAYOUT, query_func$OFFSET);
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * int (*query_func)(AVFilterContext *)
         * }
         */
        public static void query_func(MemorySegment union, MemorySegment fieldValue) {
            union.set(query_func$LAYOUT, query_func$OFFSET, fieldValue);
        }

        /**
         * {@snippet lang=c :
         * int (*query_func2)(const AVFilterContext *, struct AVFilterFormatsConfig **, struct AVFilterFormatsConfig **)
         * }
         */
        public static class query_func2 {

            query_func2() {
                // Should not be called directly
            }

            /**
             * The function pointer signature, expressed as a functional interface
             */
            public interface Function {
                int apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2);
            }

            private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
                Ffmpeg.C_INT,
                Ffmpeg.C_POINTER,
                Ffmpeg.C_POINTER,
                Ffmpeg.C_POINTER
            );

            /**
             * The descriptor of this function pointer
             */
            public static FunctionDescriptor descriptor() {
                return $DESC;
            }

            private static final MethodHandle UP$MH = Ffmpeg.upcallHandle(query_func2.Function.class, "apply", $DESC);

            /**
             * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
             * The lifetime of the returned segment is managed by {@code arena}
             */
            public static MemorySegment allocate(query_func2.Function fi, Arena arena) {
                return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
            }

            private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

            /**
             * Invoke the upcall stub {@code funcPtr}, with given parameters
             */
            public static int invoke(MemorySegment funcPtr,MemorySegment _x0, MemorySegment _x1, MemorySegment _x2) {
                try {
                    return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            }
        }

        private static final AddressLayout query_func2$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("query_func2"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * int (*query_func2)(const AVFilterContext *, struct AVFilterFormatsConfig **, struct AVFilterFormatsConfig **)
         * }
         */
        public static final AddressLayout query_func2$layout() {
            return query_func2$LAYOUT;
        }

        private static final long query_func2$OFFSET = 0;

        /**
         * Offset for field:
         * {@snippet lang=c :
         * int (*query_func2)(const AVFilterContext *, struct AVFilterFormatsConfig **, struct AVFilterFormatsConfig **)
         * }
         */
        public static final long query_func2$offset() {
            return query_func2$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * int (*query_func2)(const AVFilterContext *, struct AVFilterFormatsConfig **, struct AVFilterFormatsConfig **)
         * }
         */
        public static MemorySegment query_func2(MemorySegment union) {
            return union.get(query_func2$LAYOUT, query_func2$OFFSET);
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * int (*query_func2)(const AVFilterContext *, struct AVFilterFormatsConfig **, struct AVFilterFormatsConfig **)
         * }
         */
        public static void query_func2(MemorySegment union, MemorySegment fieldValue) {
            union.set(query_func2$LAYOUT, query_func2$OFFSET, fieldValue);
        }

        private static final AddressLayout pixels_list$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("pixels_list"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * const enum AVPixelFormat *pixels_list
         * }
         */
        public static final AddressLayout pixels_list$layout() {
            return pixels_list$LAYOUT;
        }

        private static final long pixels_list$OFFSET = 0;

        /**
         * Offset for field:
         * {@snippet lang=c :
         * const enum AVPixelFormat *pixels_list
         * }
         */
        public static final long pixels_list$offset() {
            return pixels_list$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * const enum AVPixelFormat *pixels_list
         * }
         */
        public static MemorySegment pixels_list(MemorySegment union) {
            return union.get(pixels_list$LAYOUT, pixels_list$OFFSET);
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * const enum AVPixelFormat *pixels_list
         * }
         */
        public static void pixels_list(MemorySegment union, MemorySegment fieldValue) {
            union.set(pixels_list$LAYOUT, pixels_list$OFFSET, fieldValue);
        }

        private static final AddressLayout samples_list$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("samples_list"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * const enum AVSampleFormat *samples_list
         * }
         */
        public static final AddressLayout samples_list$layout() {
            return samples_list$LAYOUT;
        }

        private static final long samples_list$OFFSET = 0;

        /**
         * Offset for field:
         * {@snippet lang=c :
         * const enum AVSampleFormat *samples_list
         * }
         */
        public static final long samples_list$offset() {
            return samples_list$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * const enum AVSampleFormat *samples_list
         * }
         */
        public static MemorySegment samples_list(MemorySegment union) {
            return union.get(samples_list$LAYOUT, samples_list$OFFSET);
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * const enum AVSampleFormat *samples_list
         * }
         */
        public static void samples_list(MemorySegment union, MemorySegment fieldValue) {
            union.set(samples_list$LAYOUT, samples_list$OFFSET, fieldValue);
        }

        private static final OfInt pix_fmt$LAYOUT = (OfInt)$LAYOUT.select(groupElement("pix_fmt"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * enum AVPixelFormat pix_fmt
         * }
         */
        public static final OfInt pix_fmt$layout() {
            return pix_fmt$LAYOUT;
        }

        private static final long pix_fmt$OFFSET = 0;

        /**
         * Offset for field:
         * {@snippet lang=c :
         * enum AVPixelFormat pix_fmt
         * }
         */
        public static final long pix_fmt$offset() {
            return pix_fmt$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * enum AVPixelFormat pix_fmt
         * }
         */
        public static int pix_fmt(MemorySegment union) {
            return union.get(pix_fmt$LAYOUT, pix_fmt$OFFSET);
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * enum AVPixelFormat pix_fmt
         * }
         */
        public static void pix_fmt(MemorySegment union, int fieldValue) {
            union.set(pix_fmt$LAYOUT, pix_fmt$OFFSET, fieldValue);
        }

        private static final OfInt sample_fmt$LAYOUT = (OfInt)$LAYOUT.select(groupElement("sample_fmt"));

        /**
         * Layout for field:
         * {@snippet lang=c :
         * enum AVSampleFormat sample_fmt
         * }
         */
        public static final OfInt sample_fmt$layout() {
            return sample_fmt$LAYOUT;
        }

        private static final long sample_fmt$OFFSET = 0;

        /**
         * Offset for field:
         * {@snippet lang=c :
         * enum AVSampleFormat sample_fmt
         * }
         */
        public static final long sample_fmt$offset() {
            return sample_fmt$OFFSET;
        }

        /**
         * Getter for field:
         * {@snippet lang=c :
         * enum AVSampleFormat sample_fmt
         * }
         */
        public static int sample_fmt(MemorySegment union) {
            return union.get(sample_fmt$LAYOUT, sample_fmt$OFFSET);
        }

        /**
         * Setter for field:
         * {@snippet lang=c :
         * enum AVSampleFormat sample_fmt
         * }
         */
        public static void sample_fmt(MemorySegment union, int fieldValue) {
            union.set(sample_fmt$LAYOUT, sample_fmt$OFFSET, fieldValue);
        }

        /**
         * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
         * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
         */
        public static MemorySegment asSlice(MemorySegment array, long index) {
            return array.asSlice(layout().byteSize() * index);
        }

        /**
         * The size (in bytes) of this union
         */
        public static long sizeof() { return layout().byteSize(); }

        /**
         * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
         */
        public static MemorySegment allocate(SegmentAllocator allocator) {
            return allocator.allocate(layout());
        }

        /**
         * Allocate an array of size {@code elementCount} using {@code allocator}.
         * The returned segment has size {@code elementCount * layout().byteSize()}.
         */
        public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
            return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
            return reinterpret(addr, 1, arena, cleanup);
        }

        /**
         * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
         * The returned segment has size {@code elementCount * layout().byteSize()}
         */
        public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
            return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
        }
    }

    private static final GroupLayout formats$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("formats"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * union {
     *     int (*query_func)(AVFilterContext *);
     *     int (*query_func2)(const AVFilterContext *, struct AVFilterFormatsConfig **, struct AVFilterFormatsConfig **);
     *     const enum AVPixelFormat *pixels_list;
     *     const enum AVSampleFormat *samples_list;
     *     enum AVPixelFormat pix_fmt;
     *     enum AVSampleFormat sample_fmt;
     * } formats
     * }
     */
    public static final GroupLayout formats$layout() {
        return formats$LAYOUT;
    }

    private static final long formats$OFFSET = 72;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * union {
     *     int (*query_func)(AVFilterContext *);
     *     int (*query_func2)(const AVFilterContext *, struct AVFilterFormatsConfig **, struct AVFilterFormatsConfig **);
     *     const enum AVPixelFormat *pixels_list;
     *     const enum AVSampleFormat *samples_list;
     *     enum AVPixelFormat pix_fmt;
     *     enum AVSampleFormat sample_fmt;
     * } formats
     * }
     */
    public static final long formats$offset() {
        return formats$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * union {
     *     int (*query_func)(AVFilterContext *);
     *     int (*query_func2)(const AVFilterContext *, struct AVFilterFormatsConfig **, struct AVFilterFormatsConfig **);
     *     const enum AVPixelFormat *pixels_list;
     *     const enum AVSampleFormat *samples_list;
     *     enum AVPixelFormat pix_fmt;
     *     enum AVSampleFormat sample_fmt;
     * } formats
     * }
     */
    public static MemorySegment formats(MemorySegment struct) {
        return struct.asSlice(formats$OFFSET, formats$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * union {
     *     int (*query_func)(AVFilterContext *);
     *     int (*query_func2)(const AVFilterContext *, struct AVFilterFormatsConfig **, struct AVFilterFormatsConfig **);
     *     const enum AVPixelFormat *pixels_list;
     *     const enum AVSampleFormat *samples_list;
     *     enum AVPixelFormat pix_fmt;
     *     enum AVSampleFormat sample_fmt;
     * } formats
     * }
     */
    public static void formats(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, formats$OFFSET, formats$LAYOUT.byteSize());
    }

    private static final OfInt priv_size$LAYOUT = (OfInt)$LAYOUT.select(groupElement("priv_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int priv_size
     * }
     */
    public static final OfInt priv_size$layout() {
        return priv_size$LAYOUT;
    }

    private static final long priv_size$OFFSET = 80;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int priv_size
     * }
     */
    public static final long priv_size$offset() {
        return priv_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int priv_size
     * }
     */
    public static int priv_size(MemorySegment struct) {
        return struct.get(priv_size$LAYOUT, priv_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int priv_size
     * }
     */
    public static void priv_size(MemorySegment struct, int fieldValue) {
        struct.set(priv_size$LAYOUT, priv_size$OFFSET, fieldValue);
    }

    private static final OfInt flags_internal$LAYOUT = (OfInt)$LAYOUT.select(groupElement("flags_internal"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int flags_internal
     * }
     */
    public static final OfInt flags_internal$layout() {
        return flags_internal$LAYOUT;
    }

    private static final long flags_internal$OFFSET = 84;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int flags_internal
     * }
     */
    public static final long flags_internal$offset() {
        return flags_internal$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int flags_internal
     * }
     */
    public static int flags_internal(MemorySegment struct) {
        return struct.get(flags_internal$LAYOUT, flags_internal$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int flags_internal
     * }
     */
    public static void flags_internal(MemorySegment struct, int fieldValue) {
        struct.set(flags_internal$LAYOUT, flags_internal$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * int (*process_command)(AVFilterContext *, const char *, const char *, char *, int, int)
     * }
     */
    public static class process_command {

        process_command() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, MemorySegment _x3, int _x4, int _x5);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            Ffmpeg.C_INT,
            Ffmpeg.C_POINTER,
            Ffmpeg.C_POINTER,
            Ffmpeg.C_POINTER,
            Ffmpeg.C_POINTER,
            Ffmpeg.C_INT,
            Ffmpeg.C_INT
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = Ffmpeg.upcallHandle(process_command.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(process_command.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr,MemorySegment _x0, MemorySegment _x1, MemorySegment _x2, MemorySegment _x3, int _x4, int _x5) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0, _x1, _x2, _x3, _x4, _x5);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout process_command$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("process_command"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int (*process_command)(AVFilterContext *, const char *, const char *, char *, int, int)
     * }
     */
    public static final AddressLayout process_command$layout() {
        return process_command$LAYOUT;
    }

    private static final long process_command$OFFSET = 88;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int (*process_command)(AVFilterContext *, const char *, const char *, char *, int, int)
     * }
     */
    public static final long process_command$offset() {
        return process_command$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int (*process_command)(AVFilterContext *, const char *, const char *, char *, int, int)
     * }
     */
    public static MemorySegment process_command(MemorySegment struct) {
        return struct.get(process_command$LAYOUT, process_command$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int (*process_command)(AVFilterContext *, const char *, const char *, char *, int, int)
     * }
     */
    public static void process_command(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(process_command$LAYOUT, process_command$OFFSET, fieldValue);
    }

    /**
     * {@snippet lang=c :
     * int (*activate)(AVFilterContext *)
     * }
     */
    public static class activate {

        activate() {
            // Should not be called directly
        }

        /**
         * The function pointer signature, expressed as a functional interface
         */
        public interface Function {
            int apply(MemorySegment _x0);
        }

        private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
            Ffmpeg.C_INT,
            Ffmpeg.C_POINTER
        );

        /**
         * The descriptor of this function pointer
         */
        public static FunctionDescriptor descriptor() {
            return $DESC;
        }

        private static final MethodHandle UP$MH = Ffmpeg.upcallHandle(activate.Function.class, "apply", $DESC);

        /**
         * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
         * The lifetime of the returned segment is managed by {@code arena}
         */
        public static MemorySegment allocate(activate.Function fi, Arena arena) {
            return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
        }

        private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

        /**
         * Invoke the upcall stub {@code funcPtr}, with given parameters
         */
        public static int invoke(MemorySegment funcPtr,MemorySegment _x0) {
            try {
                return (int) DOWN$MH.invokeExact(funcPtr, _x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        }
    }

    private static final AddressLayout activate$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("activate"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int (*activate)(AVFilterContext *)
     * }
     */
    public static final AddressLayout activate$layout() {
        return activate$LAYOUT;
    }

    private static final long activate$OFFSET = 96;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int (*activate)(AVFilterContext *)
     * }
     */
    public static final long activate$offset() {
        return activate$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int (*activate)(AVFilterContext *)
     * }
     */
    public static MemorySegment activate(MemorySegment struct) {
        return struct.get(activate$LAYOUT, activate$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int (*activate)(AVFilterContext *)
     * }
     */
    public static void activate(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(activate$LAYOUT, activate$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

