// Generated by jextract

package com.github.auties00.cobalt.util.ffmpeg;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct AVOptionRanges {
 *     AVOptionRange **range;
 *     int nb_ranges;
 *     int nb_components;
 * }
 * }
 */
public class AVOptionRanges {

    AVOptionRanges() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        Ffmpeg.C_POINTER.withName("range"),
        Ffmpeg.C_INT.withName("nb_ranges"),
        Ffmpeg.C_INT.withName("nb_components")
    ).withName("AVOptionRanges");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout range$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("range"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * AVOptionRange **range
     * }
     */
    public static final AddressLayout range$layout() {
        return range$LAYOUT;
    }

    private static final long range$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * AVOptionRange **range
     * }
     */
    public static final long range$offset() {
        return range$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * AVOptionRange **range
     * }
     */
    public static MemorySegment range(MemorySegment struct) {
        return struct.get(range$LAYOUT, range$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * AVOptionRange **range
     * }
     */
    public static void range(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(range$LAYOUT, range$OFFSET, fieldValue);
    }

    private static final OfInt nb_ranges$LAYOUT = (OfInt)$LAYOUT.select(groupElement("nb_ranges"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int nb_ranges
     * }
     */
    public static final OfInt nb_ranges$layout() {
        return nb_ranges$LAYOUT;
    }

    private static final long nb_ranges$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int nb_ranges
     * }
     */
    public static final long nb_ranges$offset() {
        return nb_ranges$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int nb_ranges
     * }
     */
    public static int nb_ranges(MemorySegment struct) {
        return struct.get(nb_ranges$LAYOUT, nb_ranges$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int nb_ranges
     * }
     */
    public static void nb_ranges(MemorySegment struct, int fieldValue) {
        struct.set(nb_ranges$LAYOUT, nb_ranges$OFFSET, fieldValue);
    }

    private static final OfInt nb_components$LAYOUT = (OfInt)$LAYOUT.select(groupElement("nb_components"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int nb_components
     * }
     */
    public static final OfInt nb_components$layout() {
        return nb_components$LAYOUT;
    }

    private static final long nb_components$OFFSET = 12;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int nb_components
     * }
     */
    public static final long nb_components$offset() {
        return nb_components$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int nb_components
     * }
     */
    public static int nb_components(MemorySegment struct) {
        return struct.get(nb_components$LAYOUT, nb_components$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int nb_components
     * }
     */
    public static void nb_components(MemorySegment struct, int fieldValue) {
        struct.set(nb_components$LAYOUT, nb_components$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

