package com.github.auties00.cobalt.wire.linked.message.call;

import com.github.auties00.cobalt.wire.linked.message.Message;

import it.auties.protobuf.annotation.*;
import it.auties.protobuf.model.*;
import java.util.Optional;

/**
 * A message that represents a business call event exchanged between a user and a WhatsApp Business account.
 *
 * <p>Business calls use a dedicated signalling channel that differs from regular one-to-one calls
 * and carry additional metadata such as a session identifier, the negotiated media type and an
 * optional caption shown to the recipient. The {@code masterKey} field holds the key material used
 * to derive the end-to-end encryption keys that protect the call's audio and video streams.
 *
 * <p>Instances of this class are typically produced by the library when a business call is
 * initiated or received. All fields are optional because the server may omit parts of the payload
 * depending on the call lifecycle stage.
 */
@ProtobufMessage(name = "Message.BCallMessage")
public final class BCallMessage implements Message {
    /**
     * Unique identifier assigned to the business call session.
     *
     * <p>The session id is used to correlate signalling events, ringing notifications and call log
     * entries that belong to the same call. It is generated by the server and shared between the
     * caller and the callee.
     */
    @ProtobufProperty(index = 1, type = ProtobufType.STRING)
    String sessionId;

    /**
     * Type of media negotiated for the business call.
     *
     * <p>Indicates whether the call is an audio only call or a video call. The value may be
     * {@link MediaType#UNKNOWN} when the media type has not yet been negotiated.
     */
    @ProtobufProperty(index = 2, type = ProtobufType.ENUM)
    MediaType mediaType;

    /**
     * Raw key material used to derive the end-to-end encryption keys for the call.
     *
     * <p>The master key is exchanged during the call setup handshake and must be kept confidential.
     * It is consumed by the Signal based key derivation routines that protect the call's media
     * streams.
     */
    @ProtobufProperty(index = 3, type = ProtobufType.BYTES)
    byte[] masterKey;

    /**
     * Optional caption shown to the recipient when the business call is received.
     *
     * <p>Business accounts may attach a short descriptive text that is displayed alongside the
     * incoming call notification, typically explaining the purpose of the call.
     */
    @ProtobufProperty(index = 4, type = ProtobufType.STRING)
    String caption;

    /**
     * Constructs a new business call message with the given session identifier, media type,
     * encryption master key and caption.
     *
     * <p>This constructor is package-private: use the generated {@code BCallMessageBuilder} to
     * create instances.
     *
     * @param sessionId the unique identifier of the business call session, may be {@code null}
     * @param mediaType the media type negotiated for the call, may be {@code null}
     * @param masterKey the raw master key used to derive the call's encryption keys, may be {@code null}
     * @param caption   the caption shown to the recipient on the incoming call screen, may be {@code null}
     */
    BCallMessage(String sessionId, MediaType mediaType, byte[] masterKey, String caption) {
        this.sessionId = sessionId;
        this.mediaType = mediaType;
        this.masterKey = masterKey;
        this.caption = caption;
    }

    /**
     * Returns the identifier of the business call session this message refers to.
     *
     * @return an {@link Optional} containing the session identifier, or empty if not set
     */
    public Optional<String> sessionId() {
        return Optional.ofNullable(sessionId);
    }

    /**
     * Returns the media type negotiated for the business call.
     *
     * @return an {@link Optional} containing the {@link MediaType}, or empty if not set
     */
    public Optional<MediaType> mediaType() {
        return Optional.ofNullable(mediaType);
    }

    /**
     * Returns the raw master key used to derive the encryption keys protecting the call's media streams.
     *
     * @return an {@link Optional} containing the master key bytes, or empty if not set
     */
    public Optional<byte[]> masterKey() {
        return Optional.ofNullable(masterKey);
    }

    /**
     * Returns the caption displayed to the recipient when the business call is received.
     *
     * @return an {@link Optional} containing the caption, or empty if no caption was supplied
     */
    public Optional<String> caption() {
        return Optional.ofNullable(caption);
    }

    /**
     * Sets the identifier of the business call session this message refers to.
     *
     * @param sessionId the session identifier, or {@code null} to clear the field
     */
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * Sets the media type negotiated for the business call.
     *
     * @param mediaType the {@link MediaType}, or {@code null} to clear the field
     */
    public void setMediaType(MediaType mediaType) {
        this.mediaType = mediaType;
    }

    /**
     * Sets the raw master key used to derive the encryption keys for the call's media streams.
     *
     * @param masterKey the master key bytes, or {@code null} to clear the field
     */
    public void setMasterKey(byte[] masterKey) {
        this.masterKey = masterKey;
    }

    /**
     * Sets the caption displayed to the recipient on the incoming call screen.
     *
     * @param caption the caption text, or {@code null} to clear the field
     */
    public void setCaption(String caption) {
        this.caption = caption;
    }

    /**
     * Describes the kind of media carried by a business call.
     *
     * <p>Used by {@link BCallMessage} to signal whether a call is audio only or also includes a
     * video stream. The {@link #UNKNOWN} value is used when the media type has not been set or is
     * not recognised by this version of the client.
     */
    @ProtobufEnum(name = "Message.BCallMessage.MediaType")
    public static enum MediaType {
        /**
         * The media type is not specified or is not recognised by this client.
         */
        UNKNOWN(0),
        /**
         * The business call carries only an audio stream.
         */
        AUDIO(1),
        /**
         * The business call carries both an audio and a video stream.
         */
        VIDEO(2);

        /**
         * Creates a media type constant with the given protobuf index.
         *
         * @param index the wire value assigned to this constant by the protobuf schema
         */
        MediaType(@ProtobufEnumIndex int index) {
            this.index = index;
        }

        /**
         * Wire value assigned to this constant by the protobuf schema.
         */
        final int index;

        /**
         * Returns the wire value of this constant.
         *
         * @return the protobuf index of this enum constant
         */
        public int index() {
            return this.index;
        }
    }
}
