package com.github.auties00.cobalt.calls.media.audio.codec.mlow;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Base64;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * C-oracle golden for the MLow 60 ms SID / discontinuous-transmission encode path. The golden
 * ({@code fixtures/call/mlow/encode/mlow-sid-60ms.json}, regenerated by {@code generate_mlow_sid_golden.py})
 * is the raw {@code smpl_Encode} packet stream the reference {@code smpl_codec} harness produced from
 * {@code libopus.a} for a fixed input at 16 kHz mono, 9600 bps, complexity 9, 60 ms packets, with DTX on:
 * fifteen packets of a deterministic two-sine plus LCG-dither active lead-in followed by twenty-five packets
 * of silence.
 *
 * <p>Each golden {@code packets} entry is one of three forms. An empty string is a non-transmitted silence
 * frame the encoder suppressed ({@code smpl_Encode} returning zero bytes). A hex string is a SID
 * comfort-noise packet (TOC byte plus range-coded payload). The literal {@value #ACTIVE_MARKER} is a
 * transmitted active or hangover packet whose bytes are deliberately not carried: the reference C harness's
 * CELP analysis-by-synthesis reads ASLR-dependent uninitialized scratch inside libopus and is not
 * byte-deterministic across runs, so only the transmit/drop schedule and the silence-driven SID packets are
 * a stable oracle. Active-voice byte-exactness is covered separately by the self-referential
 * {@code MlowBitIdentityTest}.
 *
 * <p>The test drives the same input through {@link MlowEncoder} with DTX enabled and, per packet, asserts the
 * transmit-versus-drop decision against the golden and the SID comfort-noise packets byte-for-byte, while an
 * active packet is only required to be transmitted. A green run proves the DTX-specific chain (the SID
 * comfort-noise candidate selection, the SID-interval send schedule, and the suppressed-frame drops) is
 * bit-identical to the C reference; a failure names the packet and its TOC byte so the divergence is
 * localized. The input is carried in the golden rather than regenerated so the C harness and this test encode
 * exactly the same samples with no cross-language transcendental-function drift.
 */
@DisplayName("MLow 60 ms SID/DTX C-oracle golden")
class MlowSidGoldenTest {
    /**
     * Classpath location of the golden produced by the {@code smpl_codec} harness.
     */
    private static final String RESOURCE = "fixtures/call/mlow/encode/mlow-sid-60ms.json";

    /**
     * The golden entry for a transmitted active or hangover packet whose bytes are not asserted (the C
     * reference CELP is not byte-deterministic); only that the frame is transmitted is checked.
     */
    private static final String ACTIVE_MARKER = "*";

    /**
     * Samples in one 60 ms packet at 16 kHz mono, the {@link MlowEncoder} 60 ms input span.
     */
    private static final int PACKET_SAMPLES = 960;

    /**
     * Target bitrate the golden was encoded at, the high-rate 9600 bps path.
     */
    private static final int BITRATE = 9600;

    @Test
    @DisplayName("encoding the golden input with DTX reproduces the C oracle SID packet stream byte-for-byte")
    void sidStreamMatchesOracle() {
        var json = loadResource();
        var pcm = decodePcmLittleEndian(Base64.getDecoder().decode(stringField(json, "inputPcmBase64")));
        var expected = stringArray(json, "packets");
        assertEquals(0, pcm.length % PACKET_SAMPLES, "golden input must be a whole number of 60 ms packets");
        var packets = pcm.length / PACKET_SAMPLES;
        assertEquals(expected.size(), packets, "golden packet count matches the input length");

        var encoder = new MlowEncoder(BITRATE, true);
        for (var p = 0; p < packets; p++) {
            var chunk = Arrays.copyOfRange(pcm, p * PACKET_SAMPLES, (p + 1) * PACKET_SAMPLES);
            var got = encoder.encode(chunk);
            var golden = expected.get(p);
            var tocHint = got.length > 0 ? String.format("0x%02x", got[0] & 0xFF) : "drop";
            if (ACTIVE_MARKER.equals(golden)) {
                assertTrue(got.length > 0, "packet " + p + " (" + tocHint + ") must be transmitted (active)");
            } else {
                assertEquals(golden, toHex(got), "packet " + p + " (" + tocHint + ")");
            }
        }
    }

    /**
     * Reads the golden resource into a string.
     *
     * @return the golden JSON text
     */
    private static String loadResource() {
        var loader = MlowSidGoldenTest.class.getClassLoader();
        try (InputStream in = loader.getResourceAsStream(RESOURCE)) {
            if (in == null) {
                throw new UncheckedIOException(new IOException("resource not found: " + RESOURCE));
            }
            return new String(in.readAllBytes(), StandardCharsets.UTF_8);
        } catch (IOException exception) {
            throw new UncheckedIOException(exception);
        }
    }

    /**
     * Reads a top-level JSON string field whose value contains no escapes (a base64 blob).
     *
     * @param json the JSON text
     * @param key  the field name
     * @return the field value
     */
    private static String stringField(String json, String key) {
        var marker = "\"" + key + "\":\"";
        var start = json.indexOf(marker);
        if (start < 0) {
            throw new IllegalArgumentException("missing field: " + key);
        }
        start += marker.length();
        var end = json.indexOf('"', start);
        return json.substring(start, end);
    }

    /**
     * Reads a top-level JSON array of escape-free strings (hex packet bytes, empty for a dropped frame).
     *
     * @param json the JSON text
     * @param key  the array field name
     * @return the array elements in order
     */
    private static List<String> stringArray(String json, String key) {
        var marker = "\"" + key + "\":[";
        var pos = json.indexOf(marker);
        if (pos < 0) {
            throw new IllegalArgumentException("missing array: " + key);
        }
        pos += marker.length();
        var out = new ArrayList<String>();
        while (pos < json.length()) {
            var c = json.charAt(pos);
            if (c == ']') {
                break;
            }
            if (c == '"') {
                var end = json.indexOf('"', pos + 1);
                out.add(json.substring(pos + 1, end));
                pos = end + 1;
            } else {
                pos++;
            }
        }
        return out;
    }

    /**
     * Decodes little-endian {@code int16} PCM bytes into samples.
     *
     * @param bytes the little-endian sample bytes
     * @return the samples
     */
    private static short[] decodePcmLittleEndian(byte[] bytes) {
        var samples = new short[bytes.length / 2];
        var buffer = ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN);
        for (var i = 0; i < samples.length; i++) {
            samples[i] = buffer.getShort();
        }
        return samples;
    }

    /**
     * Renders bytes as lowercase hex; an empty array yields the empty string, matching the golden's
     * representation of a dropped frame.
     *
     * @param bytes the packet bytes
     * @return the lowercase hex string
     */
    private static String toHex(byte[] bytes) {
        var sb = new StringBuilder(bytes.length * 2);
        for (var b : bytes) {
            sb.append(Character.forDigit((b >> 4) & 0xF, 16));
            sb.append(Character.forDigit(b & 0xF, 16));
        }
        return sb.toString();
    }
}
