package com.github.auties00.cobalt.calls.media.audio.neteq;

import com.github.auties00.cobalt.calls.media.audio.pipeline.AudioDecoderReceiver;
import com.github.auties00.cobalt.calls.stream.AudioFrame;
import com.github.auties00.cobalt.telemetry.log.Log;

import java.lang.System.Logger.Level;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.concurrent.locks.ReentrantLock;
import com.github.auties00.cobalt.calls.media.audio.neteq.decoder.ComfortNoiseDecoder;
import com.github.auties00.cobalt.calls.media.audio.neteq.decoder.DtmfDecoder;
import com.github.auties00.cobalt.calls.media.audio.neteq.NetEqExpand;
import com.github.auties00.cobalt.calls.media.audio.neteq.NetEqMerge;
import com.github.auties00.cobalt.calls.media.audio.neteq.NetEqSignalProcessing;
import com.github.auties00.cobalt.calls.media.audio.neteq.NetEqSyncBuffer;
import com.github.auties00.cobalt.calls.media.audio.neteq.NetEqTimeStretch;
import com.github.auties00.cobalt.calls.media.video.jitter.AvSyncFeedback;
import com.github.auties00.cobalt.calls.media.video.jitter.AvSyncFeedbackSink;

/**
 * The production adaptive audio jitter buffer, composing the packet store, delay estimator, decision
 * logic, NACK tracker, and decoder seam into one smooth playout stage.
 *
 * <p>Received packets enter through {@link #insertPacket(RtpAudioPacket)} (or the equivalent
 * {@link #insert(int, long, byte[])} seam method), which buffers them in the {@link PacketBuffer}, feeds
 * their arrival timing to the {@link DelayManager}, and records their sequence gaps in the
 * {@link NackTracker}. The playback pull, {@link #getAudio()}, asks the {@link DecisionLogic} for the next
 * {@link NetEqOperation} from the buffer level against the delay target, then renders exactly one frame:
 * decoding the scheduled packet, reconstructing a lost frame from a following packet's in band forward
 * error correction, concealing through the codec or the built in expander, or generating comfort noise.
 * Each buffered packet's RTP payload type is resolved against the payload type role registry that
 * {@link #registerComfortNoisePayloadType(int)} and {@link #registerTelephoneEventPayloadType(int)}
 * populate, so a comfort noise (RFC 3389) payload type drives {@link NetEqOperation#RFC3389_CNG} and a
 * telephone event payload type drives {@link NetEqOperation#DTMF}. The lifetime operation counts
 * accumulate into {@link NetEqStatistics} for telemetry.
 *
 * <p>{@link #getAudio()} decodes or conceals the frame through the
 * {@link AudioDecoderReceiver.FrameDecoder} codec seam (and through the {@link ComfortNoiseDecoder} and
 * {@link DtmfDecoder} pseudo decoders for a comfort noise or telephone event payload type), pushes the
 * decoded samples into the {@link #syncBuffer}, and serves one get period frame from that history. A codec
 * packet that decodes to several get period frames (the sixty millisecond MLow packet decodes to nine
 * hundred and sixty samples, three frames) is therefore served one frame per pull from the
 * {@link #syncBuffer}, running no fresh decision and no decode until the decoded span is drained, with no
 * separate remainder buffer. The {@link AudioDecoderReceiver} the playback pump pulls from is a thin
 * adapter over {@link #getAudio()}; it copies the served frame into the pump's scratch array and reads the
 * per frame voice activity verdict back through {@link #lastFrameVoiceActive()}, which the
 * {@link AudioDecoderReceiver.FrameDecoder} reports for a normal decode.
 *
 * <p>WhatsApp negotiates only a single Opus audio payload type on the wire
 * ({@code <audio enc="opus" rate="...">}), with no RFC 3389 comfort noise line and no RFC 4733 telephone
 * event line, so for a WhatsApp call no payload type is registered as comfort noise or telephone event and
 * the {@link NetEqOperation#RFC3389_CNG} and {@link NetEqOperation#DTMF} branches stay inert. WhatsApp's
 * comfort noise is codec internal (Opus discontinuous transmission): a frame that produced no codec bytes
 * is the zero length payload {@link RtpAudioPacket} models, and codec internal comfort noise
 * ({@link NetEqOperation#CODEC_INTERNAL_CNG}) is generated by the Opus decoder itself rather than by a
 * separate decision branch, because detecting an Opus discontinuous transmission frame requires the codec,
 * which the {@link AudioDecoderReceiver.FrameDecoder} seam does not yet expose.
 *
 * <p>Concurrency follows the smooth playout design: a single {@link ReentrantLock} serializes insert
 * against pull, since both mutate the shared packet store and estimators; the lock is held only for the
 * bookkeeping, not across the native decode, which runs on the pull thread alone. The delay setters and
 * avsync ingestion take the same lock.
 *
 * @implNote This implementation serializes insert against pull with the {@link ReentrantLock}, matching
 * the Cobalt virtual thread blocking model. The avsync correction biases the delay manager offset. The
 * mean wait time accumulator is reproduced through the per pull tick timer and the per packet insertion
 * stamp (see {@link #recordWaitTime(int)}). The WSOLA merge, accelerate, and preemptive expand time
 * stretch operations are ported in {@link NetEqTimeStretch} and {@link NetEqMerge} and applied to the
 * decoded audio on the {@link #getAudio()} render path, lengthening, shortening, or cross fading it over
 * the decoded PCM {@link #syncBuffer} history. The built in autoregressive concealment is ported in
 * {@link NetEqExpand} and runs over the {@link #syncBuffer} history on the {@link NetEqOperation#EXPAND}
 * and {@link NetEqOperation#CODEC_PLC} render arm, except when the codec advertises its own loss
 * concealment and the configuration prefers it (see {@link #renderExpand(InternalDecision, int)}). The
 * whole decoded packet is written into the {@link #syncBuffer} and one get period block is read from it per
 * call, so a multi frame MLow decode is served across three pulls from the one history rather than through
 * a separate remainder buffer. The comfort noise and telephone event dispatch is data driven from the
 * payload type registry rather than hardwired.
 */
public final class LiveNetEq implements AudioDecoderReceiver.NetEqAudioSource, AvSyncFeedbackSink {
    /**
     * The logger for {@link LiveNetEq}.
     */
    private static final System.Logger LOGGER = Log.get(LiveNetEq.class);

    /**
     * The call audio sample rate in hertz, fixed at 16 kHz mono to match the public call audio format.
     *
     * <p>Combined with the get period it sets the rendered frame's sample count.
     */
    public static final int SAMPLE_RATE_HZ = 16_000;

    /**
     * The RTP payload type the {@link #insert(int, long, byte[])} receive path entry point tags every
     * inserted packet with, the speech codec role.
     *
     * <p>The {@link #insert(int, long, byte[])} entry point does not carry the wire payload type, so it tags
     * each packet with this speech role. A WhatsApp call negotiates a single Opus audio payload type, so
     * every inserted packet is a speech packet; the value is a role marker for the registry, not the
     * negotiated wire payload type.
     */
    public static final int SPEECH_PAYLOAD_TYPE = 0;

    /**
     * The sample capacity of the decoded PCM output history, in samples.
     *
     * <p>Sized to hold the longest codec packet (the sixty millisecond MLow packet, nine hundred and sixty
     * samples at sixteen kilohertz) plus the lookback the expand and merge operations correlate over (one
     * hundred and twenty milliseconds). The window holds roughly two hundred milliseconds of recent rendered
     * audio.
     */
    private static final int SYNC_BUFFER_SAMPLES = SAMPLE_RATE_HZ / 1000 * 210;

    /**
     * The history lookback prepended to a decoded frame for the time stretch analysis, in samples.
     *
     * <p>Sized so the history and frame analysis buffer is long enough for the four kilohertz decimation to
     * produce the full {@link NetEqTimeStretch#ANALYSIS_WINDOW} pitch search window (the sixteen kilohertz to
     * four kilohertz decimation needs roughly four hundred and forty input samples), while staying short
     * enough that the splice peak window acts on the boundary between recent history and the new frame.
     * Thirty milliseconds at sixteen kilohertz.
     */
    private static final int STRETCH_LOOKBACK_SAMPLES = SAMPLE_RATE_HZ / 1000 * 30;

    /**
     * The configuration governing every estimator, bound, and behavioural switch.
     */
    private final NetEqConfig config;

    /**
     * The number of audio channels the rendered frame carries, fixed at mono for the public call format.
     *
     * <p>The {@link AudioDecoderReceiver.FrameDecoder} seam does not report a channel count, so the geometry
     * is fixed here to the single sixteen kilohertz mono channel a WhatsApp call negotiates; every estimator
     * and pseudo decoder is sized to it.
     */
    private static final int CHANNELS = 1;

    /**
     * The codec decode and conceal seam {@link #getAudio()} renders a speech frame through.
     *
     * <p>A normal decode returns the packet's decoded PCM and its voice activity verdict
     * ({@link AudioDecoderReceiver.DecodedFrame#voiceActive()}); a concealment returns the codec's own packet
     * loss concealment samples with no input packet. The verdict of the last normal decode is held in
     * {@link #lastFrameVoiceActive} so the playback adapter can read it.
     */
    private final AudioDecoderReceiver.FrameDecoder decoder;

    /**
     * The comfort noise pseudo decoder the direct {@link #getAudio()} path renders an
     * {@link NetEqOperation#RFC3389_CNG} frame through.
     *
     * <p>Reached only when a payload type is registered as comfort noise through
     * {@link #registerComfortNoisePayloadType(int)}; inert for a WhatsApp call, which negotiates no RFC 3389
     * comfort noise payload type.
     */
    private final ComfortNoiseDecoder comfortNoiseDecoder;

    /**
     * The telephone event pseudo decoder the direct {@link #getAudio()} path renders an
     * {@link NetEqOperation#DTMF} frame through.
     *
     * <p>Reached only when a payload type is registered as a telephone event through
     * {@link #registerTelephoneEventPayloadType(int)}; inert for a WhatsApp call, which negotiates no RFC
     * 4733 telephone event payload type.
     */
    private final DtmfDecoder dtmfDecoder;

    /**
     * The RTP payload types resolved to the RFC 3389 comfort noise role.
     *
     * <p>Populated by {@link #registerComfortNoisePayloadType(int)} and consulted on each buffered packet's
     * payload type. Empty for a WhatsApp call, which negotiates a single Opus payload type and no separate
     * comfort noise payload type.
     */
    private final Set<Integer> comfortNoisePayloadTypes;

    /**
     * The RTP payload types resolved to the RFC 4733 telephone event (DTMF) role.
     *
     * <p>Populated by {@link #registerTelephoneEventPayloadType(int)} and consulted on each buffered packet's
     * payload type. Empty for a WhatsApp call, which negotiates no telephone event payload type.
     */
    private final Set<Integer> telephoneEventPayloadTypes;

    /**
     * Whether the most recently extracted packet carried a comfort noise payload type, so a subsequent empty
     * buffer is a comfort noise gap rather than a loss.
     *
     * <p>Drives {@link DecisionLogic.Input#comfortNoiseActive()}: when the buffer is empty and this flag is
     * set, the decision logic chooses {@link NetEqOperation#RFC3389_CNG}. Cleared whenever a packet that is
     * not comfort noise is extracted and on {@link #flush()}. Always {@code false} for a WhatsApp call, which
     * registers no comfort noise payload type.
     */
    private boolean lastDecodedComfortNoise;

    /**
     * The ordered packet store the decision logic peeks and extracts from.
     */
    private final PacketBuffer packetBuffer;

    /**
     * The target level estimator the decision logic compares the buffer span against.
     */
    private final DelayManager delayManager;

    /**
     * The operation chooser driving the per pull decode or conceal decision.
     */
    private final DecisionLogic decisionLogic;

    /**
     * The NACK tracker producing the retransmission request list.
     */
    private final NackTracker nackTracker;

    /**
     * The decoded PCM output history the time stretch and concealment operations splice over, and the queue
     * the served get period frame is drawn from.
     *
     * <p>Every frame {@link #getAudio()} decodes or conceals is pushed here through
     * {@link #render(InternalDecision, int)} so the recent rendered audio is available for a lag search and an
     * overlap add; the served frame is then read out of the same history through
     * {@link NetEqSyncBuffer#getNextAudioInterleaved(short[], int)}. Because the whole decode is pushed, a
     * codec packet that decodes to several get period frames (the sixty millisecond MLow packet) leaves the
     * extra frames as the unplayed span here, and the next pulls serve them without a fresh decision or
     * decode, so this history doubles as the multi frame output queue.
     */
    private final NetEqSyncBuffer syncBuffer;

    /**
     * The autoregressive packet loss concealment driver the direct {@link #getAudio()} path extrapolates a
     * lost frame with when the codec's own loss concealment is not preferred.
     *
     * <p>Driven from the {@link #syncBuffer} history on the {@link NetEqOperation#EXPAND} and
     * {@link NetEqOperation#CODEC_PLC} render arm when {@link #decoderAdvertisesPlc()} reports the codec does
     * not advertise its own concealment; analyzed on the first frame of a concealment run and reset on
     * {@link #flush()}. Notified of every decoded, time stretched, or merged frame through
     * {@link NetEqExpand#notifyDecoded()} so the next concealment starts a fresh analysis.
     */
    private final NetEqExpand expand;

    /**
     * The reusable decode buffer the {@link NetEqOperation#NORMAL} render arm decodes each packet into before
     * appending it to the {@link #syncBuffer}.
     *
     * <p>A steady decode writes the packet's PCM into this buffer and the {@link #syncBuffer} then copies the
     * produced prefix into its history, so no fresh per frame PCM array is allocated and discarded. Sized to
     * the largest packet the codec decodes to (a 60 ms MLow packet yields three get period frames) and
     * confined to the single pull thread the render path runs on; grown lazily by {@link #decodeScratch(int)}
     * when a wider frame geometry is first seen.
     */
    private short[] decodeScratch;

    /**
     * The lock serializing insert against pull.
     */
    private final ReentrantLock lock;

    /**
     * The lifetime count of frames rendered by {@link NetEqOperation#NORMAL}.
     */
    private long normalFrames;

    /**
     * The lifetime count of concealment frames from {@link NetEqOperation#EXPAND} and
     * {@link NetEqOperation#CODEC_PLC}.
     */
    private long expandedFrames;

    /**
     * The lifetime count of frames time compressed by accelerate operations.
     */
    private long acceleratedFrames;

    /**
     * The lifetime count of frames time stretched by {@link NetEqOperation#PREEMPTIVE_EXPAND}.
     */
    private long preemptiveExpandedFrames;

    /**
     * The lifetime count of frames cross faded by {@link NetEqOperation#MERGE}.
     */
    private long mergedFrames;

    /**
     * The lifetime count of comfort noise frames.
     */
    private long comfortNoiseFrames;

    /**
     * The operation chosen on the previous pull, distinguishing a fresh decode from a post concealment merge.
     */
    private NetEqOperation lastOperation;

    /**
     * Whether the most recently decoded packet was judged voice active, the verdict {@link #getAudio()}
     * serves to the playback adapter.
     *
     * <p>Set from the {@link AudioDecoderReceiver.DecodedFrame#voiceActive()} of a normal decode or time
     * stretch decode of a real packet, and cleared for a concealment, forward error correction
     * reconstruction, comfort noise, or silence frame. Only {@link #render(InternalDecision, int)} updates it,
     * and only when a fresh decision is rendered; while the extra frames of a multi frame packet are served
     * from the {@link #syncBuffer}, no render runs and the verdict is held, so all three frames of one MLow
     * packet report that packet's single voice activity decision. Written only on the pull thread in
     * {@link #render(InternalDecision, int)} and read through {@link #lastFrameVoiceActive()}; {@code volatile}
     * so a metering reader on another thread sees the latest verdict without taking the bookkeeping lock.
     */
    private volatile boolean lastFrameVoiceActive;

    /**
     * The signed avsync delay correction in milliseconds, biasing the target level for lip sync.
     */
    private int avSyncCorrectionMillis;

    /**
     * The presentation timestamp of the next rendered frame in microseconds, advanced one frame per pull.
     */
    private long nextPtsMicros;

    /**
     * The mutable lower bound on the target playout delay, seeded from the configuration.
     */
    private int minimumDelayMillis;

    /**
     * The mutable upper bound on the target playout delay, seeded from the configuration.
     */
    private int maximumDelayMillis;

    /**
     * The current path round trip time estimate in milliseconds the NACK scheduler reads, or {@code 0}
     * before the transport supplies one.
     *
     * <p>Used as both the due time basis for releasing a NACK and, against
     * {@link NetEqConfig#nackRttLimitMs()}, the suppression threshold; updated through
     * {@link #updateRttMillis(long)}.
     */
    private long currentRttMillis;

    /**
     * The monotonic count of playback pulls so far, the tick that times how long a packet waits in the
     * buffer.
     *
     * <p>Incremented once at the start of every {@link #decideInternal()} and read against each packet's
     * insertion tick to derive its wait time; one tick is one {@link NetEqConfig#getPeriodMs()} get period.
     */
    private long pullTick;

    /**
     * The {@link #pullTick} value at which each buffered packet was inserted, keyed by sequence number.
     *
     * <p>Populated on {@link #insertPacket(RtpAudioPacket)} and consumed on extraction in
     * {@link #materialize(NetEqOperation)} to compute the packet's wait time; an entry is removed when its
     * packet is extracted, discarded on reinsertion of a buffered sequence number, and the whole map is
     * cleared on {@link #flush()}.
     */
    private final Map<Integer, Long> insertTickBySequence;

    /**
     * The running sum of every extracted packet's wait time in milliseconds, the numerator of the mean.
     */
    private long waitTimeSumMillis;

    /**
     * The count of packets whose wait time has been folded into {@link #waitTimeSumMillis}, the denominator
     * of the mean.
     */
    private long waitTimeCount;

    /**
     * Constructs a jitter buffer from the configuration and the codec decode and conceal seam the pull path
     * renders each frame through.
     *
     * <p>The geometry is fixed at sixteen kilohertz mono, the public call audio format the
     * {@link AudioDecoderReceiver.FrameDecoder} seam does not itself report; every estimator, pseudo decoder,
     * and the built in expander is sized to it.
     *
     * @param config  the jitter buffer configuration; never {@code null}
     * @param decoder the codec decode and conceal seam {@link #getAudio()} renders frames through, the same
     *                seam {@link AudioDecoderReceiver} would have driven; never {@code null}
     * @throws NullPointerException if {@code config} or {@code decoder} is {@code null}
     */
    public LiveNetEq(NetEqConfig config, AudioDecoderReceiver.FrameDecoder decoder) {
        this.config = Objects.requireNonNull(config, "config cannot be null");
        this.decoder = Objects.requireNonNull(decoder, "decoder cannot be null");
        this.comfortNoiseDecoder = new ComfortNoiseDecoder(SAMPLE_RATE_HZ, CHANNELS);
        this.dtmfDecoder = new DtmfDecoder(SAMPLE_RATE_HZ, CHANNELS);
        this.comfortNoisePayloadTypes = new HashSet<>();
        this.telephoneEventPayloadTypes = new HashSet<>();
        this.lastDecodedComfortNoise = false;
        this.packetBuffer = new PacketBuffer(config);
        this.delayManager = new DelayManager(config);
        this.decisionLogic = new DecisionLogic(config);
        this.nackTracker = new NackTracker(config);
        this.syncBuffer = new NetEqSyncBuffer(SYNC_BUFFER_SAMPLES);
        this.expand = new NetEqExpand(SAMPLE_RATE_HZ);
        this.lock = new ReentrantLock();
        this.lastOperation = NetEqOperation.NORMAL;
        this.lastFrameVoiceActive = false;
        this.avSyncCorrectionMillis = 0;
        this.nextPtsMicros = 0;
        this.minimumDelayMillis = config.minDelayMs();
        this.maximumDelayMillis = config.maxDelayMs();
        this.currentRttMillis = 0;
        this.pullTick = 0;
        this.insertTickBySequence = new HashMap<>();
        this.waitTimeSumMillis = 0;
        this.waitTimeCount = 0;
        if (Log.DEBUG) {
            LOGGER.log(Level.DEBUG,
                    "neteq: initialized, get period={0}ms min delay={1}ms max delay={2}ms",
                    config.getPeriodMs(), minimumDelayMillis, maximumDelayMillis);
        }
    }

    /**
     * Inserts one received audio packet into the buffer and updates the delay and NACK estimators.
     *
     * <p>Stores the packet for playout, discarding it if it duplicates a buffered packet or precedes the
     * playout cursor, and updates the arrival timing histogram and the NACK tracker from its sequence number
     * and arrival time. May be called from the transport receive thread concurrently with {@link #getAudio()}.
     *
     * @param packet the received packet to buffer; never {@code null}
     * @throws NullPointerException if {@code packet} is {@code null}
     */
    public void insertPacket(RtpAudioPacket packet) {
        Objects.requireNonNull(packet, "packet cannot be null");
        lock.lock();
        try {
            if (packetBuffer.insert(packet)) {
                insertTickBySequence.put(packet.sequenceNumber(), pullTick);
                pruneStaleInsertTicks();
                if (Log.TRACE) {
                    LOGGER.log(Level.TRACE, "neteq: packet inserted seq={0} size={1}",
                            packet.sequenceNumber(), packet.payload().length);
                }
            } else if (Log.DEBUG) {
                LOGGER.log(Level.DEBUG, "neteq: packet discarded (duplicate or stale) seq={0}",
                        packet.sequenceNumber());
            }
            delayManager.update(packet.arrivalMillis(), config.getPeriodMs());
            nackTracker.updateLastReceived(packet.sequenceNumber(), packet.arrivalMillis());
        } finally {
            lock.unlock();
        }
    }

    /**
     * Inserts one received audio packet by its wire fields, the receive path convenience over
     * {@link #insertPacket(RtpAudioPacket)}.
     *
     * <p>The inbound media path and the {@link AudioDecoderReceiver} call this with the demultiplexed and (on
     * the group path) SFrame opened codec packet keyed by its RTP sequence and timestamp; it stamps the packet
     * with the current monotonic time as its arrival, since this entry point does not carry an arrival
     * timestamp, and tags it with the speech payload type {@link #SPEECH_PAYLOAD_TYPE}, since it does not carry
     * the RTP payload type. A WhatsApp call has a single audio payload type, so every packet on this path is
     * the speech codec packet; a deployment that negotiates a comfort noise or telephone event payload type
     * would need this entry point extended to carry the wire payload type and would register it through
     * {@link #registerComfortNoisePayloadType(int)} or {@link #registerTelephoneEventPayloadType(int)}.
     *
     * @param rtpSequence  the packet's 16 bit RTP sequence number
     * @param rtpTimestamp the packet's RTP timestamp
     * @param payload      the decoded transport audio payload to buffer; never {@code null}
     * @throws NullPointerException if {@code payload} is {@code null}
     */
    @Override
    public void insert(int rtpSequence, long rtpTimestamp, byte[] payload) {
        Objects.requireNonNull(payload, "payload cannot be null");
        insertPacket(new RtpAudioPacket(rtpSequence & 0xFFFF, rtpTimestamp, SPEECH_PAYLOAD_TYPE, payload,
                System.currentTimeMillis()));
    }

    /**
     * Registers an RTP payload type as carrying RFC 3389 comfort noise.
     *
     * <p>A buffered packet whose payload type is registered here drives {@link NetEqOperation#RFC3389_CNG}
     * rather than a speech decode, and an empty buffer after such a packet is treated as a comfort noise gap.
     * The registry is empty by default; a WhatsApp call negotiates no separate comfort noise payload type, so
     * this is normally never called and the comfort noise branch stays inert.
     *
     * @param payloadType the 7 bit RTP payload type to mark as comfort noise, in {@code 0..127}
     * @throws IllegalArgumentException if {@code payloadType} is outside {@code 0..127}
     */
    public void registerComfortNoisePayloadType(int payloadType) {
        requirePayloadType(payloadType);
        lock.lock();
        try {
            comfortNoisePayloadTypes.add(payloadType);
            if (Log.DEBUG) {
                LOGGER.log(Level.DEBUG, "neteq: registered comfort noise payload type={0}", payloadType);
            }
        } finally {
            lock.unlock();
        }
    }

    /**
     * Registers an RTP payload type as carrying an RFC 4733 telephone event.
     *
     * <p>A buffered packet whose payload type is registered here drives {@link NetEqOperation#DTMF} rather
     * than a speech decode. The registry is empty by default; a WhatsApp call negotiates no telephone event
     * payload type, so this is normally never called and the telephone event branch stays inert.
     *
     * @param payloadType the 7 bit RTP payload type to mark as a telephone event, in {@code 0..127}
     * @throws IllegalArgumentException if {@code payloadType} is outside {@code 0..127}
     */
    public void registerTelephoneEventPayloadType(int payloadType) {
        requirePayloadType(payloadType);
        lock.lock();
        try {
            telephoneEventPayloadTypes.add(payloadType);
            if (Log.DEBUG) {
                LOGGER.log(Level.DEBUG, "neteq: registered telephone event payload type={0}", payloadType);
            }
        } finally {
            lock.unlock();
        }
    }

    /**
     * {@inheritDoc}
     *
     * @implNote This implementation serves the rendered frame from the {@link #syncBuffer} output queue, so a
     * codec packet that decodes to more than one get period frame is handed out one frame per pull. When the
     * buffer's unplayed span is shorter than a get period frame it runs the shared decide core
     * ({@link #decideInternal()}, which locks for the buffer and decision bookkeeping) to choose an operation
     * and extract any packet, then decodes or conceals the whole packet through the
     * {@link AudioDecoderReceiver.FrameDecoder} and pushes it into the {@link #syncBuffer} (a multi frame MLow
     * decode pushes all three frames), recording the decode's voice activity verdict; otherwise it reuses the
     * held verdict and serves the next frame from the unplayed span without a fresh decision or decode. The
     * decode runs on the pull thread outside the bookkeeping lock, which is held only for the decision and not
     * across the decode; the {@link #syncBuffer} is touched only on the pull thread, so it needs no lock of its
     * own. Each pull copies exactly {@link AudioDecoderReceiver#FRAME_SAMPLES} samples out of the history and
     * stamps the advancing presentation timestamp under the lock.
     */
    @Override
    public AudioFrame getAudio() {
        var frameSamples = frameSamples();
        var pcm = new short[frameSamples];
        renderFrameInto(pcm, frameSamples);
        long pts;
        lock.lock();
        try {
            pts = nextPtsMicros;
            nextPtsMicros += (long) frameSamples * 1_000_000L / SAMPLE_RATE_HZ;
        } finally {
            lock.unlock();
        }
        return new AudioFrame(pcm, pts);
    }

    /**
     * {@inheritDoc}
     *
     * @implNote This implementation renders the frame straight into {@code destination} when it can hold a
     * whole frame, the steady playback pull, so a same length pull allocates no sample array and computes no
     * presentation timestamp the caller would discard. A short pull instead renders a whole frame into a
     * scratch array and hands out only its requested prefix, discarding the remainder so the
     * {@link #syncBuffer} still advances by a whole frame. Both paths run the {@link #decideInternal() decision}
     * and decode under the same locking as {@link #getAudio()} through the shared
     * {@link #renderFrameInto(short[], int)} core.
     *
     * @param destination {@inheritDoc}
     * @param length      {@inheritDoc}
     * @return {@inheritDoc}
     */
    @Override
    public int getAudioInto(short[] destination, int length) {
        var frameSamples = frameSamples();
        if (length >= frameSamples && destination.length >= frameSamples) {
            return renderFrameInto(destination, frameSamples);
        }
        var pcm = new short[frameSamples];
        renderFrameInto(pcm, frameSamples);
        var copied = Math.min(length, frameSamples);
        System.arraycopy(pcm, 0, destination, 0, copied);
        return copied;
    }

    /**
     * Renders one whole get period frame into the given buffer, deciding and decoding a fresh packet only
     * when the output history has run below a frame.
     *
     * <p>When the {@link #syncBuffer} holds fewer than {@code frameSamples} unplayed samples it runs the
     * shared decide core and decodes or conceals the chosen packet into the history; otherwise it serves the
     * next frame straight from the unplayed span without a fresh decision, keeping the held voice activity
     * verdict. The frame is written into {@code destination} from index zero and its tail is zero filled when
     * the history serves a short frame, so the buffer always advances by exactly one whole frame.
     *
     * @param destination  the buffer to render the frame into, at least {@code frameSamples} long
     * @param frameSamples the get period frame length in samples
     * @return {@code frameSamples}, the whole frame count written
     */
    private int renderFrameInto(short[] destination, int frameSamples) {
        if (syncBuffer.futureLength() < frameSamples) {
            var decision = decideInternal();
            render(decision, frameSamples);
        }
        var served = syncBuffer.getNextAudioInterleaved(destination, frameSamples);
        if (served < frameSamples) {
            Arrays.fill(destination, served, frameSamples, (short) 0);
        }
        return frameSamples;
    }

    /**
     * Returns whether the most recently served frame was judged voice active.
     *
     * <p>Reflects the voice activity verdict of the packet the last {@link #getAudio()} frame was decoded
     * from; a concealment, forward error correction, comfort noise, or silence frame is reported inactive, and
     * every get period frame served from one multi frame packet's decoded span reports that packet's single
     * verdict. The playback adapter reads it after each pull for audio level metering and mixing.
     *
     * @return {@code true} if the last served frame carried active speech
     */
    @Override
    public boolean lastFrameVoiceActive() {
        return lastFrameVoiceActive;
    }

    /**
     * Returns the sequence numbers to request a retransmission for at the given time.
     *
     * <p>Returns the sequence numbers the NACK tracker judges still missing and old enough to retransmit, or
     * an empty list when none are due or the link is too slow for retransmission to help.
     *
     * @param nowMillis the current local monotonic time in milliseconds
     * @return the sequence numbers to NACK, ascending; never {@code null}, possibly empty
     */
    public List<Integer> pendingNackList(long nowMillis) {
        lock.lock();
        try {
            return nackTracker.nackList(nowMillis, currentRttMillis);
        } finally {
            lock.unlock();
        }
    }

    /**
     * Updates the path round trip time estimate the NACK scheduler uses as its due time and suppression
     * basis.
     *
     * <p>The transport wires its live round trip time estimate in through this method; the NACK list is then
     * built relative to it, so a packet is requested only once roughly a round trip has elapsed since it was
     * noticed missing and the whole list is suppressed when the estimate exceeds
     * {@link NetEqConfig#nackRttLimitMs()}. Before the first update the estimate is zero, which schedules
     * NACKs optimistically after only the lost audio detection insert time.
     *
     * @implNote This implementation accepts the estimate from the transport rather than estimating round trip
     * time inside the jitter buffer, since the NACK scheduler reads the shared media stream round trip
     * estimate; the buffer is not the owner of that estimate.
     * @param rttMillis the current path round trip time estimate in milliseconds; clamped non negative
     */
    public void updateRttMillis(long rttMillis) {
        lock.lock();
        try {
            this.currentRttMillis = Math.max(0, rttMillis);
            if (Log.TRACE) LOGGER.log(Level.TRACE, "neteq: rtt updated to {0}ms", currentRttMillis);
        } finally {
            lock.unlock();
        }
    }

    /**
     * Sets the lower bound on the target playout delay in milliseconds.
     *
     * <p>Clamps the estimated target level no lower than this bound from the next estimate onward.
     *
     * @param minimumDelayMillis the minimum target playout delay; clamped non negative
     */
    public void setMinimumDelayMillis(int minimumDelayMillis) {
        lock.lock();
        try {
            this.minimumDelayMillis = Math.max(0, minimumDelayMillis);
            this.maximumDelayMillis = Math.max(this.maximumDelayMillis, this.minimumDelayMillis);
            if (Log.DEBUG) {
                LOGGER.log(Level.DEBUG, "neteq: minimum delay set to {0}ms (max now {1}ms)",
                        this.minimumDelayMillis, this.maximumDelayMillis);
            }
        } finally {
            lock.unlock();
        }
    }

    /**
     * Sets the upper bound on the target playout delay in milliseconds.
     *
     * <p>Clamps the estimated target level no higher than this bound from the next estimate onward.
     *
     * @param maximumDelayMillis the maximum target playout delay; clamped no lower than the minimum
     */
    public void setMaximumDelayMillis(int maximumDelayMillis) {
        lock.lock();
        try {
            this.maximumDelayMillis = Math.max(maximumDelayMillis, this.minimumDelayMillis);
            if (Log.DEBUG) {
                LOGGER.log(Level.DEBUG, "neteq: maximum delay set to {0}ms", this.maximumDelayMillis);
            }
        } finally {
            lock.unlock();
        }
    }

    /**
     * Ingests a lip sync delay correction from the video timing path.
     *
     * <p>Biases the target playout delay by the supplied correction so audio and video stay synchronized; a
     * positive value lengthens the audio delay to wait for slower video.
     *
     * @param correctionMillis the signed delay correction in milliseconds
     */
    public void ingestAvSyncFeedbackMillis(int correctionMillis) {
        lock.lock();
        try {
            this.avSyncCorrectionMillis = correctionMillis;
            if (Log.TRACE) LOGGER.log(Level.TRACE, "neteq: avsync correction set to {0}ms", correctionMillis);
        } finally {
            lock.unlock();
        }
    }

    /**
     * {@inheritDoc}
     *
     * @implNote This implementation rounds {@link AvSyncFeedback#correctionMs()} to whole milliseconds and
     * forwards it to {@link #ingestAvSyncFeedbackMillis(int)}, so the video timing path drives this buffer
     * directly as its {@link AvSyncFeedbackSink}.
     */
    @Override
    public void applyAvSyncFeedback(AvSyncFeedback feedback) {
        Objects.requireNonNull(feedback, "feedback cannot be null");
        ingestAvSyncFeedbackMillis((int) Math.round(feedback.correctionMs()));
    }

    /**
     * Flushes the buffer, draining queued packets on a stall.
     *
     * <p>Drops queued packets so playout can resume near the target level, and resets the estimators so
     * jitter from before the stall does not bias the post stall target.
     */
    public void flush() {
        lock.lock();
        try {
            if (Log.WARNING) {
                LOGGER.log(Level.WARNING, "neteq: flushing buffer, dropping {0} queued packets after stall",
                        packetBuffer.size());
            }
            packetBuffer.clear();
            delayManager.reset();
            decisionLogic.reset();
            nackTracker.reset();
            syncBuffer.reset();
            expand.reset();
            insertTickBySequence.clear();
            lastOperation = NetEqOperation.NORMAL;
            lastDecodedComfortNoise = false;
        } finally {
            lock.unlock();
        }
    }

    /**
     * Returns a snapshot of the buffer's lifetime counters.
     *
     * @implNote This implementation reports {@link NetEqStatistics#meanWaitTimeMs()} from the running wait
     * time accumulator {@link #recordWaitTime(int)} maintains as packets are extracted; the snapshot is taken
     * under the lock so it is consistent with the buffer span and target read in the same critical section.
     * @return the current statistics snapshot; never {@code null}
     */
    public NetEqStatistics statistics() {
        lock.lock();
        try {
            var target = effectiveTargetMillis();
            var span = packetBuffer.spanMillis(packetBuffer.approximateSamplesPerPacket());
            return new NetEqStatistics(
                    normalFrames,
                    expandedFrames,
                    acceleratedFrames,
                    preemptiveExpandedFrames,
                    mergedFrames,
                    comfortNoiseFrames,
                    packetBuffer.bufferFlushes(),
                    packetBuffer.packetsDiscarded(),
                    meanWaitTimeMillis(),
                    target,
                    span);
        } finally {
            lock.unlock();
        }
    }

    /**
     * One internal render decision: the chosen operation and the payloads to render it with.
     *
     * <p>For a decode operation {@link #payload()} is the extracted packet; for a forward error correction
     * concealment {@link #fecPayload()} is the following packet whose in band copy reconstructs the lost
     * frame; both are {@code null} for a plain conceal or comfort noise.
     *
     * @param operation  the chosen operation; never {@code null}
     * @param payload    the packet to decode, or {@code null}
     * @param fecPayload the following packet carrying the forward error correction copy, or {@code null}
     */
    private record InternalDecision(NetEqOperation operation, byte[] payload, byte[] fecPayload) {
    }

    /**
     * Runs the shared decide core: chooses an operation, extracts any packet, and updates the counters.
     *
     * <p>Holds the lock for the buffer and decision logic interaction. When the next contiguous buffered
     * packet's payload type resolves to the comfort noise or telephone event role, that role overrides the
     * level based decision with {@link NetEqOperation#RFC3389_CNG} or {@link NetEqOperation#DTMF}; otherwise
     * it builds the decision logic input from the buffer span, the effective target, the next packet
     * availability, whether a comfort noise gap is in effect, and whether the codec exposes loss concealment,
     * then chooses an operation. For an operation that consumes a packet it extracts the packet from the
     * buffer and advances the NACK decoded cursor; a concealment looks ahead for a following packet to drive a
     * forward error correction reconstruction when the configuration permits. The chosen operation is recorded
     * for the next pull and folded into the statistics.
     *
     * <p>The buffered span the decision reads is denominated in the buffer's measured per packet sample count
     * ({@link PacketBuffer#approximateSamplesPerPacket()}), not the render frame size, so a 60 ms MLow stream
     * whose packet spans three render frames is counted at its true buffered duration rather than a third of
     * it; for the 20 ms Opus stream the measured spacing is the render frame size, so the span is identical.
     *
     * @return the internal decision; never {@code null}
     */
    private InternalDecision decideInternal() {
        lock.lock();
        try {
            pullTick++;
            var operation = chooseOperation();
            var decision = materialize(operation);
            if (Log.TRACE) {
                LOGGER.log(Level.TRACE, "neteq: decision={0} buffer span={1}ms target={2}ms",
                        decision.operation(),
                        packetBuffer.spanMillis(packetBuffer.approximateSamplesPerPacket()),
                        effectiveTargetMillis());
            }
            if (decision.operation() != lastOperation && Log.DEBUG) {
                LOGGER.log(Level.DEBUG, "neteq: operation {0} -> {1}", lastOperation, decision.operation());
            }
            lastOperation = decision.operation();
            countOperation(decision.operation());
            return decision;
        } finally {
            lock.unlock();
        }
    }

    /**
     * Chooses the operation for one pull, applying the payload type role override before the level decision.
     *
     * <p>When the next contiguous buffered packet resolves to the comfort noise role the operation is
     * {@link NetEqOperation#RFC3389_CNG}, and when it resolves to the telephone event role the operation is
     * {@link NetEqOperation#DTMF}; both override the level based decision, dispatching a comfort noise or DTMF
     * payload type ahead of the speech path. Otherwise the {@link DecisionLogic} chooses from the buffer span
     * against the target, with the span denominated in the buffer's measured per packet sample count
     * ({@link PacketBuffer#approximateSamplesPerPacket()}) so a 60 ms MLow packet counts as its full duration.
     * Called with the lock held.
     *
     * @return the chosen operation; never {@code null}
     */
    private NetEqOperation chooseOperation() {
        var next = packetBuffer.peekNext();
        var contiguous = packetBuffer.nextSequenceContiguous();
        if (next != null && contiguous) {
            if (telephoneEventPayloadTypes.contains(next.payloadType())) {
                return NetEqOperation.DTMF;
            }
            if (comfortNoisePayloadTypes.contains(next.payloadType())) {
                return NetEqOperation.RFC3389_CNG;
            }
        }
        var span = packetBuffer.spanMillis(packetBuffer.approximateSamplesPerPacket());
        var target = effectiveTargetMillis();
        var available = next != null;
        var comfortNoiseActive = !available && lastDecodedComfortNoise;
        var codecHasPlc = decoderAdvertisesPlc();
        var input = new DecisionLogic.Input(
                span, target, available, contiguous, comfortNoiseActive, codecHasPlc, lastOperation);
        return decisionLogic.decide(input);
    }

    /**
     * Materializes an operation into a decision, extracting packets from the buffer as the operation needs.
     *
     * <p>A decode or time stretch operation extracts the next packet, advances the decoded cursor, and clears
     * the comfort noise gap flag; a comfort noise or telephone event operation extracts its descriptor packet
     * and, for comfort noise, sets the gap flag so a subsequent empty buffer continues the comfort noise; a
     * concealment looks ahead for a following packet to reconstruct from when forward error correction is not
     * skipped, otherwise yields a plain conceal. Called with the lock held.
     *
     * @param operation the chosen operation
     * @return the materialized decision
     */
    private InternalDecision materialize(NetEqOperation operation) {
        return switch (operation) {
            case NORMAL, MERGE, ACCELERATE, FAST_ACCELERATE, PREEMPTIVE_EXPAND -> {
                var packet = extractAndAccount();
                if (packet != null) {
                    lastDecodedComfortNoise = false;
                    yield new InternalDecision(operation, packet.payload(), null);
                }
                yield new InternalDecision(NetEqOperation.EXPAND, null, null);
            }
            case RFC3389_CNG -> {
                var packet = extractAndAccount();
                lastDecodedComfortNoise = true;
                yield new InternalDecision(operation, packet == null ? null : packet.payload(), null);
            }
            case DTMF -> {
                var packet = extractAndAccount();
                lastDecodedComfortNoise = false;
                yield new InternalDecision(operation, packet == null ? null : packet.payload(), null);
            }
            case EXPAND, CODEC_PLC -> {
                if (!config.skipNackWithFec()) {
                    var lookahead = packetBuffer.peekNext();
                    if (lookahead != null) {
                        yield new InternalDecision(operation, null, lookahead.payload());
                    }
                }
                yield new InternalDecision(operation, null, null);
            }
            default -> new InternalDecision(operation, null, null);
        };
    }

    /**
     * Extracts the next buffered packet, advancing the NACK decoded cursor and folding its wait time in.
     *
     * <p>The shared extraction bookkeeping for every operation that consumes a buffered packet. Called with
     * the lock held.
     *
     * @return the extracted packet, or {@code null} when the buffer is empty
     */
    private RtpAudioPacket extractAndAccount() {
        var packet = packetBuffer.extractNext();
        if (packet != null) {
            nackTracker.updateLastDecoded(packet.sequenceNumber());
            recordWaitTime(packet.sequenceNumber());
        }
        return packet;
    }

    /**
     * Renders the PCM for an internal decision through the codec seam, records its voice activity verdict, and
     * pushes it into the output history.
     *
     * <p>Maps the decision onto a codec seam call and then the time stretch or merge operation the decision
     * names: a normal decode of the packet pushed in full so a multi frame codec packet leaves its extra frames
     * as the unplayed span the next pulls serve; an accelerate or preemptive expand that shortens or lengthens
     * the decoded audio by one pitch period; a merge that cross fades the decoded packet onto the tail of the
     * preceding expansion held in the {@link #syncBuffer}; a forward error correction decode of the following
     * packet; a codec conceal; comfort noise through the {@link ComfortNoiseDecoder} (decoding the descriptor
     * when one was extracted, otherwise continuing the gap); a telephone event tone through the
     * {@link DtmfDecoder}; or a zeroed silence frame for codec internal comfort noise and the undefined
     * sentinel. A speech decode decision missing its payload falls back to conceal so a malformed decision
     * still yields a frame. The voice activity verdict {@link #lastFrameVoiceActive} carries is set from the
     * codec seam's {@link AudioDecoderReceiver.DecodedFrame#voiceActive()} for a normal, accelerate,
     * preemptive expand, or merge decode of a real packet, and cleared for a concealment, forward error
     * correction, comfort noise, or silence frame. The rendered PCM is pushed into the {@link #syncBuffer} so
     * the recent decoded audio is available to the next time stretch and concealment operations and so the
     * served get period frame is drawn from it.
     *
     * @implNote This implementation drives the ported WSOLA operations over the decoded PCM
     * {@link NetEqSyncBuffer} history. The accelerate ({@link NetEqOperation#ACCELERATE},
     * {@link NetEqOperation#FAST_ACCELERATE}) and preemptive expand ({@link NetEqOperation#PREEMPTIVE_EXPAND})
     * decisions run {@link NetEqTimeStretch}, which performs the lag search and the pitch period splice to
     * lengthen or shorten the decoded audio before {@link #trailingFrame(short[], int)} sizes the playout
     * frame; a frame whose criterion fails falls back to the plain decode. The merge
     * ({@link NetEqOperation#MERGE}) decision runs {@link NetEqMerge}, the energy matched cross fade, against
     * the expansion tail the prior {@link NetEqOperation#EXPAND} frames left in the {@link #syncBuffer}. The
     * concealment extrapolation ({@link NetEqOperation#EXPAND}, {@link NetEqOperation#CODEC_PLC}) runs the
     * autoregressive synthesizer ({@link NetEqExpand}) over the {@link #syncBuffer} history, except when the
     * codec advertises its own loss concealment and the configuration prefers it, in which case the codec
     * conceal is used; see {@link #renderExpand(InternalDecision, int)}. A normal decode is pushed in full; the
     * time stretch, merge, and concealment arms render to one playout frame.
     *
     * @param decision     the internal decision; never {@code null}
     * @param frameSamples the per channel sample count of one served get period frame
     * @return the rendered PCM, a positive multiple of {@code frameSamples} long: one frame for the time
     * stretch, merge, concealment, comfort noise, and silence arms and for a 20 ms decode, or several for a
     * multi frame normal decode such as the 60 ms MLow packet
     */
    private short[] render(InternalDecision decision, int frameSamples) {
        if (decision.operation() == NetEqOperation.NORMAL && decision.payload() != null) {
            expand.notifyDecoded();
            var scratch = decodeScratch(frameSamples);
            var decoded = decoder.decodeInto(decision.payload(), frameSamples, false, scratch);
            lastFrameVoiceActive = decoded.voiceActive();
            var length = fitLengthToFrames(decoded.length(), frameSamples);
            if (length > decoded.length()) {
                Arrays.fill(scratch, decoded.length(), length, (short) 0);
            }
            syncBuffer.pushBack(scratch, 0, length);
            return scratch;
        }
        var rendered = switch (decision.operation()) {
            case NORMAL -> {
                // A NORMAL decision carrying a payload is decoded through the fill into scratch fast path
                // above; only a NORMAL decision with no payload reaches this arm.
                lastFrameVoiceActive = false;
                yield decoder.conceal(frameSamples);
            }
            case ACCELERATE, FAST_ACCELERATE -> renderAccelerate(decision, frameSamples);
            case PREEMPTIVE_EXPAND -> renderPreemptiveExpand(decision, frameSamples);
            case MERGE -> renderMerge(decision, frameSamples);
            case EXPAND, CODEC_PLC -> renderExpand(decision, frameSamples);
            case RFC3389_CNG -> {
                lastFrameVoiceActive = false;
                if (decision.payload() == null) {
                    yield fit(comfortNoiseDecoder.conceal(frameSamples), frameSamples);
                }
                yield fit(comfortNoiseDecoder.decode(decision.payload(), frameSamples, false), frameSamples);
            }
            case DTMF -> {
                lastFrameVoiceActive = false;
                if (decision.payload() == null) {
                    yield fit(dtmfDecoder.conceal(frameSamples), frameSamples);
                }
                yield fit(dtmfDecoder.decode(decision.payload(), frameSamples, false), frameSamples);
            }
            case CODEC_INTERNAL_CNG, UNDEFINED -> {
                lastFrameVoiceActive = false;
                yield new short[frameSamples];
            }
        };
        syncBuffer.pushBack(rendered);
        return rendered;
    }

    /**
     * Renders a concealment frame, extrapolating the lost audio through the built in autoregressive expander
     * or the codec's own loss concealment.
     *
     * <p>When the decision carries a forward error correction copy of the lost frame in the following packet,
     * that copy is reconstructed by decoding the following packet through the
     * {@link AudioDecoderReceiver.FrameDecoder} with the recovery flag set, so the codec extracts the lost
     * frame's in band redundant copy rather than the following frame; otherwise, when the codec advertises its
     * own packet loss concealment and the configuration prefers it, the codec conceal is used; otherwise the
     * built in {@link NetEqExpand} autoregressive synthesizer extrapolates the lost frame from the
     * {@link #syncBuffer} history. The built in expander analyzes the history on the first frame of a
     * concealment run and synthesizes a faithful variable decay continuation on each subsequent frame. A
     * reconstructed frame carries no voice activity verdict of its own, so the frame is reported inactive.
     *
     * @implNote This implementation applies the codec preference and the forward error correction first order
     * of the concealment arm. The recovery decode passes the following packet with the recovery flag so the
     * codec reconstructs the lost frame's in band redundant copy. When no copy is available the built in
     * {@link NetEqExpand} runs only when the codec does not advertise its own concealment
     * ({@link #decoderAdvertisesPlc()}) or the configuration disables the codec preference
     * ({@link NetEqConfig#enableCodecPlc()}), so the built in expander runs only when the codec concealment is
     * not used. A history too short to analyze falls back to the codec conceal so a frame is always produced.
     *
     * @param decision     the internal decision; never {@code null}
     * @param frameSamples the per channel sample count to render
     * @return the rendered PCM, {@code frameSamples} long
     */
    private short[] renderExpand(InternalDecision decision, int frameSamples) {
        lastFrameVoiceActive = false;
        if (decision.fecPayload() != null) {
            expand.notifyDecoded();
            if (Log.TRACE) LOGGER.log(Level.TRACE, "neteq: concealment via fec reconstruction");
            return fit(decoder.decode(decision.fecPayload(), frameSamples, true).samples(), frameSamples);
        }
        if (config.enableCodecPlc() && decoderAdvertisesPlc()) {
            if (Log.TRACE) LOGGER.log(Level.TRACE, "neteq: concealment via codec plc");
            return fit(decoder.conceal(frameSamples), frameSamples);
        }
        if (Log.TRACE) LOGGER.log(Level.TRACE, "neteq: concealment via built-in expander");
        return expand.process(syncBuffer, frameSamples);
    }

    /**
     * Renders an accelerate frame, time compressing the decoded audio by one pitch period when the criterion
     * permits.
     *
     * <p>Decodes the scheduled packet, runs {@link NetEqTimeStretch#accelerate} to remove a pitch period at
     * the peak window, and fits the shortened result to the playout frame; a missing payload or a failed
     * criterion falls back to the plain decode. The active speech threshold is taken from the packet's own
     * voice activity verdict.
     *
     * @param decision     the internal decision
     * @param frameSamples the per channel sample count to render
     * @return the rendered PCM, {@code frameSamples} long
     */
    private short[] renderAccelerate(InternalDecision decision, int frameSamples) {
        if (decision.payload() == null) {
            lastFrameVoiceActive = false;
            return fit(decoder.conceal(frameSamples), frameSamples);
        }
        expand.notifyDecoded();
        var decoded = decoder.decode(decision.payload(), frameSamples, false);
        lastFrameVoiceActive = decoded.voiceActive();
        var analysis = analysisBuffer(decoded.samples());
        var result = NetEqTimeStretch.accelerate(analysis, analysis.length, SAMPLE_RATE_HZ,
                decoded.voiceActive(), true);
        return trailingFrame(result.output(), frameSamples);
    }

    /**
     * Renders a preemptive expand frame, time stretching the decoded audio by one pitch period when the
     * criterion permits.
     *
     * <p>Decodes the scheduled packet, runs {@link NetEqTimeStretch#preemptiveExpand} to insert a pitch period
     * at the peak window, and fits the lengthened result to the playout frame; a missing payload or a failed
     * criterion falls back to the plain decode. The old data span is the unplayed history the splice extends.
     *
     * @param decision     the internal decision
     * @param frameSamples the per channel sample count to render
     * @return the rendered PCM, {@code frameSamples} long
     */
    private short[] renderPreemptiveExpand(InternalDecision decision, int frameSamples) {
        if (decision.payload() == null) {
            lastFrameVoiceActive = false;
            return fit(decoder.conceal(frameSamples), frameSamples);
        }
        expand.notifyDecoded();
        var decoded = decoder.decode(decision.payload(), frameSamples, false);
        lastFrameVoiceActive = decoded.voiceActive();
        var oldData = syncBuffer.futureLength();
        var analysis = analysisBuffer(decoded.samples());
        var result = NetEqTimeStretch.preemptiveExpand(analysis, analysis.length, SAMPLE_RATE_HZ,
                oldData, decoded.voiceActive(), true);
        return trailingFrame(result.output(), frameSamples);
    }

    /**
     * Builds the time stretch analysis buffer from the recent history and the decoded frame.
     *
     * <p>Prepends a bounded run of the most recent rendered samples held in the {@link #syncBuffer} to the
     * decoded frame so the lag search has the full four kilohertz decimation window the pitch search needs,
     * which a single short render frame does not supply on its own. The lookback is bounded so the splice the
     * operation places at its peak window acts on the boundary between the recent history and the new frame
     * rather than deep in old audio. The decoded frame is the trailing portion of the returned buffer.
     *
     * @implNote This implementation gathers the contiguous recent span into one array because the operation
     * takes a flat buffer: a bounded {@link #STRETCH_LOOKBACK_SAMPLES} lookback of history followed by the
     * decoded frame, sized so {@link NetEqSignalProcessing#downsampleTo4kHz} can produce the full
     * {@link NetEqTimeStretch#ANALYSIS_WINDOW} analysis window.
     *
     * @param decoded the decoded frame
     * @return the history prefixed analysis buffer ending in the decoded frame
     */
    private short[] analysisBuffer(short[] decoded) {
        var lookback = Math.min(syncBuffer.capacity(), STRETCH_LOOKBACK_SAMPLES);
        var buffer = new short[lookback + decoded.length];
        var base = syncBuffer.capacity() - lookback;
        syncBuffer.copyRange(base, buffer, 0, lookback);
        System.arraycopy(decoded, 0, buffer, lookback, decoded.length);
        return buffer;
    }

    /**
     * Returns the trailing playout frame of a time stretched analysis buffer.
     *
     * <p>After the splice has lengthened or shortened the analysis buffer, the rendered frame is its last
     * {@code frameSamples} samples, the most recent audio the playout consumes; a buffer shorter than the
     * frame is zero padded at the front.
     *
     * @param stretched    the spliced analysis buffer
     * @param frameSamples the playout frame size
     * @return the trailing {@code frameSamples} samples
     */
    private static short[] trailingFrame(short[] stretched, int frameSamples) {
        var out = new short[frameSamples];
        var copy = Math.min(stretched.length, frameSamples);
        System.arraycopy(stretched, stretched.length - copy, out, frameSamples - copy, copy);
        return out;
    }

    /**
     * Renders a merge frame, cross fading the decoded packet onto the tail of the preceding expansion.
     *
     * <p>Decodes the arriving packet and energy matches and cross fades it onto the recent expansion samples
     * held in the {@link #syncBuffer}, so the first packet after a concealment gap blends in without a click;
     * a missing payload falls back to the codec conceal. The expansion tail is the most recent
     * {@link NetEqMerge#MAX_EXPANDED_LENGTH} capped run of history samples.
     *
     * @param decision     the internal decision
     * @param frameSamples the per channel sample count to render
     * @return the rendered PCM, {@code frameSamples} long
     */
    private short[] renderMerge(InternalDecision decision, int frameSamples) {
        if (decision.payload() == null) {
            lastFrameVoiceActive = false;
            return fit(decoder.conceal(frameSamples), frameSamples);
        }
        expand.notifyDecoded();
        var decoded = decoder.decode(decision.payload(), frameSamples, false);
        lastFrameVoiceActive = decoded.voiceActive();
        var merged = mergeWithHistory(decoded.samples());
        return fit(merged, frameSamples);
    }

    /**
     * Cross fades a freshly decoded frame onto the expansion tail held in the history, the merge splice.
     *
     * <p>Pulls the recent expansion samples from the {@link #syncBuffer}, scales the expansion to the decoded
     * energy, and cross fades from the expansion into the decoded audio over the leading samples of the frame,
     * returning the blended frame. When too little history is available the decoded frame is returned
     * unchanged.
     *
     * @implNote This implementation drives {@link NetEqMerge}: the expansion energy weight is
     * {@link NetEqMerge#signalScaling}, and the leading {@code min(decoded.length, history)} samples are cross
     * faded through {@link NetEqMerge#rampBlend} with the ramp slope
     * {@code increment = min(4194/fs_mult, (2^20 - weight*64)/old_length)}, the merge splice specialized to the
     * single mono channel. The full lag alignment and the variable length output trimming are bounded here to
     * the fixed playout frame; the energy match and the cross fade are the audible operations.
     *
     * @param decoded the decoded frame
     * @return the merged frame
     */
    private short[] mergeWithHistory(short[] decoded) {
        var fsMult = SAMPLE_RATE_HZ / 8_000;
        var available = Math.min(syncBuffer.futureLength() == 0
                ? syncBuffer.capacity() : syncBuffer.futureLength(), NetEqMerge.MAX_EXPANDED_LENGTH);
        var overlap = Math.min(decoded.length, available);
        if (overlap <= 0) {
            return decoded;
        }
        var expanded = new short[overlap];
        var base = syncBuffer.capacity() - overlap;
        syncBuffer.copyRange(base, expanded, 0, overlap);
        var expandWeight = NetEqMerge.signalScaling(expanded, decoded, decoded.length, fsMult, 0);
        var increment = Math.min(4194 / fsMult,
                Integer.divideUnsigned((1 << 20) - (expandWeight << 6), Math.max(1, overlap)));
        var out = decoded.clone();
        var weightState = new int[]{expandWeight};
        NetEqMerge.rampBlend(out, 0, expanded, 0, decoded, 0, overlap, increment, weightState);
        return out;
    }

    /**
     * Returns the per channel sample count of one rendered frame for the configured get period.
     *
     * @return the frame sample count, {@code 320} for the captured 20 ms get period at 16 kHz
     */
    private int frameSamples() {
        return SAMPLE_RATE_HZ / 1000 * config.getPeriodMs();
    }

    /**
     * Returns the effective target playout level after applying the explicit override, the mutable bounds,
     * and the avsync correction.
     *
     * <p>When {@link NetEqConfig#targetDelayMs()} is positive it is an explicit target override that replaces
     * the delay manager estimate; otherwise the estimate is used. The chosen base is biased by the avsync
     * correction and clamped into the mutable minimum and maximum delay bounds.
     *
     * @implNote This implementation honors {@link NetEqConfig#targetDelayMs()} as a forced target on the
     * shared decide path rather than inside the {@link DelayManager}: the manager always estimates so the
     * histogram and statistics remain populated, and the override is applied where the decision logic reads
     * the target. The captured WhatsApp configuration leaves the forced target at zero, so the estimate is
     * operative in production and the override is the path a deployment that pins a fixed playout delay would
     * take.
     * @return the effective target level in milliseconds
     */
    private int effectiveTargetMillis() {
        var estimate = config.targetDelayMs() > 0 ? config.targetDelayMs() : delayManager.targetLevelMillis();
        var base = estimate + avSyncCorrectionMillis;
        return Math.clamp(base, minimumDelayMillis, maximumDelayMillis);
    }

    /**
     * Folds a rendered operation into the lifetime statistics counters.
     *
     * @param operation the operation that produced the frame
     */
    private void countOperation(NetEqOperation operation) {
        switch (operation) {
            case NORMAL -> normalFrames++;
            case EXPAND, CODEC_PLC -> expandedFrames++;
            case ACCELERATE, FAST_ACCELERATE -> acceleratedFrames++;
            case PREEMPTIVE_EXPAND -> preemptiveExpandedFrames++;
            case MERGE -> mergedFrames++;
            case RFC3389_CNG, CODEC_INTERNAL_CNG -> comfortNoiseFrames++;
            case DTMF, UNDEFINED -> {
            }
        }
    }

    /**
     * Returns whether the registered speech decoder exposes its own packet loss concealment.
     *
     * <p>Drives {@link DecisionLogic.Input#codecHasPlc()}: when set, and {@link NetEqConfig#enableCodecPlc()}
     * is on, a lost packet is concealed by the codec ({@link NetEqOperation#CODEC_PLC}) in preference to the
     * built in expander. The {@link AudioDecoderReceiver.FrameDecoder} seam always exposes a
     * {@link AudioDecoderReceiver.FrameDecoder#conceal(int)} entry point, so a bound decoder always advertises
     * concealment; the speech codecs WhatsApp negotiates (Opus and MLow) both carry packet loss concealment.
     *
     * @return {@code true} if the speech decoder conceals lost packets itself
     */
    private boolean decoderAdvertisesPlc() {
        return decoder != null;
    }

    /**
     * Validates a payload type against the 7 bit RTP range.
     *
     * @param payloadType the payload type to validate
     * @throws IllegalArgumentException if {@code payloadType} is outside {@code 0..127}
     */
    private static void requirePayloadType(int payloadType) {
        if (payloadType < 0 || payloadType > RtpAudioPacket.MAX_PAYLOAD_TYPE) {
            throw new IllegalArgumentException("payloadType must be in 0..127, got " + payloadType);
        }
    }

    /**
     * Folds an extracted packet's buffer wait time into the running mean, the wait time accumulator.
     *
     * <p>The wait time is the number of get periods that elapsed between the packet's insertion tick and the
     * current pull tick, times the get period duration: a packet inserted between pulls and decoded on the
     * next pull waited one period. A packet whose insertion tick was not recorded (a sequence number that was
     * discarded as a duplicate but is reached here through a reinsertion race) contributes nothing. Called
     * with the lock held, from {@link #materialize(NetEqOperation)} as each packet is extracted.
     *
     * @implNote This implementation ticks the {@link #pullTick} timer once per pull through
     * {@link #decideInternal()} and starts a per packet stopwatch at insertion in
     * {@link #insertTickBySequence}, so the wait time here is {@code (pullTick - insertTick) * getPeriodMs},
     * the tick count since insertion scaled by the per tick duration.
     * @param sequenceNumber the extracted packet's 16 bit sequence number
     */
    private void recordWaitTime(int sequenceNumber) {
        var insertTick = insertTickBySequence.remove(sequenceNumber);
        if (insertTick == null) {
            return;
        }
        waitTimeSumMillis += (pullTick - insertTick) * config.getPeriodMs();
        waitTimeCount++;
    }

    /**
     * Drops the oldest insertion tick entries so the map cannot outgrow the buffer's capacity.
     *
     * <p>An entry leaves naturally when its packet is extracted by {@link #recordWaitTime(int)}, but the
     * packet buffer's own smart flush drops over buffered packets without extracting them, which would
     * otherwise orphan their entries here. Since the buffer never holds more than
     * {@link NetEqConfig#maxPacketsInBuffer()} packets, any entries beyond that count belong to flushed
     * packets that can no longer be extracted; the lowest insertion ticks are the oldest, so evicting them
     * cannot discard a still buffered packet whose wait time is yet to be recorded. Called with the lock held,
     * after a successful insert.
     */
    private void pruneStaleInsertTicks() {
        var excess = insertTickBySequence.size() - config.maxPacketsInBuffer();
        if (excess <= 0) {
            return;
        }
        var entries = new ArrayList<>(insertTickBySequence.entrySet());
        entries.sort(Map.Entry.comparingByValue());
        for (var i = 0; i < excess; i++) {
            insertTickBySequence.remove(entries.get(i).getKey());
        }
    }

    /**
     * Returns the running mean packet wait time in milliseconds, or {@code 0} before any packet decoded.
     *
     * <p>The sum of every extracted packet's wait time over the count of extracted packets. Called with the
     * lock held.
     *
     * @return the mean wait time in milliseconds
     */
    private double meanWaitTimeMillis() {
        if (waitTimeCount == 0) {
            return 0.0;
        }
        return (double) waitTimeSumMillis / waitTimeCount;
    }

    /**
     * Resizes a decoded frame to exactly the requested sample count, padding with silence or truncating.
     *
     * <p>A codec may decode fewer or more samples than the frame holds; the jitter buffer renders a fixed
     * frame size, so the decoded samples are fit to it: a shorter result is zero padded and a longer result is
     * truncated.
     *
     * @param decoded      the decoded samples
     * @param frameSamples the required sample count
     * @return an array of exactly {@code frameSamples} samples
     */
    private static short[] fit(short[] decoded, int frameSamples) {
        if (decoded.length == frameSamples) {
            return decoded;
        }
        var out = new short[frameSamples];
        System.arraycopy(decoded, 0, out, 0, Math.min(decoded.length, frameSamples));
        return out;
    }

    /**
     * Resizes a normal decode to a whole number of get period frames, padding the last partial frame with
     * silence, so the {@link #syncBuffer} push preserves the get period grid.
     *
     * <p>A codec packet decodes to a whole number of get period frames (the 20 ms Opus packet to one, the
     * 60 ms MLow packet to three), and {@link #getAudio()} serves the decoded span one get period frame at a
     * time; this rounds a decode that returned a sample count that is not a multiple up to the next whole
     * frame, padding the tail with zeros, so the served frames stay aligned to the get period grid and a short
     * decode does not underrun a served frame. A decode that already spans a whole number of frames is returned
     * unchanged, so a 320 sample Opus frame and a 960 sample MLow packet pass through untouched while the
     * multi frame span is preserved rather than truncated to one frame.
     *
     * @param decoded      the decoded samples
     * @param frameSamples the per channel sample count of one served get period frame
     * @return the decode resized up to the next whole multiple of {@code frameSamples}, at least one frame
     */
    private static short[] fitToFrames(short[] decoded, int frameSamples) {
        if (decoded.length > 0 && decoded.length % frameSamples == 0) {
            return decoded;
        }
        var frames = Math.max(1, (decoded.length + frameSamples - 1) / frameSamples);
        var out = new short[frames * frameSamples];
        System.arraycopy(decoded, 0, out, 0, decoded.length);
        return out;
    }

    /**
     * Returns the reusable {@link NetEqOperation#NORMAL} decode buffer, sized to hold the largest packet the
     * codec decodes to.
     *
     * <p>Sizes the buffer to four get period frames, above the three a 60 ms MLow packet decodes to, and
     * reuses it across pulls; the buffer is only ever touched on the single pull thread, so it needs no
     * synchronization.
     *
     * @param frameSamples the per channel sample count of one get period frame
     * @return the reusable decode buffer, at least {@code 4 * frameSamples} samples long
     */
    private short[] decodeScratch(int frameSamples) {
        var needed = 4 * frameSamples;
        if (decodeScratch == null || decodeScratch.length < needed) {
            decodeScratch = new short[needed];
        }
        return decodeScratch;
    }

    /**
     * Rounds a decoded sample count up to a whole number of get period frames, the length only form of
     * {@link #fitToFrames(short[], int)}.
     *
     * <p>Computes the padded length {@link #fitToFrames(short[], int)} would produce for a decode of
     * {@code length} samples, so the {@link NetEqOperation#NORMAL} fast path can zero fill the scratch tail and
     * append a whole number of frames to the {@link #syncBuffer} without allocating a resized array. A length
     * that is already a positive multiple of {@code frameSamples} is returned unchanged.
     *
     * @param length       the decoded sample count
     * @param frameSamples the per channel sample count of one get period frame
     * @return the count rounded up to the next whole multiple of {@code frameSamples}, at least one frame
     */
    private static int fitLengthToFrames(int length, int frameSamples) {
        if (length > 0 && length % frameSamples == 0) {
            return length;
        }
        return Math.max(1, (length + frameSamples - 1) / frameSamples) * frameSamples;
    }
}
